class CctvExecutor{

    public static void main(String[] args) {

        Cctv cctv1 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv1.cameraBrand);
        System.out.println("The cameraId is : " + cctv1.cameraId);
        System.out.println("The cameraPrice is : " + cctv1.cameraPrice);
        System.out.println("The isAvailable is : " + cctv1.isAvailable);
        System.out.println("The cameraType is : " + cctv1.cameraType);
        System.out.println("The resolutionMP is : " + cctv1.resolutionMP);
        System.out.println("The weight is : " + cctv1.weight);
        System.out.println("The isNightVision is : " + cctv1.isNightVision);
        System.out.println("The lensType is : " + cctv1.lensType);
        System.out.println("The warrantyYears is : " + cctv1.warrantyYears);
        System.out.println("The viewAngle is : " + cctv1.viewAngle);
        System.out.println("The isWireless is : " + cctv1.isWireless);
        System.out.println("The color is : " + cctv1.color);
        System.out.println("The stockQuantity is : " + cctv1.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv1.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv1.isWaterproof);
        System.out.println("The storageType is : " + cctv1.storageType);
        System.out.println("The rating is : " + cctv1.rating);
        System.out.println("The frameRate is : " + cctv1.frameRate);
        System.out.println("The isCertified is : " + cctv1.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv1.manufacturingYear);
        System.out.println("The cableLength is : " + cctv1.cableLength);
        System.out.println("The supportsMobileView is : " + cctv1.supportsMobileView);
        System.out.println("The certificationType is : " + cctv1.certificationType);

        cctv1.cameraBrand = "Hikvision";
        cctv1.cameraId = 1;
        cctv1.cameraPrice = 1500.50;
        cctv1.isAvailable = true;
        cctv1.cameraType = "Dome";
        cctv1.resolutionMP = 5;
        cctv1.weight = 0.75;
        cctv1.isNightVision = true;
        cctv1.lensType = "Wide";
        cctv1.warrantyYears = 2;
        cctv1.viewAngle = 120.0;
        cctv1.isWireless = false;
        cctv1.color = "White";
        cctv1.stockQuantity = 30;
        cctv1.powerConsumption = 12.5;
        cctv1.isWaterproof = true;
        cctv1.storageType = "SD Card";
        cctv1.rating = 4;
        cctv1.frameRate = 30.0;
        cctv1.isCertified = true;
        cctv1.countryOfOrigin = "China";
        cctv1.manufacturingYear = 2025;
        cctv1.cableLength = 10.0;
        cctv1.supportsMobileView = true;
        cctv1.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv1.cameraBrand);
        System.out.println("The cameraId is : " + cctv1.cameraId);
        System.out.println("The cameraPrice is : " + cctv1.cameraPrice);
        System.out.println("The isAvailable is : " + cctv1.isAvailable);
        System.out.println("The cameraType is : " + cctv1.cameraType);
        System.out.println("The resolutionMP is : " + cctv1.resolutionMP);
        System.out.println("The weight is : " + cctv1.weight);
        System.out.println("The isNightVision is : " + cctv1.isNightVision);
        System.out.println("The lensType is : " + cctv1.lensType);
        System.out.println("The warrantyYears is : " + cctv1.warrantyYears);
        System.out.println("The viewAngle is : " + cctv1.viewAngle);
        System.out.println("The isWireless is : " + cctv1.isWireless);
        System.out.println("The color is : " + cctv1.color);
        System.out.println("The stockQuantity is : " + cctv1.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv1.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv1.isWaterproof);
        System.out.println("The storageType is : " + cctv1.storageType);
        System.out.println("The rating is : " + cctv1.rating);
        System.out.println("The frameRate is : " + cctv1.frameRate);
        System.out.println("The isCertified is : " + cctv1.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv1.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv1.manufacturingYear);
        System.out.println("The cableLength is : " + cctv1.cableLength);
        System.out.println("The supportsMobileView is : " + cctv1.supportsMobileView);
        System.out.println("The certificationType is : " + cctv1.certificationType);


        Cctv cctv2 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv2.cameraBrand);
        System.out.println("The cameraId is : " + cctv2.cameraId);
        System.out.println("The cameraPrice is : " + cctv2.cameraPrice);
        System.out.println("The isAvailable is : " + cctv2.isAvailable);
        System.out.println("The cameraType is : " + cctv2.cameraType);
        System.out.println("The resolutionMP is : " + cctv2.resolutionMP);
        System.out.println("The weight is : " + cctv2.weight);
        System.out.println("The isNightVision is : " + cctv2.isNightVision);
        System.out.println("The lensType is : " + cctv2.lensType);
        System.out.println("The warrantyYears is : " + cctv2.warrantyYears);
        System.out.println("The viewAngle is : " + cctv2.viewAngle);
        System.out.println("The isWireless is : " + cctv2.isWireless);
        System.out.println("The color is : " + cctv2.color);
        System.out.println("The stockQuantity is : " + cctv2.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv2.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv2.isWaterproof);
        System.out.println("The storageType is : " + cctv2.storageType);
        System.out.println("The rating is : " + cctv2.rating);
        System.out.println("The frameRate is : " + cctv2.frameRate);
        System.out.println("The isCertified is : " + cctv2.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv2.manufacturingYear);
        System.out.println("The cableLength is : " + cctv2.cableLength);
        System.out.println("The supportsMobileView is : " + cctv2.supportsMobileView);
        System.out.println("The certificationType is : " + cctv2.certificationType);

        cctv2.cameraBrand = "Hikvision";
        cctv2.cameraId = 2;
        cctv2.cameraPrice = 2500.50;
        cctv2.isAvailable = true;
        cctv2.cameraType = "Dome";
        cctv2.resolutionMP = 5;
        cctv2.weight = 0.75;
        cctv2.isNightVision = true;
        cctv2.lensType = "Wide";
        cctv2.warrantyYears = 2;
        cctv2.viewAngle = 120.0;
        cctv2.isWireless = false;
        cctv2.color = "White";
        cctv2.stockQuantity = 30;
        cctv2.powerConsumption = 12.5;
        cctv2.isWaterproof = true;
        cctv2.storageType = "SD Card";
        cctv2.rating = 4;
        cctv2.frameRate = 30.0;
        cctv2.isCertified = true;
        cctv2.countryOfOrigin = "China";
        cctv2.manufacturingYear = 2025;
        cctv2.cableLength = 10.0;
        cctv2.supportsMobileView = true;
        cctv2.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv2.cameraBrand);
        System.out.println("The cameraId is : " + cctv2.cameraId);
        System.out.println("The cameraPrice is : " + cctv2.cameraPrice);
        System.out.println("The isAvailable is : " + cctv2.isAvailable);
        System.out.println("The cameraType is : " + cctv2.cameraType);
        System.out.println("The resolutionMP is : " + cctv2.resolutionMP);
        System.out.println("The weight is : " + cctv2.weight);
        System.out.println("The isNightVision is : " + cctv2.isNightVision);
        System.out.println("The lensType is : " + cctv2.lensType);
        System.out.println("The warrantyYears is : " + cctv2.warrantyYears);
        System.out.println("The viewAngle is : " + cctv2.viewAngle);
        System.out.println("The isWireless is : " + cctv2.isWireless);
        System.out.println("The color is : " + cctv2.color);
        System.out.println("The stockQuantity is : " + cctv2.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv2.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv2.isWaterproof);
        System.out.println("The storageType is : " + cctv2.storageType);
        System.out.println("The rating is : " + cctv2.rating);
        System.out.println("The frameRate is : " + cctv2.frameRate);
        System.out.println("The isCertified is : " + cctv2.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv2.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv2.manufacturingYear);
        System.out.println("The cableLength is : " + cctv2.cableLength);
        System.out.println("The supportsMobileView is : " + cctv2.supportsMobileView);
        System.out.println("The certificationType is : " + cctv2.certificationType);


        Cctv cctv3 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv3.cameraBrand);
        System.out.println("The cameraId is : " + cctv3.cameraId);
        System.out.println("The cameraPrice is : " + cctv3.cameraPrice);
        System.out.println("The isAvailable is : " + cctv3.isAvailable);
        System.out.println("The cameraType is : " + cctv3.cameraType);
        System.out.println("The resolutionMP is : " + cctv3.resolutionMP);
        System.out.println("The weight is : " + cctv3.weight);
        System.out.println("The isNightVision is : " + cctv3.isNightVision);
        System.out.println("The lensType is : " + cctv3.lensType);
        System.out.println("The warrantyYears is : " + cctv3.warrantyYears);
        System.out.println("The viewAngle is : " + cctv3.viewAngle);
        System.out.println("The isWireless is : " + cctv3.isWireless);
        System.out.println("The color is : " + cctv3.color);
        System.out.println("The stockQuantity is : " + cctv3.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv3.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv3.isWaterproof);
        System.out.println("The storageType is : " + cctv3.storageType);
        System.out.println("The rating is : " + cctv3.rating);
        System.out.println("The frameRate is : " + cctv3.frameRate);
        System.out.println("The isCertified is : " + cctv3.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv3.manufacturingYear);
        System.out.println("The cableLength is : " + cctv3.cableLength);
        System.out.println("The supportsMobileView is : " + cctv3.supportsMobileView);
        System.out.println("The certificationType is : " + cctv3.certificationType);

        cctv3.cameraBrand = "Hikvision";
        cctv3.cameraId = 3;
        cctv3.cameraPrice = 3500.50;
        cctv3.isAvailable = true;
        cctv3.cameraType = "Dome";
        cctv3.resolutionMP = 5;
        cctv3.weight = 0.75;
        cctv3.isNightVision = true;
        cctv3.lensType = "Wide";
        cctv3.warrantyYears = 2;
        cctv3.viewAngle = 120.0;
        cctv3.isWireless = false;
        cctv3.color = "White";
        cctv3.stockQuantity = 30;
        cctv3.powerConsumption = 12.5;
        cctv3.isWaterproof = true;
        cctv3.storageType = "SD Card";
        cctv3.rating = 4;
        cctv3.frameRate = 30.0;
        cctv3.isCertified = true;
        cctv3.countryOfOrigin = "China";
        cctv3.manufacturingYear = 2025;
        cctv3.cableLength = 10.0;
        cctv3.supportsMobileView = true;
        cctv3.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv3.cameraBrand);
        System.out.println("The cameraId is : " + cctv3.cameraId);
        System.out.println("The cameraPrice is : " + cctv3.cameraPrice);
        System.out.println("The isAvailable is : " + cctv3.isAvailable);
        System.out.println("The cameraType is : " + cctv3.cameraType);
        System.out.println("The resolutionMP is : " + cctv3.resolutionMP);
        System.out.println("The weight is : " + cctv3.weight);
        System.out.println("The isNightVision is : " + cctv3.isNightVision);
        System.out.println("The lensType is : " + cctv3.lensType);
        System.out.println("The warrantyYears is : " + cctv3.warrantyYears);
        System.out.println("The viewAngle is : " + cctv3.viewAngle);
        System.out.println("The isWireless is : " + cctv3.isWireless);
        System.out.println("The color is : " + cctv3.color);
        System.out.println("The stockQuantity is : " + cctv3.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv3.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv3.isWaterproof);
        System.out.println("The storageType is : " + cctv3.storageType);
        System.out.println("The rating is : " + cctv3.rating);
        System.out.println("The frameRate is : " + cctv3.frameRate);
        System.out.println("The isCertified is : " + cctv3.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv3.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv3.manufacturingYear);
        System.out.println("The cableLength is : " + cctv3.cableLength);
        System.out.println("The supportsMobileView is : " + cctv3.supportsMobileView);
        System.out.println("The certificationType is : " + cctv3.certificationType);


        Cctv cctv4 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv4.cameraBrand);
        System.out.println("The cameraId is : " + cctv4.cameraId);
        System.out.println("The cameraPrice is : " + cctv4.cameraPrice);
        System.out.println("The isAvailable is : " + cctv4.isAvailable);
        System.out.println("The cameraType is : " + cctv4.cameraType);
        System.out.println("The resolutionMP is : " + cctv4.resolutionMP);
        System.out.println("The weight is : " + cctv4.weight);
        System.out.println("The isNightVision is : " + cctv4.isNightVision);
        System.out.println("The lensType is : " + cctv4.lensType);
        System.out.println("The warrantyYears is : " + cctv4.warrantyYears);
        System.out.println("The viewAngle is : " + cctv4.viewAngle);
        System.out.println("The isWireless is : " + cctv4.isWireless);
        System.out.println("The color is : " + cctv4.color);
        System.out.println("The stockQuantity is : " + cctv4.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv4.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv4.isWaterproof);
        System.out.println("The storageType is : " + cctv4.storageType);
        System.out.println("The rating is : " + cctv4.rating);
        System.out.println("The frameRate is : " + cctv4.frameRate);
        System.out.println("The isCertified is : " + cctv4.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv4.manufacturingYear);
        System.out.println("The cableLength is : " + cctv4.cableLength);
        System.out.println("The supportsMobileView is : " + cctv4.supportsMobileView);
        System.out.println("The certificationType is : " + cctv4.certificationType);

        cctv4.cameraBrand = "Hikvision";
        cctv4.cameraId = 4;
        cctv4.cameraPrice = 4500.50;
        cctv4.isAvailable = true;
        cctv4.cameraType = "Dome";
        cctv4.resolutionMP = 5;
        cctv4.weight = 0.75;
        cctv4.isNightVision = true;
        cctv4.lensType = "Wide";
        cctv4.warrantyYears = 2;
        cctv4.viewAngle = 120.0;
        cctv4.isWireless = false;
        cctv4.color = "White";
        cctv4.stockQuantity = 30;
        cctv4.powerConsumption = 12.5;
        cctv4.isWaterproof = true;
        cctv4.storageType = "SD Card";
        cctv4.rating = 4;
        cctv4.frameRate = 30.0;
        cctv4.isCertified = true;
        cctv4.countryOfOrigin = "China";
        cctv4.manufacturingYear = 2025;
        cctv4.cableLength = 10.0;
        cctv4.supportsMobileView = true;
        cctv4.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv4.cameraBrand);
        System.out.println("The cameraId is : " + cctv4.cameraId);
        System.out.println("The cameraPrice is : " + cctv4.cameraPrice);
        System.out.println("The isAvailable is : " + cctv4.isAvailable);
        System.out.println("The cameraType is : " + cctv4.cameraType);
        System.out.println("The resolutionMP is : " + cctv4.resolutionMP);
        System.out.println("The weight is : " + cctv4.weight);
        System.out.println("The isNightVision is : " + cctv4.isNightVision);
        System.out.println("The lensType is : " + cctv4.lensType);
        System.out.println("The warrantyYears is : " + cctv4.warrantyYears);
        System.out.println("The viewAngle is : " + cctv4.viewAngle);
        System.out.println("The isWireless is : " + cctv4.isWireless);
        System.out.println("The color is : " + cctv4.color);
        System.out.println("The stockQuantity is : " + cctv4.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv4.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv4.isWaterproof);
        System.out.println("The storageType is : " + cctv4.storageType);
        System.out.println("The rating is : " + cctv4.rating);
        System.out.println("The frameRate is : " + cctv4.frameRate);
        System.out.println("The isCertified is : " + cctv4.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv4.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv4.manufacturingYear);
        System.out.println("The cableLength is : " + cctv4.cableLength);
        System.out.println("The supportsMobileView is : " + cctv4.supportsMobileView);
        System.out.println("The certificationType is : " + cctv4.certificationType);


        Cctv cctv5 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv5.cameraBrand);
        System.out.println("The cameraId is : " + cctv5.cameraId);
        System.out.println("The cameraPrice is : " + cctv5.cameraPrice);
        System.out.println("The isAvailable is : " + cctv5.isAvailable);
        System.out.println("The cameraType is : " + cctv5.cameraType);
        System.out.println("The resolutionMP is : " + cctv5.resolutionMP);
        System.out.println("The weight is : " + cctv5.weight);
        System.out.println("The isNightVision is : " + cctv5.isNightVision);
        System.out.println("The lensType is : " + cctv5.lensType);
        System.out.println("The warrantyYears is : " + cctv5.warrantyYears);
        System.out.println("The viewAngle is : " + cctv5.viewAngle);
        System.out.println("The isWireless is : " + cctv5.isWireless);
        System.out.println("The color is : " + cctv5.color);
        System.out.println("The stockQuantity is : " + cctv5.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv5.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv5.isWaterproof);
        System.out.println("The storageType is : " + cctv5.storageType);
        System.out.println("The rating is : " + cctv5.rating);
        System.out.println("The frameRate is : " + cctv5.frameRate);
        System.out.println("The isCertified is : " + cctv5.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv5.manufacturingYear);
        System.out.println("The cableLength is : " + cctv5.cableLength);
        System.out.println("The supportsMobileView is : " + cctv5.supportsMobileView);
        System.out.println("The certificationType is : " + cctv5.certificationType);

        cctv5.cameraBrand = "Hikvision";
        cctv5.cameraId = 5;
        cctv5.cameraPrice = 5500.50;
        cctv5.isAvailable = true;
        cctv5.cameraType = "Dome";
        cctv5.resolutionMP = 5;
        cctv5.weight = 0.75;
        cctv5.isNightVision = true;
        cctv5.lensType = "Wide";
        cctv5.warrantyYears = 2;
        cctv5.viewAngle = 120.0;
        cctv5.isWireless = false;
        cctv5.color = "White";
        cctv5.stockQuantity = 30;
        cctv5.powerConsumption = 12.5;
        cctv5.isWaterproof = true;
        cctv5.storageType = "SD Card";
        cctv5.rating = 4;
        cctv5.frameRate = 30.0;
        cctv5.isCertified = true;
        cctv5.countryOfOrigin = "China";
        cctv5.manufacturingYear = 2025;
        cctv5.cableLength = 10.0;
        cctv5.supportsMobileView = true;
        cctv5.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv5.cameraBrand);
        System.out.println("The cameraId is : " + cctv5.cameraId);
        System.out.println("The cameraPrice is : " + cctv5.cameraPrice);
        System.out.println("The isAvailable is : " + cctv5.isAvailable);
        System.out.println("The cameraType is : " + cctv5.cameraType);
        System.out.println("The resolutionMP is : " + cctv5.resolutionMP);
        System.out.println("The weight is : " + cctv5.weight);
        System.out.println("The isNightVision is : " + cctv5.isNightVision);
        System.out.println("The lensType is : " + cctv5.lensType);
        System.out.println("The warrantyYears is : " + cctv5.warrantyYears);
        System.out.println("The viewAngle is : " + cctv5.viewAngle);
        System.out.println("The isWireless is : " + cctv5.isWireless);
        System.out.println("The color is : " + cctv5.color);
        System.out.println("The stockQuantity is : " + cctv5.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv5.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv5.isWaterproof);
        System.out.println("The storageType is : " + cctv5.storageType);
        System.out.println("The rating is : " + cctv5.rating);
        System.out.println("The frameRate is : " + cctv5.frameRate);
        System.out.println("The isCertified is : " + cctv5.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv5.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv5.manufacturingYear);
        System.out.println("The cableLength is : " + cctv5.cableLength);
        System.out.println("The supportsMobileView is : " + cctv5.supportsMobileView);
        System.out.println("The certificationType is : " + cctv5.certificationType);


        Cctv cctv6 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv6.cameraBrand);
        System.out.println("The cameraId is : " + cctv6.cameraId);
        System.out.println("The cameraPrice is : " + cctv6.cameraPrice);
        System.out.println("The isAvailable is : " + cctv6.isAvailable);
        System.out.println("The cameraType is : " + cctv6.cameraType);
        System.out.println("The resolutionMP is : " + cctv6.resolutionMP);
        System.out.println("The weight is : " + cctv6.weight);
        System.out.println("The isNightVision is : " + cctv6.isNightVision);
        System.out.println("The lensType is : " + cctv6.lensType);
        System.out.println("The warrantyYears is : " + cctv6.warrantyYears);
        System.out.println("The viewAngle is : " + cctv6.viewAngle);
        System.out.println("The isWireless is : " + cctv6.isWireless);
        System.out.println("The color is : " + cctv6.color);
        System.out.println("The stockQuantity is : " + cctv6.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv6.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv6.isWaterproof);
        System.out.println("The storageType is : " + cctv6.storageType);
        System.out.println("The rating is : " + cctv6.rating);
        System.out.println("The frameRate is : " + cctv6.frameRate);
        System.out.println("The isCertified is : " + cctv6.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv6.manufacturingYear);
        System.out.println("The cableLength is : " + cctv6.cableLength);
        System.out.println("The supportsMobileView is : " + cctv6.supportsMobileView);
        System.out.println("The certificationType is : " + cctv6.certificationType);

        cctv6.cameraBrand = "Hikvision";
        cctv6.cameraId = 6;
        cctv6.cameraPrice = 6500.50;
        cctv6.isAvailable = true;
        cctv6.cameraType = "Dome";
        cctv6.resolutionMP = 5;
        cctv6.weight = 0.75;
        cctv6.isNightVision = true;
        cctv6.lensType = "Wide";
        cctv6.warrantyYears = 2;
        cctv6.viewAngle = 120.0;
        cctv6.isWireless = false;
        cctv6.color = "White";
        cctv6.stockQuantity = 30;
        cctv6.powerConsumption = 12.5;
        cctv6.isWaterproof = true;
        cctv6.storageType = "SD Card";
        cctv6.rating = 4;
        cctv6.frameRate = 30.0;
        cctv6.isCertified = true;
        cctv6.countryOfOrigin = "China";
        cctv6.manufacturingYear = 2025;
        cctv6.cableLength = 10.0;
        cctv6.supportsMobileView = true;
        cctv6.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv6.cameraBrand);
        System.out.println("The cameraId is : " + cctv6.cameraId);
        System.out.println("The cameraPrice is : " + cctv6.cameraPrice);
        System.out.println("The isAvailable is : " + cctv6.isAvailable);
        System.out.println("The cameraType is : " + cctv6.cameraType);
        System.out.println("The resolutionMP is : " + cctv6.resolutionMP);
        System.out.println("The weight is : " + cctv6.weight);
        System.out.println("The isNightVision is : " + cctv6.isNightVision);
        System.out.println("The lensType is : " + cctv6.lensType);
        System.out.println("The warrantyYears is : " + cctv6.warrantyYears);
        System.out.println("The viewAngle is : " + cctv6.viewAngle);
        System.out.println("The isWireless is : " + cctv6.isWireless);
        System.out.println("The color is : " + cctv6.color);
        System.out.println("The stockQuantity is : " + cctv6.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv6.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv6.isWaterproof);
        System.out.println("The storageType is : " + cctv6.storageType);
        System.out.println("The rating is : " + cctv6.rating);
        System.out.println("The frameRate is : " + cctv6.frameRate);
        System.out.println("The isCertified is : " + cctv6.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv6.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv6.manufacturingYear);
        System.out.println("The cableLength is : " + cctv6.cableLength);
        System.out.println("The supportsMobileView is : " + cctv6.supportsMobileView);
        System.out.println("The certificationType is : " + cctv6.certificationType);


        Cctv cctv7 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv7.cameraBrand);
        System.out.println("The cameraId is : " + cctv7.cameraId);
        System.out.println("The cameraPrice is : " + cctv7.cameraPrice);
        System.out.println("The isAvailable is : " + cctv7.isAvailable);
        System.out.println("The cameraType is : " + cctv7.cameraType);
        System.out.println("The resolutionMP is : " + cctv7.resolutionMP);
        System.out.println("The weight is : " + cctv7.weight);
        System.out.println("The isNightVision is : " + cctv7.isNightVision);
        System.out.println("The lensType is : " + cctv7.lensType);
        System.out.println("The warrantyYears is : " + cctv7.warrantyYears);
        System.out.println("The viewAngle is : " + cctv7.viewAngle);
        System.out.println("The isWireless is : " + cctv7.isWireless);
        System.out.println("The color is : " + cctv7.color);
        System.out.println("The stockQuantity is : " + cctv7.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv7.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv7.isWaterproof);
        System.out.println("The storageType is : " + cctv7.storageType);
        System.out.println("The rating is : " + cctv7.rating);
        System.out.println("The frameRate is : " + cctv7.frameRate);
        System.out.println("The isCertified is : " + cctv7.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv7.manufacturingYear);
        System.out.println("The cableLength is : " + cctv7.cableLength);
        System.out.println("The supportsMobileView is : " + cctv7.supportsMobileView);
        System.out.println("The certificationType is : " + cctv7.certificationType);

        cctv7.cameraBrand = "Hikvision";
        cctv7.cameraId = 7;
        cctv7.cameraPrice = 7500.50;
        cctv7.isAvailable = true;
        cctv7.cameraType = "Dome";
        cctv7.resolutionMP = 5;
        cctv7.weight = 0.75;
        cctv7.isNightVision = true;
        cctv7.lensType = "Wide";
        cctv7.warrantyYears = 2;
        cctv7.viewAngle = 120.0;
        cctv7.isWireless = false;
        cctv7.color = "White";
        cctv7.stockQuantity = 30;
        cctv7.powerConsumption = 12.5;
        cctv7.isWaterproof = true;
        cctv7.storageType = "SD Card";
        cctv7.rating = 4;
        cctv7.frameRate = 30.0;
        cctv7.isCertified = true;
        cctv7.countryOfOrigin = "China";
        cctv7.manufacturingYear = 2025;
        cctv7.cableLength = 10.0;
        cctv7.supportsMobileView = true;
        cctv7.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv7.cameraBrand);
        System.out.println("The cameraId is : " + cctv7.cameraId);
        System.out.println("The cameraPrice is : " + cctv7.cameraPrice);
        System.out.println("The isAvailable is : " + cctv7.isAvailable);
        System.out.println("The cameraType is : " + cctv7.cameraType);
        System.out.println("The resolutionMP is : " + cctv7.resolutionMP);
        System.out.println("The weight is : " + cctv7.weight);
        System.out.println("The isNightVision is : " + cctv7.isNightVision);
        System.out.println("The lensType is : " + cctv7.lensType);
        System.out.println("The warrantyYears is : " + cctv7.warrantyYears);
        System.out.println("The viewAngle is : " + cctv7.viewAngle);
        System.out.println("The isWireless is : " + cctv7.isWireless);
        System.out.println("The color is : " + cctv7.color);
        System.out.println("The stockQuantity is : " + cctv7.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv7.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv7.isWaterproof);
        System.out.println("The storageType is : " + cctv7.storageType);
        System.out.println("The rating is : " + cctv7.rating);
        System.out.println("The frameRate is : " + cctv7.frameRate);
        System.out.println("The isCertified is : " + cctv7.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv7.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv7.manufacturingYear);
        System.out.println("The cableLength is : " + cctv7.cableLength);
        System.out.println("The supportsMobileView is : " + cctv7.supportsMobileView);
        System.out.println("The certificationType is : " + cctv7.certificationType);


        Cctv cctv8 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv8.cameraBrand);
        System.out.println("The cameraId is : " + cctv8.cameraId);
        System.out.println("The cameraPrice is : " + cctv8.cameraPrice);
        System.out.println("The isAvailable is : " + cctv8.isAvailable);
        System.out.println("The cameraType is : " + cctv8.cameraType);
        System.out.println("The resolutionMP is : " + cctv8.resolutionMP);
        System.out.println("The weight is : " + cctv8.weight);
        System.out.println("The isNightVision is : " + cctv8.isNightVision);
        System.out.println("The lensType is : " + cctv8.lensType);
        System.out.println("The warrantyYears is : " + cctv8.warrantyYears);
        System.out.println("The viewAngle is : " + cctv8.viewAngle);
        System.out.println("The isWireless is : " + cctv8.isWireless);
        System.out.println("The color is : " + cctv8.color);
        System.out.println("The stockQuantity is : " + cctv8.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv8.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv8.isWaterproof);
        System.out.println("The storageType is : " + cctv8.storageType);
        System.out.println("The rating is : " + cctv8.rating);
        System.out.println("The frameRate is : " + cctv8.frameRate);
        System.out.println("The isCertified is : " + cctv8.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv8.manufacturingYear);
        System.out.println("The cableLength is : " + cctv8.cableLength);
        System.out.println("The supportsMobileView is : " + cctv8.supportsMobileView);
        System.out.println("The certificationType is : " + cctv8.certificationType);

        cctv8.cameraBrand = "Hikvision";
        cctv8.cameraId = 8;
        cctv8.cameraPrice = 8500.50;
        cctv8.isAvailable = true;
        cctv8.cameraType = "Dome";
        cctv8.resolutionMP = 5;
        cctv8.weight = 0.75;
        cctv8.isNightVision = true;
        cctv8.lensType = "Wide";
        cctv8.warrantyYears = 2;
        cctv8.viewAngle = 120.0;
        cctv8.isWireless = false;
        cctv8.color = "White";
        cctv8.stockQuantity = 30;
        cctv8.powerConsumption = 12.5;
        cctv8.isWaterproof = true;
        cctv8.storageType = "SD Card";
        cctv8.rating = 4;
        cctv8.frameRate = 30.0;
        cctv8.isCertified = true;
        cctv8.countryOfOrigin = "China";
        cctv8.manufacturingYear = 2025;
        cctv8.cableLength = 10.0;
        cctv8.supportsMobileView = true;
        cctv8.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv8.cameraBrand);
        System.out.println("The cameraId is : " + cctv8.cameraId);
        System.out.println("The cameraPrice is : " + cctv8.cameraPrice);
        System.out.println("The isAvailable is : " + cctv8.isAvailable);
        System.out.println("The cameraType is : " + cctv8.cameraType);
        System.out.println("The resolutionMP is : " + cctv8.resolutionMP);
        System.out.println("The weight is : " + cctv8.weight);
        System.out.println("The isNightVision is : " + cctv8.isNightVision);
        System.out.println("The lensType is : " + cctv8.lensType);
        System.out.println("The warrantyYears is : " + cctv8.warrantyYears);
        System.out.println("The viewAngle is : " + cctv8.viewAngle);
        System.out.println("The isWireless is : " + cctv8.isWireless);
        System.out.println("The color is : " + cctv8.color);
        System.out.println("The stockQuantity is : " + cctv8.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv8.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv8.isWaterproof);
        System.out.println("The storageType is : " + cctv8.storageType);
        System.out.println("The rating is : " + cctv8.rating);
        System.out.println("The frameRate is : " + cctv8.frameRate);
        System.out.println("The isCertified is : " + cctv8.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv8.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv8.manufacturingYear);
        System.out.println("The cableLength is : " + cctv8.cableLength);
        System.out.println("The supportsMobileView is : " + cctv8.supportsMobileView);
        System.out.println("The certificationType is : " + cctv8.certificationType);


        Cctv cctv9 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv9.cameraBrand);
        System.out.println("The cameraId is : " + cctv9.cameraId);
        System.out.println("The cameraPrice is : " + cctv9.cameraPrice);
        System.out.println("The isAvailable is : " + cctv9.isAvailable);
        System.out.println("The cameraType is : " + cctv9.cameraType);
        System.out.println("The resolutionMP is : " + cctv9.resolutionMP);
        System.out.println("The weight is : " + cctv9.weight);
        System.out.println("The isNightVision is : " + cctv9.isNightVision);
        System.out.println("The lensType is : " + cctv9.lensType);
        System.out.println("The warrantyYears is : " + cctv9.warrantyYears);
        System.out.println("The viewAngle is : " + cctv9.viewAngle);
        System.out.println("The isWireless is : " + cctv9.isWireless);
        System.out.println("The color is : " + cctv9.color);
        System.out.println("The stockQuantity is : " + cctv9.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv9.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv9.isWaterproof);
        System.out.println("The storageType is : " + cctv9.storageType);
        System.out.println("The rating is : " + cctv9.rating);
        System.out.println("The frameRate is : " + cctv9.frameRate);
        System.out.println("The isCertified is : " + cctv9.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv9.manufacturingYear);
        System.out.println("The cableLength is : " + cctv9.cableLength);
        System.out.println("The supportsMobileView is : " + cctv9.supportsMobileView);
        System.out.println("The certificationType is : " + cctv9.certificationType);

        cctv9.cameraBrand = "Hikvision";
        cctv9.cameraId = 9;
        cctv9.cameraPrice = 9500.50;
        cctv9.isAvailable = true;
        cctv9.cameraType = "Dome";
        cctv9.resolutionMP = 5;
        cctv9.weight = 0.75;
        cctv9.isNightVision = true;
        cctv9.lensType = "Wide";
        cctv9.warrantyYears = 2;
        cctv9.viewAngle = 120.0;
        cctv9.isWireless = false;
        cctv9.color = "White";
        cctv9.stockQuantity = 30;
        cctv9.powerConsumption = 12.5;
        cctv9.isWaterproof = true;
        cctv9.storageType = "SD Card";
        cctv9.rating = 4;
        cctv9.frameRate = 30.0;
        cctv9.isCertified = true;
        cctv9.countryOfOrigin = "China";
        cctv9.manufacturingYear = 2025;
        cctv9.cableLength = 10.0;
        cctv9.supportsMobileView = true;
        cctv9.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv9.cameraBrand);
        System.out.println("The cameraId is : " + cctv9.cameraId);
        System.out.println("The cameraPrice is : " + cctv9.cameraPrice);
        System.out.println("The isAvailable is : " + cctv9.isAvailable);
        System.out.println("The cameraType is : " + cctv9.cameraType);
        System.out.println("The resolutionMP is : " + cctv9.resolutionMP);
        System.out.println("The weight is : " + cctv9.weight);
        System.out.println("The isNightVision is : " + cctv9.isNightVision);
        System.out.println("The lensType is : " + cctv9.lensType);
        System.out.println("The warrantyYears is : " + cctv9.warrantyYears);
        System.out.println("The viewAngle is : " + cctv9.viewAngle);
        System.out.println("The isWireless is : " + cctv9.isWireless);
        System.out.println("The color is : " + cctv9.color);
        System.out.println("The stockQuantity is : " + cctv9.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv9.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv9.isWaterproof);
        System.out.println("The storageType is : " + cctv9.storageType);
        System.out.println("The rating is : " + cctv9.rating);
        System.out.println("The frameRate is : " + cctv9.frameRate);
        System.out.println("The isCertified is : " + cctv9.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv9.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv9.manufacturingYear);
        System.out.println("The cableLength is : " + cctv9.cableLength);
        System.out.println("The supportsMobileView is : " + cctv9.supportsMobileView);
        System.out.println("The certificationType is : " + cctv9.certificationType);


        Cctv cctv10 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv10.cameraBrand);
        System.out.println("The cameraId is : " + cctv10.cameraId);
        System.out.println("The cameraPrice is : " + cctv10.cameraPrice);
        System.out.println("The isAvailable is : " + cctv10.isAvailable);
        System.out.println("The cameraType is : " + cctv10.cameraType);
        System.out.println("The resolutionMP is : " + cctv10.resolutionMP);
        System.out.println("The weight is : " + cctv10.weight);
        System.out.println("The isNightVision is : " + cctv10.isNightVision);
        System.out.println("The lensType is : " + cctv10.lensType);
        System.out.println("The warrantyYears is : " + cctv10.warrantyYears);
        System.out.println("The viewAngle is : " + cctv10.viewAngle);
        System.out.println("The isWireless is : " + cctv10.isWireless);
        System.out.println("The color is : " + cctv10.color);
        System.out.println("The stockQuantity is : " + cctv10.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv10.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv10.isWaterproof);
        System.out.println("The storageType is : " + cctv10.storageType);
        System.out.println("The rating is : " + cctv10.rating);
        System.out.println("The frameRate is : " + cctv10.frameRate);
        System.out.println("The isCertified is : " + cctv10.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv10.manufacturingYear);
        System.out.println("The cableLength is : " + cctv10.cableLength);
        System.out.println("The supportsMobileView is : " + cctv10.supportsMobileView);
        System.out.println("The certificationType is : " + cctv10.certificationType);

        cctv10.cameraBrand = "Hikvision";
        cctv10.cameraId = 10;
        cctv10.cameraPrice = 10500.50;
        cctv10.isAvailable = true;
        cctv10.cameraType = "Dome";
        cctv10.resolutionMP = 5;
        cctv10.weight = 0.75;
        cctv10.isNightVision = true;
        cctv10.lensType = "Wide";
        cctv10.warrantyYears = 2;
        cctv10.viewAngle = 120.0;
        cctv10.isWireless = false;
        cctv10.color = "White";
        cctv10.stockQuantity = 30;
        cctv10.powerConsumption = 12.5;
        cctv10.isWaterproof = true;
        cctv10.storageType = "SD Card";
        cctv10.rating = 4;
        cctv10.frameRate = 30.0;
        cctv10.isCertified = true;
        cctv10.countryOfOrigin = "China";
        cctv10.manufacturingYear = 2025;
        cctv10.cableLength = 10.0;
        cctv10.supportsMobileView = true;
        cctv10.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv10.cameraBrand);
        System.out.println("The cameraId is : " + cctv10.cameraId);
        System.out.println("The cameraPrice is : " + cctv10.cameraPrice);
        System.out.println("The isAvailable is : " + cctv10.isAvailable);
        System.out.println("The cameraType is : " + cctv10.cameraType);
        System.out.println("The resolutionMP is : " + cctv10.resolutionMP);
        System.out.println("The weight is : " + cctv10.weight);
        System.out.println("The isNightVision is : " + cctv10.isNightVision);
        System.out.println("The lensType is : " + cctv10.lensType);
        System.out.println("The warrantyYears is : " + cctv10.warrantyYears);
        System.out.println("The viewAngle is : " + cctv10.viewAngle);
        System.out.println("The isWireless is : " + cctv10.isWireless);
        System.out.println("The color is : " + cctv10.color);
        System.out.println("The stockQuantity is : " + cctv10.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv10.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv10.isWaterproof);
        System.out.println("The storageType is : " + cctv10.storageType);
        System.out.println("The rating is : " + cctv10.rating);
        System.out.println("The frameRate is : " + cctv10.frameRate);
        System.out.println("The isCertified is : " + cctv10.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv10.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv10.manufacturingYear);
        System.out.println("The cableLength is : " + cctv10.cableLength);
        System.out.println("The supportsMobileView is : " + cctv10.supportsMobileView);
        System.out.println("The certificationType is : " + cctv10.certificationType);


        Cctv cctv11 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv11.cameraBrand);
        System.out.println("The cameraId is : " + cctv11.cameraId);
        System.out.println("The cameraPrice is : " + cctv11.cameraPrice);
        System.out.println("The isAvailable is : " + cctv11.isAvailable);
        System.out.println("The cameraType is : " + cctv11.cameraType);
        System.out.println("The resolutionMP is : " + cctv11.resolutionMP);
        System.out.println("The weight is : " + cctv11.weight);
        System.out.println("The isNightVision is : " + cctv11.isNightVision);
        System.out.println("The lensType is : " + cctv11.lensType);
        System.out.println("The warrantyYears is : " + cctv11.warrantyYears);
        System.out.println("The viewAngle is : " + cctv11.viewAngle);
        System.out.println("The isWireless is : " + cctv11.isWireless);
        System.out.println("The color is : " + cctv11.color);
        System.out.println("The stockQuantity is : " + cctv11.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv11.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv11.isWaterproof);
        System.out.println("The storageType is : " + cctv11.storageType);
        System.out.println("The rating is : " + cctv11.rating);
        System.out.println("The frameRate is : " + cctv11.frameRate);
        System.out.println("The isCertified is : " + cctv11.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv11.manufacturingYear);
        System.out.println("The cableLength is : " + cctv11.cableLength);
        System.out.println("The supportsMobileView is : " + cctv11.supportsMobileView);
        System.out.println("The certificationType is : " + cctv11.certificationType);

        cctv11.cameraBrand = "Hikvision";
        cctv11.cameraId = 11;
        cctv11.cameraPrice = 11500.50;
        cctv11.isAvailable = true;
        cctv11.cameraType = "Dome";
        cctv11.resolutionMP = 5;
        cctv11.weight = 0.75;
        cctv11.isNightVision = true;
        cctv11.lensType = "Wide";
        cctv11.warrantyYears = 2;
        cctv11.viewAngle = 120.0;
        cctv11.isWireless = false;
        cctv11.color = "White";
        cctv11.stockQuantity = 30;
        cctv11.powerConsumption = 12.5;
        cctv11.isWaterproof = true;
        cctv11.storageType = "SD Card";
        cctv11.rating = 4;
        cctv11.frameRate = 30.0;
        cctv11.isCertified = true;
        cctv11.countryOfOrigin = "China";
        cctv11.manufacturingYear = 2025;
        cctv11.cableLength = 10.0;
        cctv11.supportsMobileView = true;
        cctv11.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv11.cameraBrand);
        System.out.println("The cameraId is : " + cctv11.cameraId);
        System.out.println("The cameraPrice is : " + cctv11.cameraPrice);
        System.out.println("The isAvailable is : " + cctv11.isAvailable);
        System.out.println("The cameraType is : " + cctv11.cameraType);
        System.out.println("The resolutionMP is : " + cctv11.resolutionMP);
        System.out.println("The weight is : " + cctv11.weight);
        System.out.println("The isNightVision is : " + cctv11.isNightVision);
        System.out.println("The lensType is : " + cctv11.lensType);
        System.out.println("The warrantyYears is : " + cctv11.warrantyYears);
        System.out.println("The viewAngle is : " + cctv11.viewAngle);
        System.out.println("The isWireless is : " + cctv11.isWireless);
        System.out.println("The color is : " + cctv11.color);
        System.out.println("The stockQuantity is : " + cctv11.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv11.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv11.isWaterproof);
        System.out.println("The storageType is : " + cctv11.storageType);
        System.out.println("The rating is : " + cctv11.rating);
        System.out.println("The frameRate is : " + cctv11.frameRate);
        System.out.println("The isCertified is : " + cctv11.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv11.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv11.manufacturingYear);
        System.out.println("The cableLength is : " + cctv11.cableLength);
        System.out.println("The supportsMobileView is : " + cctv11.supportsMobileView);
        System.out.println("The certificationType is : " + cctv11.certificationType);


        Cctv cctv12 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv12.cameraBrand);
        System.out.println("The cameraId is : " + cctv12.cameraId);
        System.out.println("The cameraPrice is : " + cctv12.cameraPrice);
        System.out.println("The isAvailable is : " + cctv12.isAvailable);
        System.out.println("The cameraType is : " + cctv12.cameraType);
        System.out.println("The resolutionMP is : " + cctv12.resolutionMP);
        System.out.println("The weight is : " + cctv12.weight);
        System.out.println("The isNightVision is : " + cctv12.isNightVision);
        System.out.println("The lensType is : " + cctv12.lensType);
        System.out.println("The warrantyYears is : " + cctv12.warrantyYears);
        System.out.println("The viewAngle is : " + cctv12.viewAngle);
        System.out.println("The isWireless is : " + cctv12.isWireless);
        System.out.println("The color is : " + cctv12.color);
        System.out.println("The stockQuantity is : " + cctv12.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv12.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv12.isWaterproof);
        System.out.println("The storageType is : " + cctv12.storageType);
        System.out.println("The rating is : " + cctv12.rating);
        System.out.println("The frameRate is : " + cctv12.frameRate);
        System.out.println("The isCertified is : " + cctv12.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv12.manufacturingYear);
        System.out.println("The cableLength is : " + cctv12.cableLength);
        System.out.println("The supportsMobileView is : " + cctv12.supportsMobileView);
        System.out.println("The certificationType is : " + cctv12.certificationType);

        cctv12.cameraBrand = "Hikvision";
        cctv12.cameraId = 12;
        cctv12.cameraPrice = 12500.50;
        cctv12.isAvailable = true;
        cctv12.cameraType = "Dome";
        cctv12.resolutionMP = 5;
        cctv12.weight = 0.75;
        cctv12.isNightVision = true;
        cctv12.lensType = "Wide";
        cctv12.warrantyYears = 2;
        cctv12.viewAngle = 120.0;
        cctv12.isWireless = false;
        cctv12.color = "White";
        cctv12.stockQuantity = 30;
        cctv12.powerConsumption = 12.5;
        cctv12.isWaterproof = true;
        cctv12.storageType = "SD Card";
        cctv12.rating = 4;
        cctv12.frameRate = 30.0;
        cctv12.isCertified = true;
        cctv12.countryOfOrigin = "China";
        cctv12.manufacturingYear = 2025;
        cctv12.cableLength = 10.0;
        cctv12.supportsMobileView = true;
        cctv12.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv12.cameraBrand);
        System.out.println("The cameraId is : " + cctv12.cameraId);
        System.out.println("The cameraPrice is : " + cctv12.cameraPrice);
        System.out.println("The isAvailable is : " + cctv12.isAvailable);
        System.out.println("The cameraType is : " + cctv12.cameraType);
        System.out.println("The resolutionMP is : " + cctv12.resolutionMP);
        System.out.println("The weight is : " + cctv12.weight);
        System.out.println("The isNightVision is : " + cctv12.isNightVision);
        System.out.println("The lensType is : " + cctv12.lensType);
        System.out.println("The warrantyYears is : " + cctv12.warrantyYears);
        System.out.println("The viewAngle is : " + cctv12.viewAngle);
        System.out.println("The isWireless is : " + cctv12.isWireless);
        System.out.println("The color is : " + cctv12.color);
        System.out.println("The stockQuantity is : " + cctv12.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv12.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv12.isWaterproof);
        System.out.println("The storageType is : " + cctv12.storageType);
        System.out.println("The rating is : " + cctv12.rating);
        System.out.println("The frameRate is : " + cctv12.frameRate);
        System.out.println("The isCertified is : " + cctv12.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv12.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv12.manufacturingYear);
        System.out.println("The cableLength is : " + cctv12.cableLength);
        System.out.println("The supportsMobileView is : " + cctv12.supportsMobileView);
        System.out.println("The certificationType is : " + cctv12.certificationType);


        Cctv cctv13 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv13.cameraBrand);
        System.out.println("The cameraId is : " + cctv13.cameraId);
        System.out.println("The cameraPrice is : " + cctv13.cameraPrice);
        System.out.println("The isAvailable is : " + cctv13.isAvailable);
        System.out.println("The cameraType is : " + cctv13.cameraType);
        System.out.println("The resolutionMP is : " + cctv13.resolutionMP);
        System.out.println("The weight is : " + cctv13.weight);
        System.out.println("The isNightVision is : " + cctv13.isNightVision);
        System.out.println("The lensType is : " + cctv13.lensType);
        System.out.println("The warrantyYears is : " + cctv13.warrantyYears);
        System.out.println("The viewAngle is : " + cctv13.viewAngle);
        System.out.println("The isWireless is : " + cctv13.isWireless);
        System.out.println("The color is : " + cctv13.color);
        System.out.println("The stockQuantity is : " + cctv13.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv13.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv13.isWaterproof);
        System.out.println("The storageType is : " + cctv13.storageType);
        System.out.println("The rating is : " + cctv13.rating);
        System.out.println("The frameRate is : " + cctv13.frameRate);
        System.out.println("The isCertified is : " + cctv13.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv13.manufacturingYear);
        System.out.println("The cableLength is : " + cctv13.cableLength);
        System.out.println("The supportsMobileView is : " + cctv13.supportsMobileView);
        System.out.println("The certificationType is : " + cctv13.certificationType);

        cctv13.cameraBrand = "Hikvision";
        cctv13.cameraId = 13;
        cctv13.cameraPrice = 13500.50;
        cctv13.isAvailable = true;
        cctv13.cameraType = "Dome";
        cctv13.resolutionMP = 5;
        cctv13.weight = 0.75;
        cctv13.isNightVision = true;
        cctv13.lensType = "Wide";
        cctv13.warrantyYears = 2;
        cctv13.viewAngle = 120.0;
        cctv13.isWireless = false;
        cctv13.color = "White";
        cctv13.stockQuantity = 30;
        cctv13.powerConsumption = 12.5;
        cctv13.isWaterproof = true;
        cctv13.storageType = "SD Card";
        cctv13.rating = 4;
        cctv13.frameRate = 30.0;
        cctv13.isCertified = true;
        cctv13.countryOfOrigin = "China";
        cctv13.manufacturingYear = 2025;
        cctv13.cableLength = 10.0;
        cctv13.supportsMobileView = true;
        cctv13.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv13.cameraBrand);
        System.out.println("The cameraId is : " + cctv13.cameraId);
        System.out.println("The cameraPrice is : " + cctv13.cameraPrice);
        System.out.println("The isAvailable is : " + cctv13.isAvailable);
        System.out.println("The cameraType is : " + cctv13.cameraType);
        System.out.println("The resolutionMP is : " + cctv13.resolutionMP);
        System.out.println("The weight is : " + cctv13.weight);
        System.out.println("The isNightVision is : " + cctv13.isNightVision);
        System.out.println("The lensType is : " + cctv13.lensType);
        System.out.println("The warrantyYears is : " + cctv13.warrantyYears);
        System.out.println("The viewAngle is : " + cctv13.viewAngle);
        System.out.println("The isWireless is : " + cctv13.isWireless);
        System.out.println("The color is : " + cctv13.color);
        System.out.println("The stockQuantity is : " + cctv13.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv13.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv13.isWaterproof);
        System.out.println("The storageType is : " + cctv13.storageType);
        System.out.println("The rating is : " + cctv13.rating);
        System.out.println("The frameRate is : " + cctv13.frameRate);
        System.out.println("The isCertified is : " + cctv13.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv13.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv13.manufacturingYear);
        System.out.println("The cableLength is : " + cctv13.cableLength);
        System.out.println("The supportsMobileView is : " + cctv13.supportsMobileView);
        System.out.println("The certificationType is : " + cctv13.certificationType);


        Cctv cctv14 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv14.cameraBrand);
        System.out.println("The cameraId is : " + cctv14.cameraId);
        System.out.println("The cameraPrice is : " + cctv14.cameraPrice);
        System.out.println("The isAvailable is : " + cctv14.isAvailable);
        System.out.println("The cameraType is : " + cctv14.cameraType);
        System.out.println("The resolutionMP is : " + cctv14.resolutionMP);
        System.out.println("The weight is : " + cctv14.weight);
        System.out.println("The isNightVision is : " + cctv14.isNightVision);
        System.out.println("The lensType is : " + cctv14.lensType);
        System.out.println("The warrantyYears is : " + cctv14.warrantyYears);
        System.out.println("The viewAngle is : " + cctv14.viewAngle);
        System.out.println("The isWireless is : " + cctv14.isWireless);
        System.out.println("The color is : " + cctv14.color);
        System.out.println("The stockQuantity is : " + cctv14.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv14.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv14.isWaterproof);
        System.out.println("The storageType is : " + cctv14.storageType);
        System.out.println("The rating is : " + cctv14.rating);
        System.out.println("The frameRate is : " + cctv14.frameRate);
        System.out.println("The isCertified is : " + cctv14.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv14.manufacturingYear);
        System.out.println("The cableLength is : " + cctv14.cableLength);
        System.out.println("The supportsMobileView is : " + cctv14.supportsMobileView);
        System.out.println("The certificationType is : " + cctv14.certificationType);

        cctv14.cameraBrand = "Hikvision";
        cctv14.cameraId = 14;
        cctv14.cameraPrice = 14500.50;
        cctv14.isAvailable = true;
        cctv14.cameraType = "Dome";
        cctv14.resolutionMP = 5;
        cctv14.weight = 0.75;
        cctv14.isNightVision = true;
        cctv14.lensType = "Wide";
        cctv14.warrantyYears = 2;
        cctv14.viewAngle = 120.0;
        cctv14.isWireless = false;
        cctv14.color = "White";
        cctv14.stockQuantity = 30;
        cctv14.powerConsumption = 12.5;
        cctv14.isWaterproof = true;
        cctv14.storageType = "SD Card";
        cctv14.rating = 4;
        cctv14.frameRate = 30.0;
        cctv14.isCertified = true;
        cctv14.countryOfOrigin = "China";
        cctv14.manufacturingYear = 2025;
        cctv14.cableLength = 10.0;
        cctv14.supportsMobileView = true;
        cctv14.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv14.cameraBrand);
        System.out.println("The cameraId is : " + cctv14.cameraId);
        System.out.println("The cameraPrice is : " + cctv14.cameraPrice);
        System.out.println("The isAvailable is : " + cctv14.isAvailable);
        System.out.println("The cameraType is : " + cctv14.cameraType);
        System.out.println("The resolutionMP is : " + cctv14.resolutionMP);
        System.out.println("The weight is : " + cctv14.weight);
        System.out.println("The isNightVision is : " + cctv14.isNightVision);
        System.out.println("The lensType is : " + cctv14.lensType);
        System.out.println("The warrantyYears is : " + cctv14.warrantyYears);
        System.out.println("The viewAngle is : " + cctv14.viewAngle);
        System.out.println("The isWireless is : " + cctv14.isWireless);
        System.out.println("The color is : " + cctv14.color);
        System.out.println("The stockQuantity is : " + cctv14.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv14.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv14.isWaterproof);
        System.out.println("The storageType is : " + cctv14.storageType);
        System.out.println("The rating is : " + cctv14.rating);
        System.out.println("The frameRate is : " + cctv14.frameRate);
        System.out.println("The isCertified is : " + cctv14.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv14.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv14.manufacturingYear);
        System.out.println("The cableLength is : " + cctv14.cableLength);
        System.out.println("The supportsMobileView is : " + cctv14.supportsMobileView);
        System.out.println("The certificationType is : " + cctv14.certificationType);


        Cctv cctv15 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv15.cameraBrand);
        System.out.println("The cameraId is : " + cctv15.cameraId);
        System.out.println("The cameraPrice is : " + cctv15.cameraPrice);
        System.out.println("The isAvailable is : " + cctv15.isAvailable);
        System.out.println("The cameraType is : " + cctv15.cameraType);
        System.out.println("The resolutionMP is : " + cctv15.resolutionMP);
        System.out.println("The weight is : " + cctv15.weight);
        System.out.println("The isNightVision is : " + cctv15.isNightVision);
        System.out.println("The lensType is : " + cctv15.lensType);
        System.out.println("The warrantyYears is : " + cctv15.warrantyYears);
        System.out.println("The viewAngle is : " + cctv15.viewAngle);
        System.out.println("The isWireless is : " + cctv15.isWireless);
        System.out.println("The color is : " + cctv15.color);
        System.out.println("The stockQuantity is : " + cctv15.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv15.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv15.isWaterproof);
        System.out.println("The storageType is : " + cctv15.storageType);
        System.out.println("The rating is : " + cctv15.rating);
        System.out.println("The frameRate is : " + cctv15.frameRate);
        System.out.println("The isCertified is : " + cctv15.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv15.manufacturingYear);
        System.out.println("The cableLength is : " + cctv15.cableLength);
        System.out.println("The supportsMobileView is : " + cctv15.supportsMobileView);
        System.out.println("The certificationType is : " + cctv15.certificationType);

        cctv15.cameraBrand = "Hikvision";
        cctv15.cameraId = 15;
        cctv15.cameraPrice = 15500.50;
        cctv15.isAvailable = true;
        cctv15.cameraType = "Dome";
        cctv15.resolutionMP = 5;
        cctv15.weight = 0.75;
        cctv15.isNightVision = true;
        cctv15.lensType = "Wide";
        cctv15.warrantyYears = 2;
        cctv15.viewAngle = 120.0;
        cctv15.isWireless = false;
        cctv15.color = "White";
        cctv15.stockQuantity = 30;
        cctv15.powerConsumption = 12.5;
        cctv15.isWaterproof = true;
        cctv15.storageType = "SD Card";
        cctv15.rating = 4;
        cctv15.frameRate = 30.0;
        cctv15.isCertified = true;
        cctv15.countryOfOrigin = "China";
        cctv15.manufacturingYear = 2025;
        cctv15.cableLength = 10.0;
        cctv15.supportsMobileView = true;
        cctv15.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv15.cameraBrand);
        System.out.println("The cameraId is : " + cctv15.cameraId);
        System.out.println("The cameraPrice is : " + cctv15.cameraPrice);
        System.out.println("The isAvailable is : " + cctv15.isAvailable);
        System.out.println("The cameraType is : " + cctv15.cameraType);
        System.out.println("The resolutionMP is : " + cctv15.resolutionMP);
        System.out.println("The weight is : " + cctv15.weight);
        System.out.println("The isNightVision is : " + cctv15.isNightVision);
        System.out.println("The lensType is : " + cctv15.lensType);
        System.out.println("The warrantyYears is : " + cctv15.warrantyYears);
        System.out.println("The viewAngle is : " + cctv15.viewAngle);
        System.out.println("The isWireless is : " + cctv15.isWireless);
        System.out.println("The color is : " + cctv15.color);
        System.out.println("The stockQuantity is : " + cctv15.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv15.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv15.isWaterproof);
        System.out.println("The storageType is : " + cctv15.storageType);
        System.out.println("The rating is : " + cctv15.rating);
        System.out.println("The frameRate is : " + cctv15.frameRate);
        System.out.println("The isCertified is : " + cctv15.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv15.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv15.manufacturingYear);
        System.out.println("The cableLength is : " + cctv15.cableLength);
        System.out.println("The supportsMobileView is : " + cctv15.supportsMobileView);
        System.out.println("The certificationType is : " + cctv15.certificationType);


        Cctv cctv16 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv16.cameraBrand);
        System.out.println("The cameraId is : " + cctv16.cameraId);
        System.out.println("The cameraPrice is : " + cctv16.cameraPrice);
        System.out.println("The isAvailable is : " + cctv16.isAvailable);
        System.out.println("The cameraType is : " + cctv16.cameraType);
        System.out.println("The resolutionMP is : " + cctv16.resolutionMP);
        System.out.println("The weight is : " + cctv16.weight);
        System.out.println("The isNightVision is : " + cctv16.isNightVision);
        System.out.println("The lensType is : " + cctv16.lensType);
        System.out.println("The warrantyYears is : " + cctv16.warrantyYears);
        System.out.println("The viewAngle is : " + cctv16.viewAngle);
        System.out.println("The isWireless is : " + cctv16.isWireless);
        System.out.println("The color is : " + cctv16.color);
        System.out.println("The stockQuantity is : " + cctv16.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv16.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv16.isWaterproof);
        System.out.println("The storageType is : " + cctv16.storageType);
        System.out.println("The rating is : " + cctv16.rating);
        System.out.println("The frameRate is : " + cctv16.frameRate);
        System.out.println("The isCertified is : " + cctv16.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv16.manufacturingYear);
        System.out.println("The cableLength is : " + cctv16.cableLength);
        System.out.println("The supportsMobileView is : " + cctv16.supportsMobileView);
        System.out.println("The certificationType is : " + cctv16.certificationType);

        cctv16.cameraBrand = "Hikvision";
        cctv16.cameraId = 16;
        cctv16.cameraPrice = 16500.50;
        cctv16.isAvailable = true;
        cctv16.cameraType = "Dome";
        cctv16.resolutionMP = 5;
        cctv16.weight = 0.75;
        cctv16.isNightVision = true;
        cctv16.lensType = "Wide";
        cctv16.warrantyYears = 2;
        cctv16.viewAngle = 120.0;
        cctv16.isWireless = false;
        cctv16.color = "White";
        cctv16.stockQuantity = 30;
        cctv16.powerConsumption = 12.5;
        cctv16.isWaterproof = true;
        cctv16.storageType = "SD Card";
        cctv16.rating = 4;
        cctv16.frameRate = 30.0;
        cctv16.isCertified = true;
        cctv16.countryOfOrigin = "China";
        cctv16.manufacturingYear = 2025;
        cctv16.cableLength = 10.0;
        cctv16.supportsMobileView = true;
        cctv16.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv16.cameraBrand);
        System.out.println("The cameraId is : " + cctv16.cameraId);
        System.out.println("The cameraPrice is : " + cctv16.cameraPrice);
        System.out.println("The isAvailable is : " + cctv16.isAvailable);
        System.out.println("The cameraType is : " + cctv16.cameraType);
        System.out.println("The resolutionMP is : " + cctv16.resolutionMP);
        System.out.println("The weight is : " + cctv16.weight);
        System.out.println("The isNightVision is : " + cctv16.isNightVision);
        System.out.println("The lensType is : " + cctv16.lensType);
        System.out.println("The warrantyYears is : " + cctv16.warrantyYears);
        System.out.println("The viewAngle is : " + cctv16.viewAngle);
        System.out.println("The isWireless is : " + cctv16.isWireless);
        System.out.println("The color is : " + cctv16.color);
        System.out.println("The stockQuantity is : " + cctv16.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv16.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv16.isWaterproof);
        System.out.println("The storageType is : " + cctv16.storageType);
        System.out.println("The rating is : " + cctv16.rating);
        System.out.println("The frameRate is : " + cctv16.frameRate);
        System.out.println("The isCertified is : " + cctv16.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv16.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv16.manufacturingYear);
        System.out.println("The cableLength is : " + cctv16.cableLength);
        System.out.println("The supportsMobileView is : " + cctv16.supportsMobileView);
        System.out.println("The certificationType is : " + cctv16.certificationType);


        Cctv cctv17 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv17.cameraBrand);
        System.out.println("The cameraId is : " + cctv17.cameraId);
        System.out.println("The cameraPrice is : " + cctv17.cameraPrice);
        System.out.println("The isAvailable is : " + cctv17.isAvailable);
        System.out.println("The cameraType is : " + cctv17.cameraType);
        System.out.println("The resolutionMP is : " + cctv17.resolutionMP);
        System.out.println("The weight is : " + cctv17.weight);
        System.out.println("The isNightVision is : " + cctv17.isNightVision);
        System.out.println("The lensType is : " + cctv17.lensType);
        System.out.println("The warrantyYears is : " + cctv17.warrantyYears);
        System.out.println("The viewAngle is : " + cctv17.viewAngle);
        System.out.println("The isWireless is : " + cctv17.isWireless);
        System.out.println("The color is : " + cctv17.color);
        System.out.println("The stockQuantity is : " + cctv17.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv17.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv17.isWaterproof);
        System.out.println("The storageType is : " + cctv17.storageType);
        System.out.println("The rating is : " + cctv17.rating);
        System.out.println("The frameRate is : " + cctv17.frameRate);
        System.out.println("The isCertified is : " + cctv17.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv17.manufacturingYear);
        System.out.println("The cableLength is : " + cctv17.cableLength);
        System.out.println("The supportsMobileView is : " + cctv17.supportsMobileView);
        System.out.println("The certificationType is : " + cctv17.certificationType);

        cctv17.cameraBrand = "Hikvision";
        cctv17.cameraId = 17;
        cctv17.cameraPrice = 17500.50;
        cctv17.isAvailable = true;
        cctv17.cameraType = "Dome";
        cctv17.resolutionMP = 5;
        cctv17.weight = 0.75;
        cctv17.isNightVision = true;
        cctv17.lensType = "Wide";
        cctv17.warrantyYears = 2;
        cctv17.viewAngle = 120.0;
        cctv17.isWireless = false;
        cctv17.color = "White";
        cctv17.stockQuantity = 30;
        cctv17.powerConsumption = 12.5;
        cctv17.isWaterproof = true;
        cctv17.storageType = "SD Card";
        cctv17.rating = 4;
        cctv17.frameRate = 30.0;
        cctv17.isCertified = true;
        cctv17.countryOfOrigin = "China";
        cctv17.manufacturingYear = 2025;
        cctv17.cableLength = 10.0;
        cctv17.supportsMobileView = true;
        cctv17.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv17.cameraBrand);
        System.out.println("The cameraId is : " + cctv17.cameraId);
        System.out.println("The cameraPrice is : " + cctv17.cameraPrice);
        System.out.println("The isAvailable is : " + cctv17.isAvailable);
        System.out.println("The cameraType is : " + cctv17.cameraType);
        System.out.println("The resolutionMP is : " + cctv17.resolutionMP);
        System.out.println("The weight is : " + cctv17.weight);
        System.out.println("The isNightVision is : " + cctv17.isNightVision);
        System.out.println("The lensType is : " + cctv17.lensType);
        System.out.println("The warrantyYears is : " + cctv17.warrantyYears);
        System.out.println("The viewAngle is : " + cctv17.viewAngle);
        System.out.println("The isWireless is : " + cctv17.isWireless);
        System.out.println("The color is : " + cctv17.color);
        System.out.println("The stockQuantity is : " + cctv17.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv17.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv17.isWaterproof);
        System.out.println("The storageType is : " + cctv17.storageType);
        System.out.println("The rating is : " + cctv17.rating);
        System.out.println("The frameRate is : " + cctv17.frameRate);
        System.out.println("The isCertified is : " + cctv17.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv17.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv17.manufacturingYear);
        System.out.println("The cableLength is : " + cctv17.cableLength);
        System.out.println("The supportsMobileView is : " + cctv17.supportsMobileView);
        System.out.println("The certificationType is : " + cctv17.certificationType);


        Cctv cctv18 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv18.cameraBrand);
        System.out.println("The cameraId is : " + cctv18.cameraId);
        System.out.println("The cameraPrice is : " + cctv18.cameraPrice);
        System.out.println("The isAvailable is : " + cctv18.isAvailable);
        System.out.println("The cameraType is : " + cctv18.cameraType);
        System.out.println("The resolutionMP is : " + cctv18.resolutionMP);
        System.out.println("The weight is : " + cctv18.weight);
        System.out.println("The isNightVision is : " + cctv18.isNightVision);
        System.out.println("The lensType is : " + cctv18.lensType);
        System.out.println("The warrantyYears is : " + cctv18.warrantyYears);
        System.out.println("The viewAngle is : " + cctv18.viewAngle);
        System.out.println("The isWireless is : " + cctv18.isWireless);
        System.out.println("The color is : " + cctv18.color);
        System.out.println("The stockQuantity is : " + cctv18.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv18.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv18.isWaterproof);
        System.out.println("The storageType is : " + cctv18.storageType);
        System.out.println("The rating is : " + cctv18.rating);
        System.out.println("The frameRate is : " + cctv18.frameRate);
        System.out.println("The isCertified is : " + cctv18.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv18.manufacturingYear);
        System.out.println("The cableLength is : " + cctv18.cableLength);
        System.out.println("The supportsMobileView is : " + cctv18.supportsMobileView);
        System.out.println("The certificationType is : " + cctv18.certificationType);

        cctv18.cameraBrand = "Hikvision";
        cctv18.cameraId = 18;
        cctv18.cameraPrice = 18500.50;
        cctv18.isAvailable = true;
        cctv18.cameraType = "Dome";
        cctv18.resolutionMP = 5;
        cctv18.weight = 0.75;
        cctv18.isNightVision = true;
        cctv18.lensType = "Wide";
        cctv18.warrantyYears = 2;
        cctv18.viewAngle = 120.0;
        cctv18.isWireless = false;
        cctv18.color = "White";
        cctv18.stockQuantity = 30;
        cctv18.powerConsumption = 12.5;
        cctv18.isWaterproof = true;
        cctv18.storageType = "SD Card";
        cctv18.rating = 4;
        cctv18.frameRate = 30.0;
        cctv18.isCertified = true;
        cctv18.countryOfOrigin = "China";
        cctv18.manufacturingYear = 2025;
        cctv18.cableLength = 10.0;
        cctv18.supportsMobileView = true;
        cctv18.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv18.cameraBrand);
        System.out.println("The cameraId is : " + cctv18.cameraId);
        System.out.println("The cameraPrice is : " + cctv18.cameraPrice);
        System.out.println("The isAvailable is : " + cctv18.isAvailable);
        System.out.println("The cameraType is : " + cctv18.cameraType);
        System.out.println("The resolutionMP is : " + cctv18.resolutionMP);
        System.out.println("The weight is : " + cctv18.weight);
        System.out.println("The isNightVision is : " + cctv18.isNightVision);
        System.out.println("The lensType is : " + cctv18.lensType);
        System.out.println("The warrantyYears is : " + cctv18.warrantyYears);
        System.out.println("The viewAngle is : " + cctv18.viewAngle);
        System.out.println("The isWireless is : " + cctv18.isWireless);
        System.out.println("The color is : " + cctv18.color);
        System.out.println("The stockQuantity is : " + cctv18.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv18.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv18.isWaterproof);
        System.out.println("The storageType is : " + cctv18.storageType);
        System.out.println("The rating is : " + cctv18.rating);
        System.out.println("The frameRate is : " + cctv18.frameRate);
        System.out.println("The isCertified is : " + cctv18.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv18.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv18.manufacturingYear);
        System.out.println("The cableLength is : " + cctv18.cableLength);
        System.out.println("The supportsMobileView is : " + cctv18.supportsMobileView);
        System.out.println("The certificationType is : " + cctv18.certificationType);


        Cctv cctv19 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv19.cameraBrand);
        System.out.println("The cameraId is : " + cctv19.cameraId);
        System.out.println("The cameraPrice is : " + cctv19.cameraPrice);
        System.out.println("The isAvailable is : " + cctv19.isAvailable);
        System.out.println("The cameraType is : " + cctv19.cameraType);
        System.out.println("The resolutionMP is : " + cctv19.resolutionMP);
        System.out.println("The weight is : " + cctv19.weight);
        System.out.println("The isNightVision is : " + cctv19.isNightVision);
        System.out.println("The lensType is : " + cctv19.lensType);
        System.out.println("The warrantyYears is : " + cctv19.warrantyYears);
        System.out.println("The viewAngle is : " + cctv19.viewAngle);
        System.out.println("The isWireless is : " + cctv19.isWireless);
        System.out.println("The color is : " + cctv19.color);
        System.out.println("The stockQuantity is : " + cctv19.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv19.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv19.isWaterproof);
        System.out.println("The storageType is : " + cctv19.storageType);
        System.out.println("The rating is : " + cctv19.rating);
        System.out.println("The frameRate is : " + cctv19.frameRate);
        System.out.println("The isCertified is : " + cctv19.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv19.manufacturingYear);
        System.out.println("The cableLength is : " + cctv19.cableLength);
        System.out.println("The supportsMobileView is : " + cctv19.supportsMobileView);
        System.out.println("The certificationType is : " + cctv19.certificationType);

        cctv19.cameraBrand = "Hikvision";
        cctv19.cameraId = 19;
        cctv19.cameraPrice = 19500.50;
        cctv19.isAvailable = true;
        cctv19.cameraType = "Dome";
        cctv19.resolutionMP = 5;
        cctv19.weight = 0.75;
        cctv19.isNightVision = true;
        cctv19.lensType = "Wide";
        cctv19.warrantyYears = 2;
        cctv19.viewAngle = 120.0;
        cctv19.isWireless = false;
        cctv19.color = "White";
        cctv19.stockQuantity = 30;
        cctv19.powerConsumption = 12.5;
        cctv19.isWaterproof = true;
        cctv19.storageType = "SD Card";
        cctv19.rating = 4;
        cctv19.frameRate = 30.0;
        cctv19.isCertified = true;
        cctv19.countryOfOrigin = "China";
        cctv19.manufacturingYear = 2025;
        cctv19.cableLength = 10.0;
        cctv19.supportsMobileView = true;
        cctv19.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv19.cameraBrand);
        System.out.println("The cameraId is : " + cctv19.cameraId);
        System.out.println("The cameraPrice is : " + cctv19.cameraPrice);
        System.out.println("The isAvailable is : " + cctv19.isAvailable);
        System.out.println("The cameraType is : " + cctv19.cameraType);
        System.out.println("The resolutionMP is : " + cctv19.resolutionMP);
        System.out.println("The weight is : " + cctv19.weight);
        System.out.println("The isNightVision is : " + cctv19.isNightVision);
        System.out.println("The lensType is : " + cctv19.lensType);
        System.out.println("The warrantyYears is : " + cctv19.warrantyYears);
        System.out.println("The viewAngle is : " + cctv19.viewAngle);
        System.out.println("The isWireless is : " + cctv19.isWireless);
        System.out.println("The color is : " + cctv19.color);
        System.out.println("The stockQuantity is : " + cctv19.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv19.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv19.isWaterproof);
        System.out.println("The storageType is : " + cctv19.storageType);
        System.out.println("The rating is : " + cctv19.rating);
        System.out.println("The frameRate is : " + cctv19.frameRate);
        System.out.println("The isCertified is : " + cctv19.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv19.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv19.manufacturingYear);
        System.out.println("The cableLength is : " + cctv19.cableLength);
        System.out.println("The supportsMobileView is : " + cctv19.supportsMobileView);
        System.out.println("The certificationType is : " + cctv19.certificationType);


        Cctv cctv20 = new Cctv();

        System.out.println("Before initialization");

        System.out.println("The cameraBrand is : " + cctv20.cameraBrand);
        System.out.println("The cameraId is : " + cctv20.cameraId);
        System.out.println("The cameraPrice is : " + cctv20.cameraPrice);
        System.out.println("The isAvailable is : " + cctv20.isAvailable);
        System.out.println("The cameraType is : " + cctv20.cameraType);
        System.out.println("The resolutionMP is : " + cctv20.resolutionMP);
        System.out.println("The weight is : " + cctv20.weight);
        System.out.println("The isNightVision is : " + cctv20.isNightVision);
        System.out.println("The lensType is : " + cctv20.lensType);
        System.out.println("The warrantyYears is : " + cctv20.warrantyYears);
        System.out.println("The viewAngle is : " + cctv20.viewAngle);
        System.out.println("The isWireless is : " + cctv20.isWireless);
        System.out.println("The color is : " + cctv20.color);
        System.out.println("The stockQuantity is : " + cctv20.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv20.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv20.isWaterproof);
        System.out.println("The storageType is : " + cctv20.storageType);
        System.out.println("The rating is : " + cctv20.rating);
        System.out.println("The frameRate is : " + cctv20.frameRate);
        System.out.println("The isCertified is : " + cctv20.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv20.manufacturingYear);
        System.out.println("The cableLength is : " + cctv20.cableLength);
        System.out.println("The supportsMobileView is : " + cctv20.supportsMobileView);
        System.out.println("The certificationType is : " + cctv20.certificationType);

        cctv20.cameraBrand = "Hikvision";
        cctv20.cameraId = 20;
        cctv20.cameraPrice = 20500.50;
        cctv20.isAvailable = true;
        cctv20.cameraType = "Dome";
        cctv20.resolutionMP = 5;
        cctv20.weight = 0.75;
        cctv20.isNightVision = true;
        cctv20.lensType = "Wide";
        cctv20.warrantyYears = 2;
        cctv20.viewAngle = 120.0;
        cctv20.isWireless = false;
        cctv20.color = "White";
        cctv20.stockQuantity = 30;
        cctv20.powerConsumption = 12.5;
        cctv20.isWaterproof = true;
        cctv20.storageType = "SD Card";
        cctv20.rating = 4;
        cctv20.frameRate = 30.0;
        cctv20.isCertified = true;
        cctv20.countryOfOrigin = "China";
        cctv20.manufacturingYear = 2025;
        cctv20.cableLength = 10.0;
        cctv20.supportsMobileView = true;
        cctv20.certificationType = "ISO";

        System.out.println("After initialization");

        System.out.println("The cameraBrand is : " + cctv20.cameraBrand);
        System.out.println("The cameraId is : " + cctv20.cameraId);
        System.out.println("The cameraPrice is : " + cctv20.cameraPrice);
        System.out.println("The isAvailable is : " + cctv20.isAvailable);
        System.out.println("The cameraType is : " + cctv20.cameraType);
        System.out.println("The resolutionMP is : " + cctv20.resolutionMP);
        System.out.println("The weight is : " + cctv20.weight);
        System.out.println("The isNightVision is : " + cctv20.isNightVision);
        System.out.println("The lensType is : " + cctv20.lensType);
        System.out.println("The warrantyYears is : " + cctv20.warrantyYears);
        System.out.println("The viewAngle is : " + cctv20.viewAngle);
        System.out.println("The isWireless is : " + cctv20.isWireless);
        System.out.println("The color is : " + cctv20.color);
        System.out.println("The stockQuantity is : " + cctv20.stockQuantity);
        System.out.println("The powerConsumption is : " + cctv20.powerConsumption);
        System.out.println("The isWaterproof is : " + cctv20.isWaterproof);
        System.out.println("The storageType is : " + cctv20.storageType);
        System.out.println("The rating is : " + cctv20.rating);
        System.out.println("The frameRate is : " + cctv20.frameRate);
        System.out.println("The isCertified is : " + cctv20.isCertified);
        System.out.println("The countryOfOrigin is : " + cctv20.countryOfOrigin);
        System.out.println("The manufacturingYear is : " + cctv20.manufacturingYear);
        System.out.println("The cableLength is : " + cctv20.cableLength);
        System.out.println("The supportsMobileView is : " + cctv20.supportsMobileView);
        System.out.println("The certificationType is : " + cctv20.certificationType);


    }
}
