class CellPhoneExecutor{

public static void main(String [] args){
	String contactName = "Mahesh";
long contactNo  = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Ravi";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Lava";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Kusha";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Abhi";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Bheema";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Ramu";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Hemanth";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Pampa";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Ranna";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Janna";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Narsima";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Darshan";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Sathya";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Lalu";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Vianayk";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Arun";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Mallesh";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
contactName = "Bhushan";
contactNo = CellPhone.searchContatc(contactName);
System.out.println("the number of the contact is :" + contactNo);
}}