class FlightExecutor {
    public static void main(String[] args){
        
        Flight flight1 = new Flight();

        System.out.println("Before Initialization of Flight1");
        System.out.println("Flight ID is " + flight1.flightId);
        System.out.println("Airline is " + flight1.airlineName);
        System.out.println("Source is " + flight1.source);
        System.out.println("Total Seats are " + flight1.totalSeats);
        System.out.println("Crew Count is " + flight1.crewCount);
        System.out.println("Wifi Available " + flight1.hasWifi);
        System.out.println("Business Class Available " + flight1.hasBusinessClass);
        System.out.println("First Class Available " + flight1.hasFirstClass);
        System.out.println("Meals Available " + flight1.hasMeals);
        System.out.println("Is International " + flight1.isInternational);
        System.out.println("Pilot Name " + flight1.pilotName);
        System.out.println("Departure Time " + flight1.departureTime);
        System.out.println("Arrival Time " + flight1.arrivalTime);
        System.out.println("Rating " + flight1.rating);
        System.out.println("Contact Number " + flight1.contactNumber);
        System.out.println("Email ID " + flight1.email);
        System.out.println("Departure City " + flight1.departureCity);
        System.out.println("Destination State " + flight1.destinationState);
        System.out.println("Destination Country " + flight1.destinationCountry);
        System.out.println("Manufacture Year " + flight1.manufactureYear);
        System.out.println("Lounge Access " + flight1.loungeAccess);
        System.out.println("Entertainment Available " + flight1.entertainmentAvailable);
        System.out.println("Flight Code " + flight1.flightCode);
        System.out.println("Website " + flight1.website);
        System.out.println("Frequent Flyer Available " + flight1.frequentFlyerAvailable);

        flight1.flightId = 1;
        flight1.airlineName = "SkyHigh Airways";
        flight1.source = "Delhi";
        flight1.totalSeats = 180;
        flight1.crewCount = 8;
        flight1.hasWifi = false;
        flight1.hasBusinessClass = true;
        flight1.hasFirstClass = false;
        flight1.hasMeals = true;
        flight1.isInternational = false;
        flight1.pilotName = "Capt. Raj";
        flight1.departureTime = "6AM";
        flight1.arrivalTime = "8:30AM";
        flight1.rating = 4.2;
        flight1.contactNumber = "1800123456";
        flight1.email = "support@skyhigh.com";
        flight1.departureCity = "Delhi";
        flight1.destinationState = "Maharashtra";
        flight1.destinationCountry = "India";
        flight1.manufactureYear = 2018;
        flight1.loungeAccess = true;
        flight1.entertainmentAvailable = false;
        flight1.flightCode = "SH101";
        flight1.website = "www.skyhigh.com";
        flight1.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight1");
        System.out.println("Flight ID is " + flight1.flightId);
        System.out.println("Airline is " + flight1.airlineName);
        System.out.println("Source is " + flight1.source);
        System.out.println("Total Seats are " + flight1.totalSeats);
        System.out.println("Crew Count is " + flight1.crewCount);
        System.out.println("Wifi Available " + flight1.hasWifi);
        System.out.println("Business Class Available " + flight1.hasBusinessClass);
        System.out.println("First Class Available " + flight1.hasFirstClass);
        System.out.println("Meals Available " + flight1.hasMeals);
        System.out.println("Is International " + flight1.isInternational);
        System.out.println("Pilot Name " + flight1.pilotName);
        System.out.println("Departure Time " + flight1.departureTime);
        System.out.println("Arrival Time " + flight1.arrivalTime);
        System.out.println("Rating " + flight1.rating);
        System.out.println("Contact Number " + flight1.contactNumber);
        System.out.println("Email ID " + flight1.email);
        System.out.println("Departure City " + flight1.departureCity);
        System.out.println("Destination State " + flight1.destinationState);
        System.out.println("Destination Country " + flight1.destinationCountry);
        System.out.println("Manufacture Year " + flight1.manufactureYear);
        System.out.println("Lounge Access " + flight1.loungeAccess);
        System.out.println("Entertainment Available " + flight1.entertainmentAvailable);
        System.out.println("Flight Code " + flight1.flightCode);
        System.out.println("Website " + flight1.website);
        System.out.println("Frequent Flyer Available " + flight1.frequentFlyerAvailable);


        Flight flight2 = new Flight();

        System.out.println("Before Initialization of Flight2");
        System.out.println("Flight ID is " + flight2.flightId);
        System.out.println("Airline is " + flight2.airlineName);
        System.out.println("Source is " + flight2.source);
        System.out.println("Total Seats are " + flight2.totalSeats);
        System.out.println("Crew Count is " + flight2.crewCount);
        System.out.println("Wifi Available " + flight2.hasWifi);
        System.out.println("Business Class Available " + flight2.hasBusinessClass);
        System.out.println("First Class Available " + flight2.hasFirstClass);
        System.out.println("Meals Available " + flight2.hasMeals);
        System.out.println("Is International " + flight2.isInternational);
        System.out.println("Pilot Name " + flight2.pilotName);
        System.out.println("Departure Time " + flight2.departureTime);
        System.out.println("Arrival Time " + flight2.arrivalTime);
        System.out.println("Rating " + flight2.rating);
        System.out.println("Contact Number " + flight2.contactNumber);
        System.out.println("Email ID " + flight2.email);
        System.out.println("Departure City " + flight2.departureCity);
        System.out.println("Destination State " + flight2.destinationState);
        System.out.println("Destination Country " + flight2.destinationCountry);
        System.out.println("Manufacture Year " + flight2.manufactureYear);
        System.out.println("Lounge Access " + flight2.loungeAccess);
        System.out.println("Entertainment Available " + flight2.entertainmentAvailable);
        System.out.println("Flight Code " + flight2.flightCode);
        System.out.println("Website " + flight2.website);
        System.out.println("Frequent Flyer Available " + flight2.frequentFlyerAvailable);

        flight2.flightId = 2;
        flight2.airlineName = "Global Jet";
        flight2.source = "Mumbai";
        flight2.totalSeats = 220;
        flight2.crewCount = 10;
        flight2.hasWifi = true;
        flight2.hasBusinessClass = true;
        flight2.hasFirstClass = true;
        flight2.hasMeals = true;
        flight2.isInternational = false;
        flight2.pilotName = "Capt. Singh";
        flight2.departureTime = "9AM";
        flight2.arrivalTime = "11:00AM";
        flight2.rating = 4.5;
        flight2.contactNumber = "1800654321";
        flight2.email = "info@globaljet.com";
        flight2.departureCity = "Mumbai";
        flight2.destinationState = "Karnataka";
        flight2.destinationCountry = "India";
        flight2.manufactureYear = 2020;
        flight2.loungeAccess = true;
        flight2.entertainmentAvailable = true;
        flight2.flightCode = "GJ202";
        flight2.website = "www.globaljet.com";
        flight2.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight2");
        System.out.println("Flight ID is " + flight2.flightId);
        System.out.println("Airline is " + flight2.airlineName);
        System.out.println("Source is " + flight2.source);
        System.out.println("Total Seats are " + flight2.totalSeats);
        System.out.println("Crew Count is " + flight2.crewCount);
        System.out.println("Wifi Available " + flight2.hasWifi);
        System.out.println("Business Class Available " + flight2.hasBusinessClass);
        System.out.println("First Class Available " + flight2.hasFirstClass);
        System.out.println("Meals Available " + flight2.hasMeals);
        System.out.println("Is International " + flight2.isInternational);
        System.out.println("Pilot Name " + flight2.pilotName);
        System.out.println("Departure Time " + flight2.departureTime);
        System.out.println("Arrival Time " + flight2.arrivalTime);
        System.out.println("Rating " + flight2.rating);
        System.out.println("Contact Number " + flight2.contactNumber);
        System.out.println("Email ID " + flight2.email);
        System.out.println("Departure City " + flight2.departureCity);
        System.out.println("Destination State " + flight2.destinationState);
        System.out.println("Destination Country " + flight2.destinationCountry);
        System.out.println("Manufacture Year " + flight2.manufactureYear);
        System.out.println("Lounge Access " + flight2.loungeAccess);
        System.out.println("Entertainment Available " + flight2.entertainmentAvailable);
        System.out.println("Flight Code " + flight2.flightCode);
        System.out.println("Website " + flight2.website);
        System.out.println("Frequent Flyer Available " + flight2.frequentFlyerAvailable);


        Flight flight3 = new Flight();

        System.out.println("Before Initialization of Flight3");
        System.out.println("Flight ID is " + flight3.flightId);
        System.out.println("Airline is " + flight3.airlineName);
        System.out.println("Source is " + flight3.source);
        System.out.println("Total Seats are " + flight3.totalSeats);
        System.out.println("Crew Count is " + flight3.crewCount);
        System.out.println("Wifi Available " + flight3.hasWifi);
        System.out.println("Business Class Available " + flight3.hasBusinessClass);
        System.out.println("First Class Available " + flight3.hasFirstClass);
        System.out.println("Meals Available " + flight3.hasMeals);
        System.out.println("Is International " + flight3.isInternational);
        System.out.println("Pilot Name " + flight3.pilotName);
        System.out.println("Departure Time " + flight3.departureTime);
        System.out.println("Arrival Time " + flight3.arrivalTime);
        System.out.println("Rating " + flight3.rating);
        System.out.println("Contact Number " + flight3.contactNumber);
        System.out.println("Email ID " + flight3.email);
        System.out.println("Departure City " + flight3.departureCity);
        System.out.println("Destination State " + flight3.destinationState);
        System.out.println("Destination Country " + flight3.destinationCountry);
        System.out.println("Manufacture Year " + flight3.manufactureYear);
        System.out.println("Lounge Access " + flight3.loungeAccess);
        System.out.println("Entertainment Available " + flight3.entertainmentAvailable);
        System.out.println("Flight Code " + flight3.flightCode);
        System.out.println("Website " + flight3.website);
        System.out.println("Frequent Flyer Available " + flight3.frequentFlyerAvailable);

        flight3.flightId = 3;
        flight3.airlineName = "Aero India";
        flight3.source = "Bangalore";
        flight3.totalSeats = 150;
        flight3.crewCount = 6;
        flight3.hasWifi = false;
        flight3.hasBusinessClass = false;
        flight3.hasFirstClass = false;
        flight3.hasMeals = false;
        flight3.isInternational = false;
        flight3.pilotName = "Capt. Reddy";
        flight3.departureTime = "11AM";
        flight3.arrivalTime = "1:30PM";
        flight3.rating = 3.9;
        flight3.contactNumber = "1800112233";
        flight3.email = "support@aeroindia.com";
        flight3.departureCity = "Bangalore";
        flight3.destinationState = "Delhi";
        flight3.destinationCountry = "India";
        flight3.manufactureYear = 2015;
        flight3.loungeAccess = false;
        flight3.entertainmentAvailable = false;
        flight3.flightCode = "AI303";
        flight3.website = "www.aeroindia.com";
        flight3.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight3");
        System.out.println("Flight ID is " + flight3.flightId);
        System.out.println("Airline is " + flight3.airlineName);
        System.out.println("Source is " + flight3.source);
        System.out.println("Total Seats are " + flight3.totalSeats);
        System.out.println("Crew Count is " + flight3.crewCount);
        System.out.println("Wifi Available " + flight3.hasWifi);
        System.out.println("Business Class Available " + flight3.hasBusinessClass);
        System.out.println("First Class Available " + flight3.hasFirstClass);
        System.out.println("Meals Available " + flight3.hasMeals);
        System.out.println("Is International " + flight3.isInternational);
        System.out.println("Pilot Name " + flight3.pilotName);
        System.out.println("Departure Time " + flight3.departureTime);
        System.out.println("Arrival Time " + flight3.arrivalTime);
        System.out.println("Rating " + flight3.rating);
        System.out.println("Contact Number " + flight3.contactNumber);
        System.out.println("Email ID " + flight3.email);
        System.out.println("Departure City " + flight3.departureCity);
        System.out.println("Destination State " + flight3.destinationState);
        System.out.println("Destination Country " + flight3.destinationCountry);
        System.out.println("Manufacture Year " + flight3.manufactureYear);
        System.out.println("Lounge Access " + flight3.loungeAccess);
        System.out.println("Entertainment Available " + flight3.entertainmentAvailable);
        System.out.println("Flight Code " + flight3.flightCode);
        System.out.println("Website " + flight3.website);
        System.out.println("Frequent Flyer Available " + flight3.frequentFlyerAvailable);


        Flight flight4 = new Flight();

        System.out.println("Before Initialization of Flight4");
        System.out.println("Flight ID is " + flight4.flightId);
        System.out.println("Airline is " + flight4.airlineName);
        System.out.println("Source is " + flight4.source);
        System.out.println("Total Seats are " + flight4.totalSeats);
        System.out.println("Crew Count is " + flight4.crewCount);
        System.out.println("Wifi Available " + flight4.hasWifi);
        System.out.println("Business Class Available " + flight4.hasBusinessClass);
        System.out.println("First Class Available " + flight4.hasFirstClass);
        System.out.println("Meals Available " + flight4.hasMeals);
        System.out.println("Is International " + flight4.isInternational);
        System.out.println("Pilot Name " + flight4.pilotName);
        System.out.println("Departure Time " + flight4.departureTime);
        System.out.println("Arrival Time " + flight4.arrivalTime);
        System.out.println("Rating " + flight4.rating);
        System.out.println("Contact Number " + flight4.contactNumber);
        System.out.println("Email ID " + flight4.email);
        System.out.println("Departure City " + flight4.departureCity);
        System.out.println("Destination State " + flight4.destinationState);
        System.out.println("Destination Country " + flight4.destinationCountry);
        System.out.println("Manufacture Year " + flight4.manufactureYear);
        System.out.println("Lounge Access " + flight4.loungeAccess);
        System.out.println("Entertainment Available " + flight4.entertainmentAvailable);
        System.out.println("Flight Code " + flight4.flightCode);
        System.out.println("Website " + flight4.website);
        System.out.println("Frequent Flyer Available " + flight4.frequentFlyerAvailable);

        flight4.flightId = 4;
        flight4.airlineName = "Ocean Air";
        flight4.source = "Chennai";
        flight4.totalSeats = 200;
        flight4.crewCount = 9;
        flight4.hasWifi = true;
        flight4.hasBusinessClass = true;
        flight4.hasFirstClass = false;
        flight4.hasMeals = true;
        flight4.isInternational = false;
        flight4.pilotName = "Capt. Iyer";
        flight4.departureTime = "1PM";
        flight4.arrivalTime = "2:45PM";
        flight4.rating = 4.1;
        flight4.contactNumber = "1800445566";
        flight4.email = "hello@oceanair.com";
        flight4.departureCity = "Chennai";
        flight4.destinationState = "Kerala";
        flight4.destinationCountry = "India";
        flight4.manufactureYear = 2019;
        flight4.loungeAccess = true;
        flight4.entertainmentAvailable = true;
        flight4.flightCode = "OA404";
        flight4.website = "www.oceanair.com";
        flight4.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight4");
        System.out.println("Flight ID is " + flight4.flightId);
        System.out.println("Airline is " + flight4.airlineName);
        System.out.println("Source is " + flight4.source);
        System.out.println("Total Seats are " + flight4.totalSeats);
        System.out.println("Crew Count is " + flight4.crewCount);
        System.out.println("Wifi Available " + flight4.hasWifi);
        System.out.println("Business Class Available " + flight4.hasBusinessClass);
        System.out.println("First Class Available " + flight4.hasFirstClass);
        System.out.println("Meals Available " + flight4.hasMeals);
        System.out.println("Is International " + flight4.isInternational);
        System.out.println("Pilot Name " + flight4.pilotName);
        System.out.println("Departure Time " + flight4.departureTime);
        System.out.println("Arrival Time " + flight4.arrivalTime);
        System.out.println("Rating " + flight4.rating);
        System.out.println("Contact Number " + flight4.contactNumber);
        System.out.println("Email ID " + flight4.email);
        System.out.println("Departure City " + flight4.departureCity);
        System.out.println("Destination State " + flight4.destinationState);
        System.out.println("Destination Country " + flight4.destinationCountry);
        System.out.println("Manufacture Year " + flight4.manufactureYear);
        System.out.println("Lounge Access " + flight4.loungeAccess);
        System.out.println("Entertainment Available " + flight4.entertainmentAvailable);
        System.out.println("Flight Code " + flight4.flightCode);
        System.out.println("Website " + flight4.website);
        System.out.println("Frequent Flyer Available " + flight4.frequentFlyerAvailable);


        Flight flight5 = new Flight();

        System.out.println("Before Initialization of Flight5");
        System.out.println("Flight ID is " + flight5.flightId);
        System.out.println("Airline is " + flight5.airlineName);
        System.out.println("Source is " + flight5.source);
        System.out.println("Total Seats are " + flight5.totalSeats);
        System.out.println("Crew Count is " + flight5.crewCount);
        System.out.println("Wifi Available " + flight5.hasWifi);
        System.out.println("Business Class Available " + flight5.hasBusinessClass);
        System.out.println("First Class Available " + flight5.hasFirstClass);
        System.out.println("Meals Available " + flight5.hasMeals);
        System.out.println("Is International " + flight5.isInternational);
        System.out.println("Pilot Name " + flight5.pilotName);
        System.out.println("Departure Time " + flight5.departureTime);
        System.out.println("Arrival Time " + flight5.arrivalTime);
        System.out.println("Rating " + flight5.rating);
        System.out.println("Contact Number " + flight5.contactNumber);
        System.out.println("Email ID " + flight5.email);
        System.out.println("Departure City " + flight5.departureCity);
        System.out.println("Destination State " + flight5.destinationState);
        System.out.println("Destination Country " + flight5.destinationCountry);
        System.out.println("Manufacture Year " + flight5.manufactureYear);
        System.out.println("Lounge Access " + flight5.loungeAccess);
        System.out.println("Entertainment Available " + flight5.entertainmentAvailable);
        System.out.println("Flight Code " + flight5.flightCode);
        System.out.println("Website " + flight5.website);
        System.out.println("Frequent Flyer Available " + flight5.frequentFlyerAvailable);

        flight5.flightId = 5;
        flight5.airlineName = "Mountain Airlines";
        flight5.source = "Kolkata";
        flight5.totalSeats = 120;
        flight5.crewCount = 5;
        flight5.hasWifi = false;
        flight5.hasBusinessClass = false;
        flight5.hasFirstClass = false;
        flight5.hasMeals = true;
        flight5.isInternational = false;
        flight5.pilotName = "Capt. Das";
        flight5.departureTime = "3PM";
        flight5.arrivalTime = "4:30PM";
        flight5.rating = 4.0;
        flight5.contactNumber = "1800778899";
        flight5.email = "contact@mountainair.com";
        flight5.departureCity = "Kolkata";
        flight5.destinationState = "Assam";
        flight5.destinationCountry = "India";
        flight5.manufactureYear = 2014;
        flight5.loungeAccess = false;
        flight5.entertainmentAvailable = false;
        flight5.flightCode = "MA505";
        flight5.website = "www.mountainair.com";
        flight5.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight5");
        System.out.println("Flight ID is " + flight5.flightId);
        System.out.println("Airline is " + flight5.airlineName);
        System.out.println("Source is " + flight5.source);
        System.out.println("Total Seats are " + flight5.totalSeats);
        System.out.println("Crew Count is " + flight5.crewCount);
        System.out.println("Wifi Available " + flight5.hasWifi);
        System.out.println("Business Class Available " + flight5.hasBusinessClass);
        System.out.println("First Class Available " + flight5.hasFirstClass);
        System.out.println("Meals Available " + flight5.hasMeals);
        System.out.println("Is International " + flight5.isInternational);
        System.out.println("Pilot Name " + flight5.pilotName);
        System.out.println("Departure Time " + flight5.departureTime);
        System.out.println("Arrival Time " + flight5.arrivalTime);
        System.out.println("Rating " + flight5.rating);
        System.out.println("Contact Number " + flight5.contactNumber);
        System.out.println("Email ID " + flight5.email);
        System.out.println("Departure City " + flight5.departureCity);
        System.out.println("Destination State " + flight5.destinationState);
        System.out.println("Destination Country " + flight5.destinationCountry);
        System.out.println("Manufacture Year " + flight5.manufactureYear);
        System.out.println("Lounge Access " + flight5.loungeAccess);
        System.out.println("Entertainment Available " + flight5.entertainmentAvailable);
        System.out.println("Flight Code " + flight5.flightCode);
        System.out.println("Website " + flight5.website);
        System.out.println("Frequent Flyer Available " + flight5.frequentFlyerAvailable);


        Flight flight6 = new Flight();

        System.out.println("Before Initialization of Flight6");
        System.out.println("Flight ID is " + flight6.flightId);
        System.out.println("Airline is " + flight6.airlineName);
        System.out.println("Source is " + flight6.source);
        System.out.println("Total Seats are " + flight6.totalSeats);
        System.out.println("Crew Count is " + flight6.crewCount);
        System.out.println("Wifi Available " + flight6.hasWifi);
        System.out.println("Business Class Available " + flight6.hasBusinessClass);
        System.out.println("First Class Available " + flight6.hasFirstClass);
        System.out.println("Meals Available " + flight6.hasMeals);
        System.out.println("Is International " + flight6.isInternational);
        System.out.println("Pilot Name " + flight6.pilotName);
        System.out.println("Departure Time " + flight6.departureTime);
        System.out.println("Arrival Time " + flight6.arrivalTime);
        System.out.println("Rating " + flight6.rating);
        System.out.println("Contact Number " + flight6.contactNumber);
        System.out.println("Email ID " + flight6.email);
        System.out.println("Departure City " + flight6.departureCity);
        System.out.println("Destination State " + flight6.destinationState);
        System.out.println("Destination Country " + flight6.destinationCountry);
        System.out.println("Manufacture Year " + flight6.manufactureYear);
        System.out.println("Lounge Access " + flight6.loungeAccess);
        System.out.println("Entertainment Available " + flight6.entertainmentAvailable);
        System.out.println("Flight Code " + flight6.flightCode);
        System.out.println("Website " + flight6.website);
        System.out.println("Frequent Flyer Available " + flight6.frequentFlyerAvailable);

        flight6.flightId = 6;
        flight6.airlineName = "Desert Wings";
        flight6.source = "Jaipur";
        flight6.totalSeats = 160;
        flight6.crewCount = 7;
        flight6.hasWifi = false;
        flight6.hasBusinessClass = true;
        flight6.hasFirstClass = false;
        flight6.hasMeals = true;
        flight6.isInternational = false;
        flight6.pilotName = "Capt. Sharma";
        flight6.departureTime = "5PM";
        flight6.arrivalTime = "6:15PM";
        flight6.rating = 4.3;
        flight6.contactNumber = "1800998877";
        flight6.email = "info@desertwings.com";
        flight6.departureCity = "Jaipur";
        flight6.destinationState = "Gujarat";
        flight6.destinationCountry = "India";
        flight6.manufactureYear = 2017;
        flight6.loungeAccess = true;
        flight6.entertainmentAvailable = false;
        flight6.flightCode = "DW606";
        flight6.website = "www.desertwings.com";
        flight6.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight6");
        System.out.println("Flight ID is " + flight6.flightId);
        System.out.println("Airline is " + flight6.airlineName);
        System.out.println("Source is " + flight6.source);
        System.out.println("Total Seats are " + flight6.totalSeats);
        System.out.println("Crew Count is " + flight6.crewCount);
        System.out.println("Wifi Available " + flight6.hasWifi);
        System.out.println("Business Class Available " + flight6.hasBusinessClass);
        System.out.println("First Class Available " + flight6.hasFirstClass);
        System.out.println("Meals Available " + flight6.hasMeals);
        System.out.println("Is International " + flight6.isInternational);
        System.out.println("Pilot Name " + flight6.pilotName);
        System.out.println("Departure Time " + flight6.departureTime);
        System.out.println("Arrival Time " + flight6.arrivalTime);
        System.out.println("Rating " + flight6.rating);
        System.out.println("Contact Number " + flight6.contactNumber);
        System.out.println("Email ID " + flight6.email);
        System.out.println("Departure City " + flight6.departureCity);
        System.out.println("Destination State " + flight6.destinationState);
        System.out.println("Destination Country " + flight6.destinationCountry);
        System.out.println("Manufacture Year " + flight6.manufactureYear);
        System.out.println("Lounge Access " + flight6.loungeAccess);
        System.out.println("Entertainment Available " + flight6.entertainmentAvailable);
        System.out.println("Flight Code " + flight6.flightCode);
        System.out.println("Website " + flight6.website);
        System.out.println("Frequent Flyer Available " + flight6.frequentFlyerAvailable);


        Flight flight7 = new Flight();

        System.out.println("Before Initialization of Flight7");
        System.out.println("Flight ID is " + flight7.flightId);
        System.out.println("Airline is " + flight7.airlineName);
        System.out.println("Source is " + flight7.source);
        System.out.println("Total Seats are " + flight7.totalSeats);
        System.out.println("Crew Count is " + flight7.crewCount);
        System.out.println("Wifi Available " + flight7.hasWifi);
        System.out.println("Business Class Available " + flight7.hasBusinessClass);
        System.out.println("First Class Available " + flight7.hasFirstClass);
        System.out.println("Meals Available " + flight7.hasMeals);
        System.out.println("Is International " + flight7.isInternational);
        System.out.println("Pilot Name " + flight7.pilotName);
        System.out.println("Departure Time " + flight7.departureTime);
        System.out.println("Arrival Time " + flight7.arrivalTime);
        System.out.println("Rating " + flight7.rating);
        System.out.println("Contact Number " + flight7.contactNumber);
        System.out.println("Email ID " + flight7.email);
        System.out.println("Departure City " + flight7.departureCity);
        System.out.println("Destination State " + flight7.destinationState);
        System.out.println("Destination Country " + flight7.destinationCountry);
        System.out.println("Manufacture Year " + flight7.manufactureYear);
        System.out.println("Lounge Access " + flight7.loungeAccess);
        System.out.println("Entertainment Available " + flight7.entertainmentAvailable);
        System.out.println("Flight Code " + flight7.flightCode);
        System.out.println("Website " + flight7.website);
        System.out.println("Frequent Flyer Available " + flight7.frequentFlyerAvailable);

        flight7.flightId = 7;
        flight7.airlineName = "IT City Express";
        flight7.source = "Pune";
        flight7.totalSeats = 190;
        flight7.crewCount = 8;
        flight7.hasWifi = true;
        flight7.hasBusinessClass = true;
        flight7.hasFirstClass = false;
        flight7.hasMeals = true;
        flight7.isInternational = false;
        flight7.pilotName = "Capt. Joshi";
        flight7.departureTime = "7AM";
        flight7.arrivalTime = "8:20AM";
        flight7.rating = 4.4;
        flight7.contactNumber = "1800223344";
        flight7.email = "fly@itcity.com";
        flight7.departureCity = "Pune";
        flight7.destinationState = "Karnataka";
        flight7.destinationCountry = "India";
        flight7.manufactureYear = 2021;
        flight7.loungeAccess = true;
        flight7.entertainmentAvailable = true;
        flight7.flightCode = "IT707";
        flight7.website = "www.itcityexpress.com";
        flight7.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight7");
        System.out.println("Flight ID is " + flight7.flightId);
        System.out.println("Airline is " + flight7.airlineName);
        System.out.println("Source is " + flight7.source);
        System.out.println("Total Seats are " + flight7.totalSeats);
        System.out.println("Crew Count is " + flight7.crewCount);
        System.out.println("Wifi Available " + flight7.hasWifi);
        System.out.println("Business Class Available " + flight7.hasBusinessClass);
        System.out.println("First Class Available " + flight7.hasFirstClass);
        System.out.println("Meals Available " + flight7.hasMeals);
        System.out.println("Is International " + flight7.isInternational);
        System.out.println("Pilot Name " + flight7.pilotName);
        System.out.println("Departure Time " + flight7.departureTime);
        System.out.println("Arrival Time " + flight7.arrivalTime);
        System.out.println("Rating " + flight7.rating);
        System.out.println("Contact Number " + flight7.contactNumber);
        System.out.println("Email ID " + flight7.email);
        System.out.println("Departure City " + flight7.departureCity);
        System.out.println("Destination State " + flight7.destinationState);
        System.out.println("Destination Country " + flight7.destinationCountry);
        System.out.println("Manufacture Year " + flight7.manufactureYear);
        System.out.println("Lounge Access " + flight7.loungeAccess);
        System.out.println("Entertainment Available " + flight7.entertainmentAvailable);
        System.out.println("Flight Code " + flight7.flightCode);
        System.out.println("Website " + flight7.website);
        System.out.println("Frequent Flyer Available " + flight7.frequentFlyerAvailable);


        Flight flight8 = new Flight();

        System.out.println("Before Initialization of Flight8");
        System.out.println("Flight ID is " + flight8.flightId);
        System.out.println("Airline is " + flight8.airlineName);
        System.out.println("Source is " + flight8.source);
        System.out.println("Total Seats are " + flight8.totalSeats);
        System.out.println("Crew Count is " + flight8.crewCount);
        System.out.println("Wifi Available " + flight8.hasWifi);
        System.out.println("Business Class Available " + flight8.hasBusinessClass);
        System.out.println("First Class Available " + flight8.hasFirstClass);
        System.out.println("Meals Available " + flight8.hasMeals);
        System.out.println("Is International " + flight8.isInternational);
        System.out.println("Pilot Name " + flight8.pilotName);
        System.out.println("Departure Time " + flight8.departureTime);
        System.out.println("Arrival Time " + flight8.arrivalTime);
        System.out.println("Rating " + flight8.rating);
        System.out.println("Contact Number " + flight8.contactNumber);
        System.out.println("Email ID " + flight8.email);
        System.out.println("Departure City " + flight8.departureCity);
        System.out.println("Destination State " + flight8.destinationState);
        System.out.println("Destination Country " + flight8.destinationCountry);
        System.out.println("Manufacture Year " + flight8.manufactureYear);
        System.out.println("Lounge Access " + flight8.loungeAccess);
        System.out.println("Entertainment Available " + flight8.entertainmentAvailable);
        System.out.println("Flight Code " + flight8.flightCode);
        System.out.println("Website " + flight8.website);
        System.out.println("Frequent Flyer Available " + flight8.frequentFlyerAvailable);

        flight8.flightId = 8;
        flight8.airlineName = "Royal Air";
        flight8.source = "Lucknow";
        flight8.totalSeats = 140;
        flight8.crewCount = 6;
        flight8.hasWifi = false;
        flight8.hasBusinessClass = false;
        flight8.hasFirstClass = false;
        flight8.hasMeals = true;
        flight8.isInternational = false;
        flight8.pilotName = "Capt. Mishra";
        flight8.departureTime = "10AM";
        flight8.arrivalTime = "11:15AM";
        flight8.rating = 3.8;
        flight8.contactNumber = "1800556677";
        flight8.email = "help@royalair.com";
        flight8.departureCity = "Lucknow";
        flight8.destinationState = "Rajasthan";
        flight8.destinationCountry = "India";
        flight8.manufactureYear = 2013;
        flight8.loungeAccess = false;
        flight8.entertainmentAvailable = false;
        flight8.flightCode = "RA808";
        flight8.website = "www.royalair.com";
        flight8.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight8");
        System.out.println("Flight ID is " + flight8.flightId);
        System.out.println("Airline is " + flight8.airlineName);
        System.out.println("Source is " + flight8.source);
        System.out.println("Total Seats are " + flight8.totalSeats);
        System.out.println("Crew Count is " + flight8.crewCount);
        System.out.println("Wifi Available " + flight8.hasWifi);
        System.out.println("Business Class Available " + flight8.hasBusinessClass);
        System.out.println("First Class Available " + flight8.hasFirstClass);
        System.out.println("Meals Available " + flight8.hasMeals);
        System.out.println("Is International " + flight8.isInternational);
        System.out.println("Pilot Name " + flight8.pilotName);
        System.out.println("Departure Time " + flight8.departureTime);
        System.out.println("Arrival Time " + flight8.arrivalTime);
        System.out.println("Rating " + flight8.rating);
        System.out.println("Contact Number " + flight8.contactNumber);
        System.out.println("Email ID " + flight8.email);
        System.out.println("Departure City " + flight8.departureCity);
        System.out.println("Destination State " + flight8.destinationState);
        System.out.println("Destination Country " + flight8.destinationCountry);
        System.out.println("Manufacture Year " + flight8.manufactureYear);
        System.out.println("Lounge Access " + flight8.loungeAccess);
        System.out.println("Entertainment Available " + flight8.entertainmentAvailable);
        System.out.println("Flight Code " + flight8.flightCode);
        System.out.println("Website " + flight8.website);
        System.out.println("Frequent Flyer Available " + flight8.frequentFlyerAvailable);


        Flight flight9 = new Flight();

        System.out.println("Before Initialization of Flight9");
        System.out.println("Flight ID is " + flight9.flightId);
        System.out.println("Airline is " + flight9.airlineName);
        System.out.println("Source is " + flight9.source);
        System.out.println("Total Seats are " + flight9.totalSeats);
        System.out.println("Crew Count is " + flight9.crewCount);
        System.out.println("Wifi Available " + flight9.hasWifi);
        System.out.println("Business Class Available " + flight9.hasBusinessClass);
        System.out.println("First Class Available " + flight9.hasFirstClass);
        System.out.println("Meals Available " + flight9.hasMeals);
        System.out.println("Is International " + flight9.isInternational);
        System.out.println("Pilot Name " + flight9.pilotName);
        System.out.println("Departure Time " + flight9.departureTime);
        System.out.println("Arrival Time " + flight9.arrivalTime);
        System.out.println("Rating " + flight9.rating);
        System.out.println("Contact Number " + flight9.contactNumber);
        System.out.println("Email ID " + flight9.email);
        System.out.println("Departure City " + flight9.departureCity);
        System.out.println("Destination State " + flight9.destinationState);
        System.out.println("Destination Country " + flight9.destinationCountry);
        System.out.println("Manufacture Year " + flight9.manufactureYear);
        System.out.println("Lounge Access " + flight9.loungeAccess);
        System.out.println("Entertainment Available " + flight9.entertainmentAvailable);
        System.out.println("Flight Code " + flight9.flightCode);
        System.out.println("Website " + flight9.website);
        System.out.println("Frequent Flyer Available " + flight9.frequentFlyerAvailable);

        flight9.flightId = 9;
        flight9.airlineName = "Coastal Flights";
        flight9.source = "Goa";
        flight9.totalSeats = 180;
        flight9.crewCount = 8;
        flight9.hasWifi = true;
        flight9.hasBusinessClass = true;
        flight9.hasFirstClass = false;
        flight9.hasMeals = true;
        flight9.isInternational = false;
        flight9.pilotName = "Capt. Dsouza";
        flight9.departureTime = "4PM";
        flight9.arrivalTime = "5:15PM";
        flight9.rating = 4.6;
        flight9.contactNumber = "1800667788";
        flight9.email = "bookings@coastal.com";
        flight9.departureCity = "Goa";
        flight9.destinationState = "Maharashtra";
        flight9.destinationCountry = "India";
        flight9.manufactureYear = 2022;
        flight9.loungeAccess = true;
        flight9.entertainmentAvailable = true;
        flight9.flightCode = "CF909";
        flight9.website = "www.coastalflights.com";
        flight9.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight9");
        System.out.println("Flight ID is " + flight9.flightId);
        System.out.println("Airline is " + flight9.airlineName);
        System.out.println("Source is " + flight9.source);
        System.out.println("Total Seats are " + flight9.totalSeats);
        System.out.println("Crew Count is " + flight9.crewCount);
        System.out.println("Wifi Available " + flight9.hasWifi);
        System.out.println("Business Class Available " + flight9.hasBusinessClass);
        System.out.println("First Class Available " + flight9.hasFirstClass);
        System.out.println("Meals Available " + flight9.hasMeals);
        System.out.println("Is International " + flight9.isInternational);
        System.out.println("Pilot Name " + flight9.pilotName);
        System.out.println("Departure Time " + flight9.departureTime);
        System.out.println("Arrival Time " + flight9.arrivalTime);
        System.out.println("Rating " + flight9.rating);
        System.out.println("Contact Number " + flight9.contactNumber);
        System.out.println("Email ID " + flight9.email);
        System.out.println("Departure City " + flight9.departureCity);
        System.out.println("Destination State " + flight9.destinationState);
        System.out.println("Destination Country " + flight9.destinationCountry);
        System.out.println("Manufacture Year " + flight9.manufactureYear);
        System.out.println("Lounge Access " + flight9.loungeAccess);
        System.out.println("Entertainment Available " + flight9.entertainmentAvailable);
        System.out.println("Flight Code " + flight9.flightCode);
        System.out.println("Website " + flight9.website);
        System.out.println("Frequent Flyer Available " + flight9.frequentFlyerAvailable);


        Flight flight10 = new Flight();

        System.out.println("Before Initialization of Flight10");
        System.out.println("Flight ID is " + flight10.flightId);
        System.out.println("Airline is " + flight10.airlineName);
        System.out.println("Source is " + flight10.source);
        System.out.println("Total Seats are " + flight10.totalSeats);
        System.out.println("Crew Count is " + flight10.crewCount);
        System.out.println("Wifi Available " + flight10.hasWifi);
        System.out.println("Business Class Available " + flight10.hasBusinessClass);
        System.out.println("First Class Available " + flight10.hasFirstClass);
        System.out.println("Meals Available " + flight10.hasMeals);
        System.out.println("Is International " + flight10.isInternational);
        System.out.println("Pilot Name " + flight10.pilotName);
        System.out.println("Departure Time " + flight10.departureTime);
        System.out.println("Arrival Time " + flight10.arrivalTime);
        System.out.println("Rating " + flight10.rating);
        System.out.println("Contact Number " + flight10.contactNumber);
        System.out.println("Email ID " + flight10.email);
        System.out.println("Departure City " + flight10.departureCity);
        System.out.println("Destination State " + flight10.destinationState);
        System.out.println("Destination Country " + flight10.destinationCountry);
        System.out.println("Manufacture Year " + flight10.manufactureYear);
        System.out.println("Lounge Access " + flight10.loungeAccess);
        System.out.println("Entertainment Available " + flight10.entertainmentAvailable);
        System.out.println("Flight Code " + flight10.flightCode);
        System.out.println("Website " + flight10.website);
        System.out.println("Frequent Flyer Available " + flight10.frequentFlyerAvailable);

        flight10.flightId = 10;
        flight10.airlineName = "Metro Air";
        flight10.source = "Hyderabad";
        flight10.totalSeats = 250;
        flight10.crewCount = 12;
        flight10.hasWifi = true;
        flight10.hasBusinessClass = true;
        flight10.hasFirstClass = true;
        flight10.hasMeals = true;
        flight10.isInternational = false;
        flight10.pilotName = "Capt. Ali";
        flight10.departureTime = "8AM";
        flight10.arrivalTime = "9:30AM";
        flight10.rating = 4.7;
        flight10.contactNumber = "1800102030";
        flight10.email = "service@metroair.com";
        flight10.departureCity = "Hyderabad";
        flight10.destinationState = "Tamil Nadu";
        flight10.destinationCountry = "India";
        flight10.manufactureYear = 2023;
        flight10.loungeAccess = true;
        flight10.entertainmentAvailable = true;
        flight10.flightCode = "MA1010";
        flight10.website = "www.metroair.com";
        flight10.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight10");
        System.out.println("Flight ID is " + flight10.flightId);
        System.out.println("Airline is " + flight10.airlineName);
        System.out.println("Source is " + flight10.source);
        System.out.println("Total Seats are " + flight10.totalSeats);
        System.out.println("Crew Count is " + flight10.crewCount);
        System.out.println("Wifi Available " + flight10.hasWifi);
        System.out.println("Business Class Available " + flight10.hasBusinessClass);
        System.out.println("First Class Available " + flight10.hasFirstClass);
        System.out.println("Meals Available " + flight10.hasMeals);
        System.out.println("Is International " + flight10.isInternational);
        System.out.println("Pilot Name " + flight10.pilotName);
        System.out.println("Departure Time " + flight10.departureTime);
        System.out.println("Arrival Time " + flight10.arrivalTime);
        System.out.println("Rating " + flight10.rating);
        System.out.println("Contact Number " + flight10.contactNumber);
        System.out.println("Email ID " + flight10.email);
        System.out.println("Departure City " + flight10.departureCity);
        System.out.println("Destination State " + flight10.destinationState);
        System.out.println("Destination Country " + flight10.destinationCountry);
        System.out.println("Manufacture Year " + flight10.manufactureYear);
        System.out.println("Lounge Access " + flight10.loungeAccess);
        System.out.println("Entertainment Available " + flight10.entertainmentAvailable);
        System.out.println("Flight Code " + flight10.flightCode);
        System.out.println("Website " + flight10.website);
        System.out.println("Frequent Flyer Available " + flight10.frequentFlyerAvailable);


        Flight flight11 = new Flight();

        System.out.println("Before Initialization of Flight11");
        System.out.println("Flight ID is " + flight11.flightId);
        System.out.println("Airline is " + flight11.airlineName);
        System.out.println("Source is " + flight11.source);
        System.out.println("Total Seats are " + flight11.totalSeats);
        System.out.println("Crew Count is " + flight11.crewCount);
        System.out.println("Wifi Available " + flight11.hasWifi);
        System.out.println("Business Class Available " + flight11.hasBusinessClass);
        System.out.println("First Class Available " + flight11.hasFirstClass);
        System.out.println("Meals Available " + flight11.hasMeals);
        System.out.println("Is International " + flight11.isInternational);
        System.out.println("Pilot Name " + flight11.pilotName);
        System.out.println("Departure Time " + flight11.departureTime);
        System.out.println("Arrival Time " + flight11.arrivalTime);
        System.out.println("Rating " + flight11.rating);
        System.out.println("Contact Number " + flight11.contactNumber);
        System.out.println("Email ID " + flight11.email);
        System.out.println("Departure City " + flight11.departureCity);
        System.out.println("Destination State " + flight11.destinationState);
        System.out.println("Destination Country " + flight11.destinationCountry);
        System.out.println("Manufacture Year " + flight11.manufactureYear);
        System.out.println("Lounge Access " + flight11.loungeAccess);
        System.out.println("Entertainment Available " + flight11.entertainmentAvailable);
        System.out.println("Flight Code " + flight11.flightCode);
        System.out.println("Website " + flight11.website);
        System.out.println("Frequent Flyer Available " + flight11.frequentFlyerAvailable);

        flight11.flightId = 11;
        flight11.airlineName = "Capital Connect";
        flight11.source = "Delhi";
        flight11.totalSeats = 130;
        flight11.crewCount = 5;
        flight11.hasWifi = false;
        flight11.hasBusinessClass = false;
        flight11.hasFirstClass = false;
        flight11.hasMeals = true;
        flight11.isInternational = false;
        flight11.pilotName = "Capt. Kaur";
        flight11.departureTime = "6:30AM";
        flight11.arrivalTime = "7:45AM";
        flight11.rating = 4.0;
        flight11.contactNumber = "1800203040";
        flight11.email = "fly@capitalconnect.com";
        flight11.departureCity = "Delhi";
        flight11.destinationState = "Punjab";
        flight11.destinationCountry = "India";
        flight11.manufactureYear = 2016;
        flight11.loungeAccess = false;
        flight11.entertainmentAvailable = false;
        flight11.flightCode = "CC111";
        flight11.website = "www.capitalconnect.com";
        flight11.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight11");
        System.out.println("Flight ID is " + flight11.flightId);
        System.out.println("Airline is " + flight11.airlineName);
        System.out.println("Source is " + flight11.source);
        System.out.println("Total Seats are " + flight11.totalSeats);
        System.out.println("Crew Count is " + flight11.crewCount);
        System.out.println("Wifi Available " + flight11.hasWifi);
        System.out.println("Business Class Available " + flight11.hasBusinessClass);
        System.out.println("First Class Available " + flight11.hasFirstClass);
        System.out.println("Meals Available " + flight11.hasMeals);
        System.out.println("Is International " + flight11.isInternational);
        System.out.println("Pilot Name " + flight11.pilotName);
        System.out.println("Departure Time " + flight11.departureTime);
        System.out.println("Arrival Time " + flight11.arrivalTime);
        System.out.println("Rating " + flight11.rating);
        System.out.println("Contact Number " + flight11.contactNumber);
        System.out.println("Email ID " + flight11.email);
        System.out.println("Departure City " + flight11.departureCity);
        System.out.println("Destination State " + flight11.destinationState);
        System.out.println("Destination Country " + flight11.destinationCountry);
        System.out.println("Manufacture Year " + flight11.manufactureYear);
        System.out.println("Lounge Access " + flight11.loungeAccess);
        System.out.println("Entertainment Available " + flight11.entertainmentAvailable);
        System.out.println("Flight Code " + flight11.flightCode);
        System.out.println("Website " + flight11.website);
        System.out.println("Frequent Flyer Available " + flight11.frequentFlyerAvailable);


        Flight flight12 = new Flight();

        System.out.println("Before Initialization of Flight12");
        System.out.println("Flight ID is " + flight12.flightId);
        System.out.println("Airline is " + flight12.airlineName);
        System.out.println("Source is " + flight12.source);
        System.out.println("Total Seats are " + flight12.totalSeats);
        System.out.println("Crew Count is " + flight12.crewCount);
        System.out.println("Wifi Available " + flight12.hasWifi);
        System.out.println("Business Class Available " + flight12.hasBusinessClass);
        System.out.println("First Class Available " + flight12.hasFirstClass);
        System.out.println("Meals Available " + flight12.hasMeals);
        System.out.println("Is International " + flight12.isInternational);
        System.out.println("Pilot Name " + flight12.pilotName);
        System.out.println("Departure Time " + flight12.departureTime);
        System.out.println("Arrival Time " + flight12.arrivalTime);
        System.out.println("Rating " + flight12.rating);
        System.out.println("Contact Number " + flight12.contactNumber);
        System.out.println("Email ID " + flight12.email);
        System.out.println("Departure City " + flight12.departureCity);
        System.out.println("Destination State " + flight12.destinationState);
        System.out.println("Destination Country " + flight12.destinationCountry);
        System.out.println("Manufacture Year " + flight12.manufactureYear);
        System.out.println("Lounge Access " + flight12.loungeAccess);
        System.out.println("Entertainment Available " + flight12.entertainmentAvailable);
        System.out.println("Flight Code " + flight12.flightCode);
        System.out.println("Website " + flight12.website);
        System.out.println("Frequent Flyer Available " + flight12.frequentFlyerAvailable);

        flight12.flightId = 12;
        flight12.airlineName = "Southern Sky";
        flight12.source = "Kochi";
        flight12.totalSeats = 175;
        flight12.crewCount = 7;
        flight12.hasWifi = true;
        flight12.hasBusinessClass = true;
        flight12.hasFirstClass = false;
        flight12.hasMeals = true;
        flight12.isInternational = false;
        flight12.pilotName = "Capt. Menon";
        flight12.departureTime = "12PM";
        flight12.arrivalTime = "1:10PM";
        flight12.rating = 4.3;
        flight12.contactNumber = "1800304050";
        flight12.email = "hello@southernsky.com";
        flight12.departureCity = "Kochi";
        flight12.destinationState = "Tamil Nadu";
        flight12.destinationCountry = "India";
        flight12.manufactureYear = 2018;
        flight12.loungeAccess = true;
        flight12.entertainmentAvailable = true;
        flight12.flightCode = "SS122";
        flight12.website = "www.southernsky.com";
        flight12.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight12");
        System.out.println("Flight ID is " + flight12.flightId);
        System.out.println("Airline is " + flight12.airlineName);
        System.out.println("Source is " + flight12.source);
        System.out.println("Total Seats are " + flight12.totalSeats);
        System.out.println("Crew Count is " + flight12.crewCount);
        System.out.println("Wifi Available " + flight12.hasWifi);
        System.out.println("Business Class Available " + flight12.hasBusinessClass);
        System.out.println("First Class Available " + flight12.hasFirstClass);
        System.out.println("Meals Available " + flight12.hasMeals);
        System.out.println("Is International " + flight12.isInternational);
        System.out.println("Pilot Name " + flight12.pilotName);
        System.out.println("Departure Time " + flight12.departureTime);
        System.out.println("Arrival Time " + flight12.arrivalTime);
        System.out.println("Rating " + flight12.rating);
        System.out.println("Contact Number " + flight12.contactNumber);
        System.out.println("Email ID " + flight12.email);
        System.out.println("Departure City " + flight12.departureCity);
        System.out.println("Destination State " + flight12.destinationState);
        System.out.println("Destination Country " + flight12.destinationCountry);
        System.out.println("Manufacture Year " + flight12.manufactureYear);
        System.out.println("Lounge Access " + flight12.loungeAccess);
        System.out.println("Entertainment Available " + flight12.entertainmentAvailable);
        System.out.println("Flight Code " + flight12.flightCode);
        System.out.println("Website " + flight12.website);
        System.out.println("Frequent Flyer Available " + flight12.frequentFlyerAvailable);


        Flight flight13 = new Flight();

        System.out.println("Before Initialization of Flight13");
        System.out.println("Flight ID is " + flight13.flightId);
        System.out.println("Airline is " + flight13.airlineName);
        System.out.println("Source is " + flight13.source);
        System.out.println("Total Seats are " + flight13.totalSeats);
        System.out.println("Crew Count is " + flight13.crewCount);
        System.out.println("Wifi Available " + flight13.hasWifi);
        System.out.println("Business Class Available " + flight13.hasBusinessClass);
        System.out.println("First Class Available " + flight13.hasFirstClass);
        System.out.println("Meals Available " + flight13.hasMeals);
        System.out.println("Is International " + flight13.isInternational);
        System.out.println("Pilot Name " + flight13.pilotName);
        System.out.println("Departure Time " + flight13.departureTime);
        System.out.println("Arrival Time " + flight13.arrivalTime);
        System.out.println("Rating " + flight13.rating);
        System.out.println("Contact Number " + flight13.contactNumber);
        System.out.println("Email ID " + flight13.email);
        System.out.println("Departure City " + flight13.departureCity);
        System.out.println("Destination State " + flight13.destinationState);
        System.out.println("Destination Country " + flight13.destinationCountry);
        System.out.println("Manufacture Year " + flight13.manufactureYear);
        System.out.println("Lounge Access " + flight13.loungeAccess);
        System.out.println("Entertainment Available " + flight13.entertainmentAvailable);
        System.out.println("Flight Code " + flight13.flightCode);
        System.out.println("Website " + flight13.website);
        System.out.println("Frequent Flyer Available " + flight13.frequentFlyerAvailable);

        flight13.flightId = 13;
        flight13.airlineName = "Eastern Jet";
        flight13.source = "Patna";
        flight13.totalSeats = 110;
        flight13.crewCount = 5;
        flight13.hasWifi = false;
        flight13.hasBusinessClass = false;
        flight13.hasFirstClass = false;
        flight13.hasMeals = true;
        flight13.isInternational = false;
        flight13.pilotName = "Capt. Sinha";
        flight13.departureTime = "2PM";
        flight13.arrivalTime = "3:15PM";
        flight13.rating = 3.7;
        flight13.contactNumber = "1800405060";
        flight13.email = "info@easternjet.com";
        flight13.departureCity = "Patna";
        flight13.destinationState = "West Bengal";
        flight13.destinationCountry = "India";
        flight13.manufactureYear = 2012;
        flight13.loungeAccess = false;
        flight13.entertainmentAvailable = false;
        flight13.flightCode = "EJ133";
        flight13.website = "www.easternjet.com";
        flight13.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight13");
        System.out.println("Flight ID is " + flight13.flightId);
        System.out.println("Airline is " + flight13.airlineName);
        System.out.println("Source is " + flight13.source);
        System.out.println("Total Seats are " + flight13.totalSeats);
        System.out.println("Crew Count is " + flight13.crewCount);
        System.out.println("Wifi Available " + flight13.hasWifi);
        System.out.println("Business Class Available " + flight13.hasBusinessClass);
        System.out.println("First Class Available " + flight13.hasFirstClass);
        System.out.println("Meals Available " + flight13.hasMeals);
        System.out.println("Is International " + flight13.isInternational);
        System.out.println("Pilot Name " + flight13.pilotName);
        System.out.println("Departure Time " + flight13.departureTime);
        System.out.println("Arrival Time " + flight13.arrivalTime);
        System.out.println("Rating " + flight13.rating);
        System.out.println("Contact Number " + flight13.contactNumber);
        System.out.println("Email ID " + flight13.email);
        System.out.println("Departure City " + flight13.departureCity);
        System.out.println("Destination State " + flight13.destinationState);
        System.out.println("Destination Country " + flight13.destinationCountry);
        System.out.println("Manufacture Year " + flight13.manufactureYear);
        System.out.println("Lounge Access " + flight13.loungeAccess);
        System.out.println("Entertainment Available " + flight13.entertainmentAvailable);
        System.out.println("Flight Code " + flight13.flightCode);
        System.out.println("Website " + flight13.website);
        System.out.println("Frequent Flyer Available " + flight13.frequentFlyerAvailable);


        Flight flight14 = new Flight();

        System.out.println("Before Initialization of Flight14");
        System.out.println("Flight ID is " + flight14.flightId);
        System.out.println("Airline is " + flight14.airlineName);
        System.out.println("Source is " + flight14.source);
        System.out.println("Total Seats are " + flight14.totalSeats);
        System.out.println("Crew Count is " + flight14.crewCount);
        System.out.println("Wifi Available " + flight14.hasWifi);
        System.out.println("Business Class Available " + flight14.hasBusinessClass);
        System.out.println("First Class Available " + flight14.hasFirstClass);
        System.out.println("Meals Available " + flight14.hasMeals);
        System.out.println("Is International " + flight14.isInternational);
        System.out.println("Pilot Name " + flight14.pilotName);
        System.out.println("Departure Time " + flight14.departureTime);
        System.out.println("Arrival Time " + flight14.arrivalTime);
        System.out.println("Rating " + flight14.rating);
        System.out.println("Contact Number " + flight14.contactNumber);
        System.out.println("Email ID " + flight14.email);
        System.out.println("Departure City " + flight14.departureCity);
        System.out.println("Destination State " + flight14.destinationState);
        System.out.println("Destination Country " + flight14.destinationCountry);
        System.out.println("Manufacture Year " + flight14.manufactureYear);
        System.out.println("Lounge Access " + flight14.loungeAccess);
        System.out.println("Entertainment Available " + flight14.entertainmentAvailable);
        System.out.println("Flight Code " + flight14.flightCode);
        System.out.println("Website " + flight14.website);
        System.out.println("Frequent Flyer Available " + flight14.frequentFlyerAvailable);

        flight14.flightId = 14;
        flight14.airlineName = "Western Wings";
        flight14.source = "Ahmedabad";
        flight14.totalSeats = 190;
        flight14.crewCount = 8;
        flight14.hasWifi = true;
        flight14.hasBusinessClass = true;
        flight14.hasFirstClass = false;
        flight14.hasMeals = true;
        flight14.isInternational = false;
        flight14.pilotName = "Capt. Patel";
        flight14.departureTime = "8:45AM";
        flight14.arrivalTime = "10:00AM";
        flight14.rating = 4.2;
        flight14.contactNumber = "1800506070";
        flight14.email = "fly@westernwings.com";
        flight14.departureCity = "Ahmedabad";
        flight14.destinationState = "Maharashtra";
        flight14.destinationCountry = "India";
        flight14.manufactureYear = 2020;
        flight14.loungeAccess = true;
        flight14.entertainmentAvailable = false;
        flight14.flightCode = "WW144";
        flight14.website = "www.westernwings.com";
        flight14.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight14");
        System.out.println("Flight ID is " + flight14.flightId);
        System.out.println("Airline is " + flight14.airlineName);
        System.out.println("Source is " + flight14.source);
        System.out.println("Total Seats are " + flight14.totalSeats);
        System.out.println("Crew Count is " + flight14.crewCount);
        System.out.println("Wifi Available " + flight14.hasWifi);
        System.out.println("Business Class Available " + flight14.hasBusinessClass);
        System.out.println("First Class Available " + flight14.hasFirstClass);
        System.out.println("Meals Available " + flight14.hasMeals);
        System.out.println("Is International " + flight14.isInternational);
        System.out.println("Pilot Name " + flight14.pilotName);
        System.out.println("Departure Time " + flight14.departureTime);
        System.out.println("Arrival Time " + flight14.arrivalTime);
        System.out.println("Rating " + flight14.rating);
        System.out.println("Contact Number " + flight14.contactNumber);
        System.out.println("Email ID " + flight14.email);
        System.out.println("Departure City " + flight14.departureCity);
        System.out.println("Destination State " + flight14.destinationState);
        System.out.println("Destination Country " + flight14.destinationCountry);
        System.out.println("Manufacture Year " + flight14.manufactureYear);
        System.out.println("Lounge Access " + flight14.loungeAccess);
        System.out.println("Entertainment Available " + flight14.entertainmentAvailable);
        System.out.println("Flight Code " + flight14.flightCode);
        System.out.println("Website " + flight14.website);
        System.out.println("Frequent Flyer Available " + flight14.frequentFlyerAvailable);


        Flight flight15 = new Flight();

        System.out.println("Before Initialization of Flight15");
        System.out.println("Flight ID is " + flight15.flightId);
        System.out.println("Airline is " + flight15.airlineName);
        System.out.println("Source is " + flight15.source);
        System.out.println("Total Seats are " + flight15.totalSeats);
        System.out.println("Crew Count is " + flight15.crewCount);
        System.out.println("Wifi Available " + flight15.hasWifi);
        System.out.println("Business Class Available " + flight15.hasBusinessClass);
        System.out.println("First Class Available " + flight15.hasFirstClass);
        System.out.println("Meals Available " + flight15.hasMeals);
        System.out.println("Is International " + flight15.isInternational);
        System.out.println("Pilot Name " + flight15.pilotName);
        System.out.println("Departure Time " + flight15.departureTime);
        System.out.println("Arrival Time " + flight15.arrivalTime);
        System.out.println("Rating " + flight15.rating);
        System.out.println("Contact Number " + flight15.contactNumber);
        System.out.println("Email ID " + flight15.email);
        System.out.println("Departure City " + flight15.departureCity);
        System.out.println("Destination State " + flight15.destinationState);
        System.out.println("Destination Country " + flight15.destinationCountry);
        System.out.println("Manufacture Year " + flight15.manufactureYear);
        System.out.println("Lounge Access " + flight15.loungeAccess);
        System.out.println("Entertainment Available " + flight15.entertainmentAvailable);
        System.out.println("Flight Code " + flight15.flightCode);
        System.out.println("Website " + flight15.website);
        System.out.println("Frequent Flyer Available " + flight15.frequentFlyerAvailable);

        flight15.flightId = 15;
        flight15.airlineName = "Central Air";
        flight15.source = "Bhopal";
        flight15.totalSeats = 140;
        flight15.crewCount = 6;
        flight15.hasWifi = false;
        flight15.hasBusinessClass = true;
        flight15.hasFirstClass = false;
        flight15.hasMeals = true;
        flight15.isInternational = false;
        flight15.pilotName = "Capt. Jain";
        flight15.departureTime = "7:30AM";
        flight15.arrivalTime = "8:45AM";
        flight15.rating = 4.1;
        flight15.contactNumber = "1800607080";
        flight15.email = "contact@centralair.com";
        flight15.departureCity = "Bhopal";
        flight15.destinationState = "Delhi";
        flight15.destinationCountry = "India";
        flight15.manufactureYear = 2017;
        flight15.loungeAccess = true;
        flight15.entertainmentAvailable = false;
        flight15.flightCode = "CA155";
        flight15.website = "www.centralair.com";
        flight15.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight15");
        System.out.println("Flight ID is " + flight15.flightId);
        System.out.println("Airline is " + flight15.airlineName);
        System.out.println("Source is " + flight15.source);
        System.out.println("Total Seats are " + flight15.totalSeats);
        System.out.println("Crew Count is " + flight15.crewCount);
        System.out.println("Wifi Available " + flight15.hasWifi);
        System.out.println("Business Class Available " + flight15.hasBusinessClass);
        System.out.println("First Class Available " + flight15.hasFirstClass);
        System.out.println("Meals Available " + flight15.hasMeals);
        System.out.println("Is International " + flight15.isInternational);
        System.out.println("Pilot Name " + flight15.pilotName);
        System.out.println("Departure Time " + flight15.departureTime);
        System.out.println("Arrival Time " + flight15.arrivalTime);
        System.out.println("Rating " + flight15.rating);
        System.out.println("Contact Number " + flight15.contactNumber);
        System.out.println("Email ID " + flight15.email);
        System.out.println("Departure City " + flight15.departureCity);
        System.out.println("Destination State " + flight15.destinationState);
        System.out.println("Destination Country " + flight15.destinationCountry);
        System.out.println("Manufacture Year " + flight15.manufactureYear);
        System.out.println("Lounge Access " + flight15.loungeAccess);
        System.out.println("Entertainment Available " + flight15.entertainmentAvailable);
        System.out.println("Flight Code " + flight15.flightCode);
        System.out.println("Website " + flight15.website);
        System.out.println("Frequent Flyer Available " + flight15.frequentFlyerAvailable);


        Flight flight16 = new Flight();

        System.out.println("Before Initialization of Flight16");
        System.out.println("Flight ID is " + flight16.flightId);
        System.out.println("Airline is " + flight16.airlineName);
        System.out.println("Source is " + flight16.source);
        System.out.println("Total Seats are " + flight16.totalSeats);
        System.out.println("Crew Count is " + flight16.crewCount);
        System.out.println("Wifi Available " + flight16.hasWifi);
        System.out.println("Business Class Available " + flight16.hasBusinessClass);
        System.out.println("First Class Available " + flight16.hasFirstClass);
        System.out.println("Meals Available " + flight16.hasMeals);
        System.out.println("Is International " + flight16.isInternational);
        System.out.println("Pilot Name " + flight16.pilotName);
        System.out.println("Departure Time " + flight16.departureTime);
        System.out.println("Arrival Time " + flight16.arrivalTime);
        System.out.println("Rating " + flight16.rating);
        System.out.println("Contact Number " + flight16.contactNumber);
        System.out.println("Email ID " + flight16.email);
        System.out.println("Departure City " + flight16.departureCity);
        System.out.println("Destination State " + flight16.destinationState);
        System.out.println("Destination Country " + flight16.destinationCountry);
        System.out.println("Manufacture Year " + flight16.manufactureYear);
        System.out.println("Lounge Access " + flight16.loungeAccess);
        System.out.println("Entertainment Available " + flight16.entertainmentAvailable);
        System.out.println("Flight Code " + flight16.flightCode);
        System.out.println("Website " + flight16.website);
        System.out.println("Frequent Flyer Available " + flight16.frequentFlyerAvailable);

        flight16.flightId = 16;
        flight16.airlineName = "Northern Star";
        flight16.source = "Srinagar";
        flight16.totalSeats = 100;
        flight16.crewCount = 5;
        flight16.hasWifi = false;
        flight16.hasBusinessClass = false;
        flight16.hasFirstClass = false;
        flight16.hasMeals = true;
        flight16.isInternational = false;
        flight16.pilotName = "Capt. Dar";
        flight16.departureTime = "10:00AM";
        flight16.arrivalTime = "11:30AM";
        flight16.rating = 4.0;
        flight16.contactNumber = "1800708090";
        flight16.email = "hello@northernstar.com";
        flight16.departureCity = "Srinagar";
        flight16.destinationState = "Delhi";
        flight16.destinationCountry = "India";
        flight16.manufactureYear = 2011;
        flight16.loungeAccess = false;
        flight16.entertainmentAvailable = false;
        flight16.flightCode = "NS166";
        flight16.website = "www.northernstar.com";
        flight16.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight16");
        System.out.println("Flight ID is " + flight16.flightId);
        System.out.println("Airline is " + flight16.airlineName);
        System.out.println("Source is " + flight16.source);
        System.out.println("Total Seats are " + flight16.totalSeats);
        System.out.println("Crew Count is " + flight16.crewCount);
        System.out.println("Wifi Available " + flight16.hasWifi);
        System.out.println("Business Class Available " + flight16.hasBusinessClass);
        System.out.println("First Class Available " + flight16.hasFirstClass);
        System.out.println("Meals Available " + flight16.hasMeals);
        System.out.println("Is International " + flight16.isInternational);
        System.out.println("Pilot Name " + flight16.pilotName);
        System.out.println("Departure Time " + flight16.departureTime);
        System.out.println("Arrival Time " + flight16.arrivalTime);
        System.out.println("Rating " + flight16.rating);
        System.out.println("Contact Number " + flight16.contactNumber);
        System.out.println("Email ID " + flight16.email);
        System.out.println("Departure City " + flight16.departureCity);
        System.out.println("Destination State " + flight16.destinationState);
        System.out.println("Destination Country " + flight16.destinationCountry);
        System.out.println("Manufacture Year " + flight16.manufactureYear);
        System.out.println("Lounge Access " + flight16.loungeAccess);
        System.out.println("Entertainment Available " + flight16.entertainmentAvailable);
        System.out.println("Flight Code " + flight16.flightCode);
        System.out.println("Website " + flight16.website);
        System.out.println("Frequent Flyer Available " + flight16.frequentFlyerAvailable);


        Flight flight17 = new Flight();

        System.out.println("Before Initialization of Flight17");
        System.out.println("Flight ID is " + flight17.flightId);
        System.out.println("Airline is " + flight17.airlineName);
        System.out.println("Source is " + flight17.source);
        System.out.println("Total Seats are " + flight17.totalSeats);
        System.out.println("Crew Count is " + flight17.crewCount);
        System.out.println("Wifi Available " + flight17.hasWifi);
        System.out.println("Business Class Available " + flight17.hasBusinessClass);
        System.out.println("First Class Available " + flight17.hasFirstClass);
        System.out.println("Meals Available " + flight17.hasMeals);
        System.out.println("Is International " + flight17.isInternational);
        System.out.println("Pilot Name " + flight17.pilotName);
        System.out.println("Departure Time " + flight17.departureTime);
        System.out.println("Arrival Time " + flight17.arrivalTime);
        System.out.println("Rating " + flight17.rating);
        System.out.println("Contact Number " + flight17.contactNumber);
        System.out.println("Email ID " + flight17.email);
        System.out.println("Departure City " + flight17.departureCity);
        System.out.println("Destination State " + flight17.destinationState);
        System.out.println("Destination Country " + flight17.destinationCountry);
        System.out.println("Manufacture Year " + flight17.manufactureYear);
        System.out.println("Lounge Access " + flight17.loungeAccess);
        System.out.println("Entertainment Available " + flight17.entertainmentAvailable);
        System.out.println("Flight Code " + flight17.flightCode);
        System.out.println("Website " + flight17.website);
        System.out.println("Frequent Flyer Available " + flight17.frequentFlyerAvailable);

        flight17.flightId = 17;
        flight17.airlineName = "Island Hopper";
        flight17.source = "Port Blair";
        flight17.totalSeats = 150;
        flight17.crewCount = 7;
        flight17.hasWifi = false;
        flight17.hasBusinessClass = true;
        flight17.hasFirstClass = false;
        flight17.hasMeals = true;
        flight17.isInternational = false;
        flight17.pilotName = "Capt. Biswas";
        flight17.departureTime = "1:00PM";
        flight17.arrivalTime = "3:30PM";
        flight17.rating = 4.5;
        flight17.contactNumber = "1800809000";
        flight17.email = "fly@islandhopper.com";
        flight17.departureCity = "Port Blair";
        flight17.destinationState = "Tamil Nadu";
        flight17.destinationCountry = "India";
        flight17.manufactureYear = 2019;
        flight17.loungeAccess = false;
        flight17.entertainmentAvailable = true;
        flight17.flightCode = "IH177";
        flight17.website = "www.islandhopper.com";
        flight17.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight17");
        System.out.println("Flight ID is " + flight17.flightId);
        System.out.println("Airline is " + flight17.airlineName);
        System.out.println("Source is " + flight17.source);
        System.out.println("Total Seats are " + flight17.totalSeats);
        System.out.println("Crew Count is " + flight17.crewCount);
        System.out.println("Wifi Available " + flight17.hasWifi);
        System.out.println("Business Class Available " + flight17.hasBusinessClass);
        System.out.println("First Class Available " + flight17.hasFirstClass);
        System.out.println("Meals Available " + flight17.hasMeals);
        System.out.println("Is International " + flight17.isInternational);
        System.out.println("Pilot Name " + flight17.pilotName);
        System.out.println("Departure Time " + flight17.departureTime);
        System.out.println("Arrival Time " + flight17.arrivalTime);
        System.out.println("Rating " + flight17.rating);
        System.out.println("Contact Number " + flight17.contactNumber);
        System.out.println("Email ID " + flight17.email);
        System.out.println("Departure City " + flight17.departureCity);
        System.out.println("Destination State " + flight17.destinationState);
        System.out.println("Destination Country " + flight17.destinationCountry);
        System.out.println("Manufacture Year " + flight17.manufactureYear);
        System.out.println("Lounge Access " + flight17.loungeAccess);
        System.out.println("Entertainment Available " + flight17.entertainmentAvailable);
        System.out.println("Flight Code " + flight17.flightCode);
        System.out.println("Website " + flight17.website);
        System.out.println("Frequent Flyer Available " + flight17.frequentFlyerAvailable);


        Flight flight18 = new Flight();

        System.out.println("Before Initialization of Flight18");
        System.out.println("Flight ID is " + flight18.flightId);
        System.out.println("Airline is " + flight18.airlineName);
        System.out.println("Source is " + flight18.source);
        System.out.println("Total Seats are " + flight18.totalSeats);
        System.out.println("Crew Count is " + flight18.crewCount);
        System.out.println("Wifi Available " + flight18.hasWifi);
        System.out.println("Business Class Available " + flight18.hasBusinessClass);
        System.out.println("First Class Available " + flight18.hasFirstClass);
        System.out.println("Meals Available " + flight18.hasMeals);
        System.out.println("Is International " + flight18.isInternational);
        System.out.println("Pilot Name " + flight18.pilotName);
        System.out.println("Departure Time " + flight18.departureTime);
        System.out.println("Arrival Time " + flight18.arrivalTime);
        System.out.println("Rating " + flight18.rating);
        System.out.println("Contact Number " + flight18.contactNumber);
        System.out.println("Email ID " + flight18.email);
        System.out.println("Departure City " + flight18.departureCity);
        System.out.println("Destination State " + flight18.destinationState);
        System.out.println("Destination Country " + flight18.destinationCountry);
        System.out.println("Manufacture Year " + flight18.manufactureYear);
        System.out.println("Lounge Access " + flight18.loungeAccess);
        System.out.println("Entertainment Available " + flight18.entertainmentAvailable);
        System.out.println("Flight Code " + flight18.flightCode);
        System.out.println("Website " + flight18.website);
        System.out.println("Frequent Flyer Available " + flight18.frequentFlyerAvailable);

        flight18.flightId = 18;
        flight18.airlineName = "Temple Air";
        flight18.source = "Madurai";
        flight18.totalSeats = 120;
        flight18.crewCount = 5;
        flight18.hasWifi = false;
        flight18.hasBusinessClass = false;
        flight18.hasFirstClass = false;
        flight18.hasMeals = true;
        flight18.isInternational = false;
        flight18.pilotName = "Capt. Kumar";
        flight18.departureTime = "11:30AM";
        flight18.arrivalTime = "12:45PM";
        flight18.rating = 3.9;
        flight18.contactNumber = "1800900100";
        flight18.email = "info@templeair.com";
        flight18.departureCity = "Madurai";
        flight18.destinationState = "Karnataka";
        flight18.destinationCountry = "India";
        flight18.manufactureYear = 2014;
        flight18.loungeAccess = false;
        flight18.entertainmentAvailable = false;
        flight18.flightCode = "TA188";
        flight18.website = "www.templeair.com";
        flight18.frequentFlyerAvailable = false;

        System.out.println("After Initialization of Flight18");
        System.out.println("Flight ID is " + flight18.flightId);
        System.out.println("Airline is " + flight18.airlineName);
        System.out.println("Source is " + flight18.source);
        System.out.println("Total Seats are " + flight18.totalSeats);
        System.out.println("Crew Count is " + flight18.crewCount);
        System.out.println("Wifi Available " + flight18.hasWifi);
        System.out.println("Business Class Available " + flight18.hasBusinessClass);
        System.out.println("First Class Available " + flight18.hasFirstClass);
        System.out.println("Meals Available " + flight18.hasMeals);
        System.out.println("Is International " + flight18.isInternational);
        System.out.println("Pilot Name " + flight18.pilotName);
        System.out.println("Departure Time " + flight18.departureTime);
        System.out.println("Arrival Time " + flight18.arrivalTime);
        System.out.println("Rating " + flight18.rating);
        System.out.println("Contact Number " + flight18.contactNumber);
        System.out.println("Email ID " + flight18.email);
        System.out.println("Departure City " + flight18.departureCity);
        System.out.println("Destination State " + flight18.destinationState);
        System.out.println("Destination Country " + flight18.destinationCountry);
        System.out.println("Manufacture Year " + flight18.manufactureYear);
        System.out.println("Lounge Access " + flight18.loungeAccess);
        System.out.println("Entertainment Available " + flight18.entertainmentAvailable);
        System.out.println("Flight Code " + flight18.flightCode);
        System.out.println("Website " + flight18.website);
        System.out.println("Frequent Flyer Available " + flight18.frequentFlyerAvailable);


        Flight flight19 = new Flight();

        System.out.println("Before Initialization of Flight19");
        System.out.println("Flight ID is " + flight19.flightId);
        System.out.println("Airline is " + flight19.airlineName);
        System.out.println("Source is " + flight19.source);
        System.out.println("Total Seats are " + flight19.totalSeats);
        System.out.println("Crew Count is " + flight19.crewCount);
        System.out.println("Wifi Available " + flight19.hasWifi);
        System.out.println("Business Class Available " + flight19.hasBusinessClass);
        System.out.println("First Class Available " + flight19.hasFirstClass);
        System.out.println("Meals Available " + flight19.hasMeals);
        System.out.println("Is International " + flight19.isInternational);
        System.out.println("Pilot Name " + flight19.pilotName);
        System.out.println("Departure Time " + flight19.departureTime);
        System.out.println("Arrival Time " + flight19.arrivalTime);
        System.out.println("Rating " + flight19.rating);
        System.out.println("Contact Number " + flight19.contactNumber);
        System.out.println("Email ID " + flight19.email);
        System.out.println("Departure City " + flight19.departureCity);
        System.out.println("Destination State " + flight19.destinationState);
        System.out.println("Destination Country " + flight19.destinationCountry);
        System.out.println("Manufacture Year " + flight19.manufactureYear);
        System.out.println("Lounge Access " + flight19.loungeAccess);
        System.out.println("Entertainment Available " + flight19.entertainmentAvailable);
        System.out.println("Flight Code " + flight19.flightCode);
        System.out.println("Website " + flight19.website);
        System.out.println("Frequent Flyer Available " + flight19.frequentFlyerAvailable);

        flight19.flightId = 19;
        flight19.airlineName = "Safari Flights";
        flight19.source = "Nagpur";
        flight19.totalSeats = 150;
        flight19.crewCount = 7;
        flight19.hasWifi = true;
        flight19.hasBusinessClass = true;
        flight19.hasFirstClass = false;
        flight19.hasMeals = true;
        flight19.isInternational = false;
        flight19.pilotName = "Capt. Gadkari";
        flight19.departureTime = "9:00AM";
        flight19.arrivalTime = "10:20AM";
        flight19.rating = 4.2;
        flight19.contactNumber = "1800100200";
        flight19.email = "safari@flights.com";
        flight19.departureCity = "Nagpur";
        flight19.destinationState = "Madhya Pradesh";
        flight19.destinationCountry = "India";
        flight19.manufactureYear = 2021;
        flight19.loungeAccess = true;
        flight19.entertainmentAvailable = false;
        flight19.flightCode = "SF199";
        flight19.website = "www.safariflights.com";
        flight19.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight19");
        System.out.println("Flight ID is " + flight19.flightId);
        System.out.println("Airline is " + flight19.airlineName);
        System.out.println("Source is " + flight19.source);
        System.out.println("Total Seats are " + flight19.totalSeats);
        System.out.println("Crew Count is " + flight19.crewCount);
        System.out.println("Wifi Available " + flight19.hasWifi);
        System.out.println("Business Class Available " + flight19.hasBusinessClass);
        System.out.println("First Class Available " + flight19.hasFirstClass);
        System.out.println("Meals Available " + flight19.hasMeals);
        System.out.println("Is International " + flight19.isInternational);
        System.out.println("Pilot Name " + flight19.pilotName);
        System.out.println("Departure Time " + flight19.departureTime);
        System.out.println("Arrival Time " + flight19.arrivalTime);
        System.out.println("Rating " + flight19.rating);
        System.out.println("Contact Number " + flight19.contactNumber);
        System.out.println("Email ID " + flight19.email);
        System.out.println("Departure City " + flight19.departureCity);
        System.out.println("Destination State " + flight19.destinationState);
        System.out.println("Destination Country " + flight19.destinationCountry);
        System.out.println("Manufacture Year " + flight19.manufactureYear);
        System.out.println("Lounge Access " + flight19.loungeAccess);
        System.out.println("Entertainment Available " + flight19.entertainmentAvailable);
        System.out.println("Flight Code " + flight19.flightCode);
        System.out.println("Website " + flight19.website);
        System.out.println("Frequent Flyer Available " + flight19.frequentFlyerAvailable);


        Flight flight20 = new Flight();

        System.out.println("Before Initialization of Flight20");
        System.out.println("Flight ID is " + flight20.flightId);
        System.out.println("Airline is " + flight20.airlineName);
        System.out.println("Source is " + flight20.source);
        System.out.println("Total Seats are " + flight20.totalSeats);
        System.out.println("Crew Count is " + flight20.crewCount);
        System.out.println("Wifi Available " + flight20.hasWifi);
        System.out.println("Business Class Available " + flight20.hasBusinessClass);
        System.out.println("First Class Available " + flight20.hasFirstClass);
        System.out.println("Meals Available " + flight20.hasMeals);
        System.out.println("Is International " + flight20.isInternational);
        System.out.println("Pilot Name " + flight20.pilotName);
        System.out.println("Departure Time " + flight20.departureTime);
        System.out.println("Arrival Time " + flight20.arrivalTime);
        System.out.println("Rating " + flight20.rating);
        System.out.println("Contact Number " + flight20.contactNumber);
        System.out.println("Email ID " + flight20.email);
        System.out.println("Departure City " + flight20.departureCity);
        System.out.println("Destination State " + flight20.destinationState);
        System.out.println("Destination Country " + flight20.destinationCountry);
        System.out.println("Manufacture Year " + flight20.manufactureYear);
        System.out.println("Lounge Access " + flight20.loungeAccess);
        System.out.println("Entertainment Available " + flight20.entertainmentAvailable);
        System.out.println("Flight Code " + flight20.flightCode);
        System.out.println("Website " + flight20.website);
        System.out.println("Frequent Flyer Available " + flight20.frequentFlyerAvailable);

        flight20.flightId = 20;
        flight20.airlineName = "Heritage Air";
        flight20.source = "Agra";
        flight20.totalSeats = 160;
        flight20.crewCount = 7;
        flight20.hasWifi = true;
        flight20.hasBusinessClass = true;
        flight20.hasFirstClass = true;
        flight20.hasMeals = true;
        flight20.isInternational = false;
        flight20.pilotName = "Capt. Verma";
        flight20.departureTime = "4:00PM";
        flight20.arrivalTime = "5:00PM";
        flight20.rating = 4.8;
        flight20.contactNumber = "1800200300";
        flight20.email = "fly@heritageair.com";
        flight20.departureCity = "Agra";
        flight20.destinationState = "Uttar Pradesh";
        flight20.destinationCountry = "India";
        flight20.manufactureYear = 2022;
        flight20.loungeAccess = true;
        flight20.entertainmentAvailable = true;
        flight20.flightCode = "HA200";
        flight20.website = "www.heritageair.com";
        flight20.frequentFlyerAvailable = true;

        System.out.println("After Initialization of Flight20");
        System.out.println("Flight ID is " + flight20.flightId);
        System.out.println("Airline is " + flight20.airlineName);
        System.out.println("Source is " + flight20.source);
        System.out.println("Total Seats are " + flight20.totalSeats);
        System.out.println("Crew Count is " + flight20.crewCount);
        System.out.println("Wifi Available " + flight20.hasWifi);
        System.out.println("Business Class Available " + flight20.hasBusinessClass);
        System.out.println("First Class Available " + flight20.hasFirstClass);
        System.out.println("Meals Available " + flight20.hasMeals);
        System.out.println("Is International " + flight20.isInternational);
        System.out.println("Pilot Name " + flight20.pilotName);
        System.out.println("Departure Time " + flight20.departureTime);
        System.out.println("Arrival Time " + flight20.arrivalTime);
        System.out.println("Rating " + flight20.rating);
        System.out.println("Contact Number " + flight20.contactNumber);
        System.out.println("Email ID " + flight20.email);
        System.out.println("Departure City " + flight20.departureCity);
        System.out.println("Destination State " + flight20.destinationState);
        System.out.println("Destination Country " + flight20.destinationCountry);
        System.out.println("Manufacture Year " + flight20.manufactureYear);
        System.out.println("Lounge Access " + flight20.loungeAccess);
        System.out.println("Entertainment Available " + flight20.entertainmentAvailable);
        System.out.println("Flight Code " + flight20.flightCode);
        System.out.println("Website " + flight20.website);
        System.out.println("Frequent Flyer Available " + flight20.frequentFlyerAvailable);

    }
}