class HospitalExecutor {
    public static void main(String[] args){
        Hospital hospital1 = new Hospital();

        System.out.println("Before Initialization of Hospital1");

        System.out.println("Hospital ID is " + hospital1.hospitalId);
        System.out.println("Hospital Name is " + hospital1.hospitalName);
        System.out.println("Hospital Location is " + hospital1.location);
        System.out.println("Total Beds are " + hospital1.totalBeds);
        System.out.println("Staff Count is " + hospital1.staffCount);
        System.out.println("Emergency Available " + hospital1.hasEmergency);
        System.out.println("ICU Available " + hospital1.hasICU);
        System.out.println("Ambulance Available " + hospital1.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital1.hasPharmacy);
        System.out.println("Open 24x7 " + hospital1.open24x7);
        System.out.println("Chief Doctor Name " + hospital1.chiefDoctorName);
        System.out.println("Opening Time " + hospital1.openingTime);
        System.out.println("Closing Time " + hospital1.closingTime);
        System.out.println("Hospital Rating " + hospital1.rating);
        System.out.println("Contact Number " + hospital1.contactNumber);
        System.out.println("Email ID " + hospital1.email);
        System.out.println("City " + hospital1.city);
        System.out.println("State " + hospital1.state);
        System.out.println("Country " + hospital1.country);
        System.out.println("Established Year " + hospital1.establishedYear);
        System.out.println("Parking Available " + hospital1.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital1.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital1.hospitalCode);
        System.out.println("Website " + hospital1.website);
        System.out.println("Insurance Accepted " + hospital1.insuranceAccepted);

        hospital1.hospitalId = 1;
        hospital1.hospitalName = "City Care Hospital";
        hospital1.location = "Downtown";
        hospital1.totalBeds = 500;
        hospital1.staffCount = 150;
        hospital1.hasEmergency = true;
        hospital1.hasICU = true;
        hospital1.hasAmbulance = true;
        hospital1.hasPharmacy = true;
        hospital1.open24x7 = true;
        hospital1.chiefDoctorName = "Dr. Sharma";
        hospital1.openingTime = "12AM";
        hospital1.closingTime = "11PM";
        hospital1.rating = 4.8;
        hospital1.contactNumber = "9876543210";
        hospital1.email = "contact@citycare.com";
        hospital1.city = "Mumbai";
        hospital1.state = "Maharashtra";
        hospital1.country = "India";
        hospital1.establishedYear = 1995;
        hospital1.parkingAvailable = true;
        hospital1.cafeteriaAvailable = true;
        hospital1.hospitalCode = "HOSP101";
        hospital1.website = "www.citycare.com";
        hospital1.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital1");

        System.out.println("Hospital ID is " + hospital1.hospitalId);
        System.out.println("Hospital Name is " + hospital1.hospitalName);
        System.out.println("Hospital Location is " + hospital1.location);
        System.out.println("Total Beds are " + hospital1.totalBeds);
        System.out.println("Staff Count is " + hospital1.staffCount);
        System.out.println("Emergency Available " + hospital1.hasEmergency);
        System.out.println("ICU Available " + hospital1.hasICU);
        System.out.println("Ambulance Available " + hospital1.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital1.hasPharmacy);
        System.out.println("Open 24x7 " + hospital1.open24x7);
        System.out.println("Chief Doctor Name " + hospital1.chiefDoctorName);
        System.out.println("Opening Time " + hospital1.openingTime);
        System.out.println("Closing Time " + hospital1.closingTime);
        System.out.println("Hospital Rating " + hospital1.rating);
        System.out.println("Contact Number " + hospital1.contactNumber);
        System.out.println("Email ID " + hospital1.email);
        System.out.println("City " + hospital1.city);
        System.out.println("State " + hospital1.state);
        System.out.println("Country " + hospital1.country);
        System.out.println("Established Year " + hospital1.establishedYear);
        System.out.println("Parking Available " + hospital1.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital1.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital1.hospitalCode);
        System.out.println("Website " + hospital1.website);
        System.out.println("Insurance Accepted " + hospital1.insuranceAccepted);


        Hospital hospital2 = new Hospital();

        System.out.println("Before Initialization of Hospital2");

        System.out.println("Hospital ID is " + hospital2.hospitalId);
        System.out.println("Hospital Name is " + hospital2.hospitalName);
        System.out.println("Hospital Location is " + hospital2.location);
        System.out.println("Total Beds are " + hospital2.totalBeds);
        System.out.println("Staff Count is " + hospital2.staffCount);
        System.out.println("Emergency Available " + hospital2.hasEmergency);
        System.out.println("ICU Available " + hospital2.hasICU);
        System.out.println("Ambulance Available " + hospital2.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital2.hasPharmacy);
        System.out.println("Open 24x7 " + hospital2.open24x7);
        System.out.println("Chief Doctor Name " + hospital2.chiefDoctorName);
        System.out.println("Opening Time " + hospital2.openingTime);
        System.out.println("Closing Time " + hospital2.closingTime);
        System.out.println("Hospital Rating " + hospital2.rating);
        System.out.println("Contact Number " + hospital2.contactNumber);
        System.out.println("Email ID " + hospital2.email);
        System.out.println("City " + hospital2.city);
        System.out.println("State " + hospital2.state);
        System.out.println("Country " + hospital2.country);
        System.out.println("Established Year " + hospital2.establishedYear);
        System.out.println("Parking Available " + hospital2.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital2.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital2.hospitalCode);
        System.out.println("Website " + hospital2.website);
        System.out.println("Insurance Accepted " + hospital2.insuranceAccepted);

        hospital2.hospitalId = 2;
        hospital2.hospitalName = "Green Valley Medical";
        hospital2.location = "North Hills";
        hospital2.totalBeds = 350;
        hospital2.staffCount = 120;
        hospital2.hasEmergency = true;
        hospital2.hasICU = true;
        hospital2.hasAmbulance = true;
        hospital2.hasPharmacy = true;
        hospital2.open24x7 = false;
        hospital2.chiefDoctorName = "Dr. Iyer";
        hospital2.openingTime = "8AM";
        hospital2.closingTime = "10PM";
        hospital2.rating = 4.5;
        hospital2.contactNumber = "9123456789";
        hospital2.email = "info@greenvalley.com";
        hospital2.city = "Bangalore";
        hospital2.state = "Karnataka";
        hospital2.country = "India";
        hospital2.establishedYear = 2005;
        hospital2.parkingAvailable = true;
        hospital2.cafeteriaAvailable = true;
        hospital2.hospitalCode = "HOSP102";
        hospital2.website = "www.greenvalley.com";
        hospital2.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital2");

        System.out.println("Hospital ID is " + hospital2.hospitalId);
        System.out.println("Hospital Name is " + hospital2.hospitalName);
        System.out.println("Hospital Location is " + hospital2.location);
        System.out.println("Total Beds are " + hospital2.totalBeds);
        System.out.println("Staff Count is " + hospital2.staffCount);
        System.out.println("Emergency Available " + hospital2.hasEmergency);
        System.out.println("ICU Available " + hospital2.hasICU);
        System.out.println("Ambulance Available " + hospital2.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital2.hasPharmacy);
        System.out.println("Open 24x7 " + hospital2.open24x7);
        System.out.println("Chief Doctor Name " + hospital2.chiefDoctorName);
        System.out.println("Opening Time " + hospital2.openingTime);
        System.out.println("Closing Time " + hospital2.closingTime);
        System.out.println("Hospital Rating " + hospital2.rating);
        System.out.println("Contact Number " + hospital2.contactNumber);
        System.out.println("Email ID " + hospital2.email);
        System.out.println("City " + hospital2.city);
        System.out.println("State " + hospital2.state);
        System.out.println("Country " + hospital2.country);
        System.out.println("Established Year " + hospital2.establishedYear);
        System.out.println("Parking Available " + hospital2.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital2.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital2.hospitalCode);
        System.out.println("Website " + hospital2.website);
        System.out.println("Insurance Accepted " + hospital2.insuranceAccepted);


        Hospital hospital3 = new Hospital();

        System.out.println("Before Initialization of Hospital3");

        System.out.println("Hospital ID is " + hospital3.hospitalId);
        System.out.println("Hospital Name is " + hospital3.hospitalName);
        System.out.println("Hospital Location is " + hospital3.location);
        System.out.println("Total Beds are " + hospital3.totalBeds);
        System.out.println("Staff Count is " + hospital3.staffCount);

        hospital3.hospitalId = 3;
        hospital3.hospitalName = "Sunshine Care";
        hospital3.location = "East End";
        hospital3.totalBeds = 200;
        hospital3.staffCount = 80;
        hospital3.hasEmergency = true;
        hospital3.hasICU = false;
        hospital3.hasAmbulance = true;
        hospital3.hasPharmacy = true;
        hospital3.open24x7 = true;
        hospital3.chiefDoctorName = "Dr. Reddy";
        hospital3.openingTime = "12AM";
        hospital3.closingTime = "11PM";
        hospital3.rating = 4.2;
        hospital3.contactNumber = "9988776655";
        hospital3.email = "sunshine@care.com";
        hospital3.city = "Chennai";
        hospital3.state = "Tamil Nadu";
        hospital3.country = "India";
        hospital3.establishedYear = 2010;
        hospital3.parkingAvailable = true;
        hospital3.cafeteriaAvailable = false;
        hospital3.hospitalCode = "HOSP103";
        hospital3.website = "www.sunshinecare.com";
        hospital3.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital3");

        System.out.println("Hospital ID is " + hospital3.hospitalId);
        System.out.println("Hospital Name is " + hospital3.hospitalName);
        System.out.println("Hospital Location is " + hospital3.location);
        System.out.println("Total Beds are " + hospital3.totalBeds);
        System.out.println("Staff Count is " + hospital3.staffCount);
        System.out.println("City is " + hospital3.city);


        Hospital hospital4 = new Hospital();

        System.out.println("Before Initialization of Hospital4");

        System.out.println("Hospital ID is " + hospital4.hospitalId);
        System.out.println("Hospital Name is " + hospital4.hospitalName);
        System.out.println("Hospital Location is " + hospital4.location);
        System.out.println("Total Beds are " + hospital4.totalBeds);
        System.out.println("Staff Count is " + hospital4.staffCount);
        System.out.println("Emergency Available " + hospital4.hasEmergency);
        System.out.println("ICU Available " + hospital4.hasICU);
        System.out.println("Ambulance Available " + hospital4.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital4.hasPharmacy);
        System.out.println("Open 24x7 " + hospital4.open24x7);
        System.out.println("Chief Doctor Name " + hospital4.chiefDoctorName);
        System.out.println("Opening Time " + hospital4.openingTime);
        System.out.println("Closing Time " + hospital4.closingTime);
        System.out.println("Hospital Rating " + hospital4.rating);
        System.out.println("Contact Number " + hospital4.contactNumber);
        System.out.println("Email ID " + hospital4.email);
        System.out.println("City " + hospital4.city);
        System.out.println("State " + hospital4.state);
        System.out.println("Country " + hospital4.country);
        System.out.println("Established Year " + hospital4.establishedYear);
        System.out.println("Parking Available " + hospital4.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital4.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital4.hospitalCode);
        System.out.println("Website " + hospital4.website);
        System.out.println("Insurance Accepted " + hospital4.insuranceAccepted);

        hospital4.hospitalId = 4;
        hospital4.hospitalName = "Apollo Health Center";
        hospital4.location = "Jubilee Hills";
        hospital4.totalBeds = 800;
        hospital4.staffCount = 300;
        hospital4.hasEmergency = true;
        hospital4.hasICU = true;
        hospital4.hasAmbulance = true;
        hospital4.hasPharmacy = true;
        hospital4.open24x7 = true;
        hospital4.chiefDoctorName = "Dr. Prasad";
        hospital4.openingTime = "12AM";
        hospital4.closingTime = "11PM";
        hospital4.rating = 4.9;
        hospital4.contactNumber = "9001122334";
        hospital4.email = "contact@apollohealth.com";
        hospital4.city = "Hyderabad";
        hospital4.state = "Telangana";
        hospital4.country = "India";
        hospital4.establishedYear = 1988;
        hospital4.parkingAvailable = true;
        hospital4.cafeteriaAvailable = true;
        hospital4.hospitalCode = "HOSP104";
        hospital4.website = "www.apollohealth.com";
        hospital4.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital4");

        System.out.println("Hospital ID is " + hospital4.hospitalId);
        System.out.println("Hospital Name is " + hospital4.hospitalName);
        System.out.println("Hospital Location is " + hospital4.location);
        System.out.println("Total Beds are " + hospital4.totalBeds);
        System.out.println("Staff Count is " + hospital4.staffCount);
        System.out.println("Emergency Available " + hospital4.hasEmergency);
        System.out.println("ICU Available " + hospital4.hasICU);
        System.out.println("Ambulance Available " + hospital4.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital4.hasPharmacy);
        System.out.println("Open 24x7 " + hospital4.open24x7);
        System.out.println("Chief Doctor Name " + hospital4.chiefDoctorName);
        System.out.println("Opening Time " + hospital4.openingTime);
        System.out.println("Closing Time " + hospital4.closingTime);
        System.out.println("Hospital Rating " + hospital4.rating);
        System.out.println("Contact Number " + hospital4.contactNumber);
        System.out.println("Email ID " + hospital4.email);
        System.out.println("City " + hospital4.city);
        System.out.println("State " + hospital4.state);
        System.out.println("Country " + hospital4.country);
        System.out.println("Established Year " + hospital4.establishedYear);
        System.out.println("Parking Available " + hospital4.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital4.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital4.hospitalCode);
        System.out.println("Website " + hospital4.website);
        System.out.println("Insurance Accepted " + hospital4.insuranceAccepted);


        Hospital hospital5 = new Hospital();

        System.out.println("Before Initialization of Hospital5");

        System.out.println("Hospital ID is " + hospital5.hospitalId);
        System.out.println("Hospital Name is " + hospital5.hospitalName);
        System.out.println("Hospital Location is " + hospital5.location);
        System.out.println("Total Beds are " + hospital5.totalBeds);
        System.out.println("Staff Count is " + hospital5.staffCount);
        System.out.println("Emergency Available " + hospital5.hasEmergency);
        System.out.println("ICU Available " + hospital5.hasICU);
        System.out.println("Ambulance Available " + hospital5.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital5.hasPharmacy);
        System.out.println("Open 24x7 " + hospital5.open24x7);
        System.out.println("Chief Doctor Name " + hospital5.chiefDoctorName);
        System.out.println("Opening Time " + hospital5.openingTime);
        System.out.println("Closing Time " + hospital5.closingTime);
        System.out.println("Hospital Rating " + hospital5.rating);
        System.out.println("Contact Number " + hospital5.contactNumber);
        System.out.println("Email ID " + hospital5.email);
        System.out.println("City " + hospital5.city);
        System.out.println("State " + hospital5.state);
        System.out.println("Country " + hospital5.country);
        System.out.println("Established Year " + hospital5.establishedYear);
        System.out.println("Parking Available " + hospital5.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital5.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital5.hospitalCode);
        System.out.println("Website " + hospital5.website);
        System.out.println("Insurance Accepted " + hospital5.insuranceAccepted);

        hospital5.hospitalId = 5;
        hospital5.hospitalName = "Max Super Speciality";
        hospital5.location = "Saket";
        hospital5.totalBeds = 600;
        hospital5.staffCount = 200;
        hospital5.hasEmergency = true;
        hospital5.hasICU = true;
        hospital5.hasAmbulance = true;
        hospital5.hasPharmacy = true;
        hospital5.open24x7 = true;
        hospital5.chiefDoctorName = "Dr. Gupta";
        hospital5.openingTime = "12AM";
        hospital5.closingTime = "11PM";
        hospital5.rating = 4.7;
        hospital5.contactNumber = "9012345678";
        hospital5.email = "help@maxhospital.com";
        hospital5.city = "Delhi";
        hospital5.state = "Delhi";
        hospital5.country = "India";
        hospital5.establishedYear = 2000;
        hospital5.parkingAvailable = true;
        hospital5.cafeteriaAvailable = true;
        hospital5.hospitalCode = "HOSP105";
        hospital5.website = "www.maxhospital.com";
        hospital5.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital5");

        System.out.println("Hospital ID is " + hospital5.hospitalId);
        System.out.println("Hospital Name is " + hospital5.hospitalName);
        System.out.println("Hospital Location is " + hospital5.location);
        System.out.println("Total Beds are " + hospital5.totalBeds);
        System.out.println("Staff Count is " + hospital5.staffCount);
        System.out.println("Emergency Available " + hospital5.hasEmergency);
        System.out.println("ICU Available " + hospital5.hasICU);
        System.out.println("Ambulance Available " + hospital5.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital5.hasPharmacy);
        System.out.println("Open 24x7 " + hospital5.open24x7);
        System.out.println("Chief Doctor Name " + hospital5.chiefDoctorName);
        System.out.println("Opening Time " + hospital5.openingTime);
        System.out.println("Closing Time " + hospital5.closingTime);
        System.out.println("Hospital Rating " + hospital5.rating);
        System.out.println("Contact Number " + hospital5.contactNumber);
        System.out.println("Email ID " + hospital5.email);
        System.out.println("City " + hospital5.city);
        System.out.println("State " + hospital5.state);
        System.out.println("Country " + hospital5.country);
        System.out.println("Established Year " + hospital5.establishedYear);
        System.out.println("Parking Available " + hospital5.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital5.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital5.hospitalCode);
        System.out.println("Website " + hospital5.website);
        System.out.println("Insurance Accepted " + hospital5.insuranceAccepted);
Hospital hospital6 = new Hospital();

        System.out.println("Before Initialization of Hospital6");
        System.out.println("Hospital ID is " + hospital6.hospitalId);
        System.out.println("Hospital Name is " + hospital6.hospitalName);
        System.out.println("Hospital Location is " + hospital6.location);
        System.out.println("Total Beds are " + hospital6.totalBeds);
        System.out.println("Staff Count is " + hospital6.staffCount);
        System.out.println("Emergency Available " + hospital6.hasEmergency);
        System.out.println("ICU Available " + hospital6.hasICU);
        System.out.println("Ambulance Available " + hospital6.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital6.hasPharmacy);
        System.out.println("Open 24x7 " + hospital6.open24x7);
        System.out.println("Chief Doctor Name " + hospital6.chiefDoctorName);
        System.out.println("Opening Time " + hospital6.openingTime);
        System.out.println("Closing Time " + hospital6.closingTime);
        System.out.println("Hospital Rating " + hospital6.rating);
        System.out.println("Contact Number " + hospital6.contactNumber);
        System.out.println("Email ID " + hospital6.email);
        System.out.println("City " + hospital6.city);
        System.out.println("State " + hospital6.state);
        System.out.println("Country " + hospital6.country);
        System.out.println("Established Year " + hospital6.establishedYear);
        System.out.println("Parking Available " + hospital6.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital6.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital6.hospitalCode);
        System.out.println("Website " + hospital6.website);
        System.out.println("Insurance Accepted " + hospital6.insuranceAccepted);

        hospital6.hospitalId = 6;
        hospital6.hospitalName = "Fortis Escorts";
        hospital6.location = "Okhla";
        hospital6.totalBeds = 450;
        hospital6.staffCount = 180;
        hospital6.hasEmergency = true;
        hospital6.hasICU = true;
        hospital6.hasAmbulance = true;
        hospital6.hasPharmacy = true;
        hospital6.open24x7 = true;
        hospital6.chiefDoctorName = "Dr. Singh";
        hospital6.openingTime = "12AM";
        hospital6.closingTime = "11PM";
        hospital6.rating = 4.6;
        hospital6.contactNumber = "9988001122";
        hospital6.email = "fortis@escorts.com";
        hospital6.city = "Delhi";
        hospital6.state = "Delhi";
        hospital6.country = "India";
        hospital6.establishedYear = 1992;
        hospital6.parkingAvailable = true;
        hospital6.cafeteriaAvailable = true;
        hospital6.hospitalCode = "HOSP106";
        hospital6.website = "www.fortis.com";
        hospital6.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital6");
        System.out.println("Hospital ID is " + hospital6.hospitalId);
        System.out.println("Hospital Name is " + hospital6.hospitalName);
        System.out.println("Hospital Location is " + hospital6.location);
        System.out.println("Total Beds are " + hospital6.totalBeds);
        System.out.println("Staff Count is " + hospital6.staffCount);
        System.out.println("Emergency Available " + hospital6.hasEmergency);
        System.out.println("ICU Available " + hospital6.hasICU);
        System.out.println("Ambulance Available " + hospital6.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital6.hasPharmacy);
        System.out.println("Open 24x7 " + hospital6.open24x7);
        System.out.println("Chief Doctor Name " + hospital6.chiefDoctorName);
        System.out.println("Opening Time " + hospital6.openingTime);
        System.out.println("Closing Time " + hospital6.closingTime);
        System.out.println("Hospital Rating " + hospital6.rating);
        System.out.println("Contact Number " + hospital6.contactNumber);
        System.out.println("Email ID " + hospital6.email);
        System.out.println("City " + hospital6.city);
        System.out.println("State " + hospital6.state);
        System.out.println("Country " + hospital6.country);
        System.out.println("Established Year " + hospital6.establishedYear);
        System.out.println("Parking Available " + hospital6.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital6.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital6.hospitalCode);
        System.out.println("Website " + hospital6.website);
        System.out.println("Insurance Accepted " + hospital6.insuranceAccepted);

        Hospital hospital7 = new Hospital();

        System.out.println("Before Initialization of Hospital7");
        System.out.println("Hospital ID is " + hospital7.hospitalId);
        System.out.println("Hospital Name is " + hospital7.hospitalName);
        System.out.println("Hospital Location is " + hospital7.location);
        System.out.println("Total Beds are " + hospital7.totalBeds);
        System.out.println("Staff Count is " + hospital7.staffCount);
        System.out.println("Emergency Available " + hospital7.hasEmergency);
        System.out.println("ICU Available " + hospital7.hasICU);
        System.out.println("Ambulance Available " + hospital7.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital7.hasPharmacy);
        System.out.println("Open 24x7 " + hospital7.open24x7);
        System.out.println("Chief Doctor Name " + hospital7.chiefDoctorName);
        System.out.println("Opening Time " + hospital7.openingTime);
        System.out.println("Closing Time " + hospital7.closingTime);
        System.out.println("Hospital Rating " + hospital7.rating);
        System.out.println("Contact Number " + hospital7.contactNumber);
        System.out.println("Email ID " + hospital7.email);
        System.out.println("City " + hospital7.city);
        System.out.println("State " + hospital7.state);
        System.out.println("Country " + hospital7.country);
        System.out.println("Established Year " + hospital7.establishedYear);
        System.out.println("Parking Available " + hospital7.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital7.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital7.hospitalCode);
        System.out.println("Website " + hospital7.website);
        System.out.println("Insurance Accepted " + hospital7.insuranceAccepted);

        hospital7.hospitalId = 7;
        hospital7.hospitalName = "Care Hospitals";
        hospital7.location = "Banjara Hills";
        hospital7.totalBeds = 380;
        hospital7.staffCount = 140;
        hospital7.hasEmergency = true;
        hospital7.hasICU = true;
        hospital7.hasAmbulance = true;
        hospital7.hasPharmacy = true;
        hospital7.open24x7 = true;
        hospital7.chiefDoctorName = "Dr. Kumar";
        hospital7.openingTime = "12AM";
        hospital7.closingTime = "11PM";
        hospital7.rating = 4.3;
        hospital7.contactNumber = "9871234567";
        hospital7.email = "info@carehospitals.com";
        hospital7.city = "Hyderabad";
        hospital7.state = "Telangana";
        hospital7.country = "India";
        hospital7.establishedYear = 1997;
        hospital7.parkingAvailable = true;
        hospital7.cafeteriaAvailable = true;
        hospital7.hospitalCode = "HOSP107";
        hospital7.website = "www.carehospitals.com";
        hospital7.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital7");
        System.out.println("Hospital ID is " + hospital7.hospitalId);
        System.out.println("Hospital Name is " + hospital7.hospitalName);
        System.out.println("Hospital Location is " + hospital7.location);
        System.out.println("Total Beds are " + hospital7.totalBeds);
        System.out.println("Staff Count is " + hospital7.staffCount);
        System.out.println("Emergency Available " + hospital7.hasEmergency);
        System.out.println("ICU Available " + hospital7.hasICU);
        System.out.println("Ambulance Available " + hospital7.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital7.hasPharmacy);
        System.out.println("Open 24x7 " + hospital7.open24x7);
        System.out.println("Chief Doctor Name " + hospital7.chiefDoctorName);
        System.out.println("Opening Time " + hospital7.openingTime);
        System.out.println("Closing Time " + hospital7.closingTime);
        System.out.println("Hospital Rating " + hospital7.rating);
        System.out.println("Contact Number " + hospital7.contactNumber);
        System.out.println("Email ID " + hospital7.email);
        System.out.println("City " + hospital7.city);
        System.out.println("State " + hospital7.state);
        System.out.println("Country " + hospital7.country);
        System.out.println("Established Year " + hospital7.establishedYear);
        System.out.println("Parking Available " + hospital7.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital7.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital7.hospitalCode);
        System.out.println("Website " + hospital7.website);
        System.out.println("Insurance Accepted " + hospital7.insuranceAccepted);

        Hospital hospital8 = new Hospital();

        System.out.println("Before Initialization of Hospital8");
        System.out.println("Hospital ID is " + hospital8.hospitalId);
        System.out.println("Hospital Name is " + hospital8.hospitalName);
        System.out.println("Hospital Location is " + hospital8.location);
        System.out.println("Total Beds are " + hospital8.totalBeds);
        System.out.println("Staff Count is " + hospital8.staffCount);
        System.out.println("Emergency Available " + hospital8.hasEmergency);
        System.out.println("ICU Available " + hospital8.hasICU);
        System.out.println("Ambulance Available " + hospital8.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital8.hasPharmacy);
        System.out.println("Open 24x7 " + hospital8.open24x7);
        System.out.println("Chief Doctor Name " + hospital8.chiefDoctorName);
        System.out.println("Opening Time " + hospital8.openingTime);
        System.out.println("Closing Time " + hospital8.closingTime);
        System.out.println("Hospital Rating " + hospital8.rating);
        System.out.println("Contact Number " + hospital8.contactNumber);
        System.out.println("Email ID " + hospital8.email);
        System.out.println("City " + hospital8.city);
        System.out.println("State " + hospital8.state);
        System.out.println("Country " + hospital8.country);
        System.out.println("Established Year " + hospital8.establishedYear);
        System.out.println("Parking Available " + hospital8.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital8.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital8.hospitalCode);
        System.out.println("Website " + hospital8.website);
        System.out.println("Insurance Accepted " + hospital8.insuranceAccepted);

        hospital8.hospitalId = 8;
        hospital8.hospitalName = "Manipal Hospital";
        hospital8.location = "Old Airport Road";
        hospital8.totalBeds = 700;
        hospital8.staffCount = 250;
        hospital8.hasEmergency = true;
        hospital8.hasICU = true;
        hospital8.hasAmbulance = true;
        hospital8.hasPharmacy = true;
        hospital8.open24x7 = true;
        hospital8.chiefDoctorName = "Dr. Hegde";
        hospital8.openingTime = "12AM";
        hospital8.closingTime = "11PM";
        hospital8.rating = 4.8;
        hospital8.contactNumber = "9887766554";
        hospital8.email = "contact@manipal.com";
        hospital8.city = "Bangalore";
        hospital8.state = "Karnataka";
        hospital8.country = "India";
        hospital8.establishedYear = 1991;
        hospital8.parkingAvailable = true;
        hospital8.cafeteriaAvailable = true;
        hospital8.hospitalCode = "HOSP108";
        hospital8.website = "www.manipal.com";
        hospital8.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital8");
        System.out.println("Hospital ID is " + hospital8.hospitalId);
        System.out.println("Hospital Name is " + hospital8.hospitalName);
        System.out.println("Hospital Location is " + hospital8.location);
        System.out.println("Total Beds are " + hospital8.totalBeds);
        System.out.println("Staff Count is " + hospital8.staffCount);
        System.out.println("Emergency Available " + hospital8.hasEmergency);
        System.out.println("ICU Available " + hospital8.hasICU);
        System.out.println("Ambulance Available " + hospital8.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital8.hasPharmacy);
        System.out.println("Open 24x7 " + hospital8.open24x7);
        System.out.println("Chief Doctor Name " + hospital8.chiefDoctorName);
        System.out.println("Opening Time " + hospital8.openingTime);
        System.out.println("Closing Time " + hospital8.closingTime);
        System.out.println("Hospital Rating " + hospital8.rating);
        System.out.println("Contact Number " + hospital8.contactNumber);
        System.out.println("Email ID " + hospital8.email);
        System.out.println("City " + hospital8.city);
        System.out.println("State " + hospital8.state);
        System.out.println("Country " + hospital8.country);
        System.out.println("Established Year " + hospital8.establishedYear);
        System.out.println("Parking Available " + hospital8.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital8.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital8.hospitalCode);
        System.out.println("Website " + hospital8.website);
        System.out.println("Insurance Accepted " + hospital8.insuranceAccepted);

        Hospital hospital9 = new Hospital();

        System.out.println("Before Initialization of Hospital9");
        System.out.println("Hospital ID is " + hospital9.hospitalId);
        System.out.println("Hospital Name is " + hospital9.hospitalName);
        System.out.println("Hospital Location is " + hospital9.location);
        System.out.println("Total Beds are " + hospital9.totalBeds);
        System.out.println("Staff Count is " + hospital9.staffCount);
        System.out.println("Emergency Available " + hospital9.hasEmergency);
        System.out.println("ICU Available " + hospital9.hasICU);
        System.out.println("Ambulance Available " + hospital9.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital9.hasPharmacy);
        System.out.println("Open 24x7 " + hospital9.open24x7);
        System.out.println("Chief Doctor Name " + hospital9.chiefDoctorName);
        System.out.println("Opening Time " + hospital9.openingTime);
        System.out.println("Closing Time " + hospital9.closingTime);
        System.out.println("Hospital Rating " + hospital9.rating);
        System.out.println("Contact Number " + hospital9.contactNumber);
        System.out.println("Email ID " + hospital9.email);
        System.out.println("City " + hospital9.city);
        System.out.println("State " + hospital9.state);
        System.out.println("Country " + hospital9.country);
        System.out.println("Established Year " + hospital9.establishedYear);
        System.out.println("Parking Available " + hospital9.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital9.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital9.hospitalCode);
        System.out.println("Website " + hospital9.website);
        System.out.println("Insurance Accepted " + hospital9.insuranceAccepted);

        hospital9.hospitalId = 9;
        hospital9.hospitalName = "Columbia Asia";
        hospital9.location = "Hebbal";
        hospital9.totalBeds = 250;
        hospital9.staffCount = 90;
        hospital9.hasEmergency = true;
        hospital9.hasICU = true;
        hospital9.hasAmbulance = false;
        hospital9.hasPharmacy = true;
        hospital9.open24x7 = true;
        hospital9.chiefDoctorName = "Dr. Rao";
        hospital9.openingTime = "12AM";
        hospital9.closingTime = "11PM";
        hospital9.rating = 4.4;
        hospital9.contactNumber = "9876501234";
        hospital9.email = "helpdesk@columbia.com";
        hospital9.city = "Bangalore";
        hospital9.state = "Karnataka";
        hospital9.country = "India";
        hospital9.establishedYear = 2004;
        hospital9.parkingAvailable = true;
        hospital9.cafeteriaAvailable = false;
        hospital9.hospitalCode = "HOSP109";
        hospital9.website = "www.columbiaasia.com";
        hospital9.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital9");
        System.out.println("Hospital ID is " + hospital9.hospitalId);
        System.out.println("Hospital Name is " + hospital9.hospitalName);
        System.out.println("Hospital Location is " + hospital9.location);
        System.out.println("Total Beds are " + hospital9.totalBeds);
        System.out.println("Staff Count is " + hospital9.staffCount);
        System.out.println("Emergency Available " + hospital9.hasEmergency);
        System.out.println("ICU Available " + hospital9.hasICU);
        System.out.println("Ambulance Available " + hospital9.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital9.hasPharmacy);
        System.out.println("Open 24x7 " + hospital9.open24x7);
        System.out.println("Chief Doctor Name " + hospital9.chiefDoctorName);
        System.out.println("Opening Time " + hospital9.openingTime);
        System.out.println("Closing Time " + hospital9.closingTime);
        System.out.println("Hospital Rating " + hospital9.rating);
        System.out.println("Contact Number " + hospital9.contactNumber);
        System.out.println("Email ID " + hospital9.email);
        System.out.println("City " + hospital9.city);
        System.out.println("State " + hospital9.state);
        System.out.println("Country " + hospital9.country);
        System.out.println("Established Year " + hospital9.establishedYear);
        System.out.println("Parking Available " + hospital9.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital9.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital9.hospitalCode);
        System.out.println("Website " + hospital9.website);
        System.out.println("Insurance Accepted " + hospital9.insuranceAccepted);

        Hospital hospital10 = new Hospital();

        System.out.println("Before Initialization of Hospital10");
        System.out.println("Hospital ID is " + hospital10.hospitalId);
        System.out.println("Hospital Name is " + hospital10.hospitalName);
        System.out.println("Hospital Location is " + hospital10.location);
        System.out.println("Total Beds are " + hospital10.totalBeds);
        System.out.println("Staff Count is " + hospital10.staffCount);
        System.out.println("Emergency Available " + hospital10.hasEmergency);
        System.out.println("ICU Available " + hospital10.hasICU);
        System.out.println("Ambulance Available " + hospital10.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital10.hasPharmacy);
        System.out.println("Open 24x7 " + hospital10.open24x7);
        System.out.println("Chief Doctor Name " + hospital10.chiefDoctorName);
        System.out.println("Opening Time " + hospital10.openingTime);
        System.out.println("Closing Time " + hospital10.closingTime);
        System.out.println("Hospital Rating " + hospital10.rating);
        System.out.println("Contact Number " + hospital10.contactNumber);
        System.out.println("Email ID " + hospital10.email);
        System.out.println("City " + hospital10.city);
        System.out.println("State " + hospital10.state);
        System.out.println("Country " + hospital10.country);
        System.out.println("Established Year " + hospital10.establishedYear);
        System.out.println("Parking Available " + hospital10.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital10.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital10.hospitalCode);
        System.out.println("Website " + hospital10.website);
        System.out.println("Insurance Accepted " + hospital10.insuranceAccepted);

        hospital10.hospitalId = 10;
        hospital10.hospitalName = "Narayana Health";
        hospital10.location = "Bommasandra";
        hospital10.totalBeds = 900;
        hospital10.staffCount = 400;
        hospital10.hasEmergency = true;
        hospital10.hasICU = true;
        hospital10.hasAmbulance = true;
        hospital10.hasPharmacy = true;
        hospital10.open24x7 = true;
        hospital10.chiefDoctorName = "Dr. Shetty";
        hospital10.openingTime = "12AM";
        hospital10.closingTime = "11PM";
        hospital10.rating = 4.9;
        hospital10.contactNumber = "9898989898";
        hospital10.email = "care@narayanahealth.com";
        hospital10.city = "Bangalore";
        hospital10.state = "Karnataka";
        hospital10.country = "India";
        hospital10.establishedYear = 2000;
        hospital10.parkingAvailable = true;
        hospital10.cafeteriaAvailable = true;
        hospital10.hospitalCode = "HOSP110";
        hospital10.website = "www.narayanahealth.com";
        hospital10.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital10");
        System.out.println("Hospital ID is " + hospital10.hospitalId);
        System.out.println("Hospital Name is " + hospital10.hospitalName);
        System.out.println("Hospital Location is " + hospital10.location);
        System.out.println("Total Beds are " + hospital10.totalBeds);
        System.out.println("Staff Count is " + hospital10.staffCount);
        System.out.println("Emergency Available " + hospital10.hasEmergency);
        System.out.println("ICU Available " + hospital10.hasICU);
        System.out.println("Ambulance Available " + hospital10.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital10.hasPharmacy);
        System.out.println("Open 24x7 " + hospital10.open24x7);
        System.out.println("Chief Doctor Name " + hospital10.chiefDoctorName);
        System.out.println("Opening Time " + hospital10.openingTime);
        System.out.println("Closing Time " + hospital10.closingTime);
        System.out.println("Hospital Rating " + hospital10.rating);
        System.out.println("Contact Number " + hospital10.contactNumber);
        System.out.println("Email ID " + hospital10.email);
        System.out.println("City " + hospital10.city);
        System.out.println("State " + hospital10.state);
        System.out.println("Country " + hospital10.country);
        System.out.println("Established Year " + hospital10.establishedYear);
        System.out.println("Parking Available " + hospital10.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital10.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital10.hospitalCode);
        System.out.println("Website " + hospital10.website);
        System.out.println("Insurance Accepted " + hospital10.insuranceAccepted);

        Hospital hospital11 = new Hospital();

        System.out.println("Before Initialization of Hospital11");
        System.out.println("Hospital ID is " + hospital11.hospitalId);
        System.out.println("Hospital Name is " + hospital11.hospitalName);
        System.out.println("Hospital Location is " + hospital11.location);
        System.out.println("Total Beds are " + hospital11.totalBeds);
        System.out.println("Staff Count is " + hospital11.staffCount);
        System.out.println("Emergency Available " + hospital11.hasEmergency);
        System.out.println("ICU Available " + hospital11.hasICU);
        System.out.println("Ambulance Available " + hospital11.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital11.hasPharmacy);
        System.out.println("Open 24x7 " + hospital11.open24x7);
        System.out.println("Chief Doctor Name " + hospital11.chiefDoctorName);
        System.out.println("Opening Time " + hospital11.openingTime);
        System.out.println("Closing Time " + hospital11.closingTime);
        System.out.println("Hospital Rating " + hospital11.rating);
        System.out.println("Contact Number " + hospital11.contactNumber);
        System.out.println("Email ID " + hospital11.email);
        System.out.println("City " + hospital11.city);
        System.out.println("State " + hospital11.state);
        System.out.println("Country " + hospital11.country);
        System.out.println("Established Year " + hospital11.establishedYear);
        System.out.println("Parking Available " + hospital11.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital11.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital11.hospitalCode);
        System.out.println("Website " + hospital11.website);
        System.out.println("Insurance Accepted " + hospital11.insuranceAccepted);

        hospital11.hospitalId = 11;
        hospital11.hospitalName = "Medanta The Medicity";
        hospital11.location = "Sector 38";
        hospital11.totalBeds = 1250;
        hospital11.staffCount = 500;
        hospital11.hasEmergency = true;
        hospital11.hasICU = true;
        hospital11.hasAmbulance = true;
        hospital11.hasPharmacy = true;
        hospital11.open24x7 = true;
        hospital11.chiefDoctorName = "Dr. Trehan";
        hospital11.openingTime = "12AM";
        hospital11.closingTime = "11PM";
        hospital11.rating = 4.8;
        hospital11.contactNumber = "9876541111";
        hospital11.email = "info@medanta.org";
        hospital11.city = "Gurgaon";
        hospital11.state = "Haryana";
        hospital11.country = "India";
        hospital11.establishedYear = 2009;
        hospital11.parkingAvailable = true;
        hospital11.cafeteriaAvailable = true;
        hospital11.hospitalCode = "HOSP111";
        hospital11.website = "www.medanta.org";
        hospital11.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital11");
        System.out.println("Hospital ID is " + hospital11.hospitalId);
        System.out.println("Hospital Name is " + hospital11.hospitalName);
        System.out.println("Hospital Location is " + hospital11.location);
        System.out.println("Total Beds are " + hospital11.totalBeds);
        System.out.println("Staff Count is " + hospital11.staffCount);
        System.out.println("Emergency Available " + hospital11.hasEmergency);
        System.out.println("ICU Available " + hospital11.hasICU);
        System.out.println("Ambulance Available " + hospital11.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital11.hasPharmacy);
        System.out.println("Open 24x7 " + hospital11.open24x7);
        System.out.println("Chief Doctor Name " + hospital11.chiefDoctorName);
        System.out.println("Opening Time " + hospital11.openingTime);
        System.out.println("Closing Time " + hospital11.closingTime);
        System.out.println("Hospital Rating " + hospital11.rating);
        System.out.println("Contact Number " + hospital11.contactNumber);
        System.out.println("Email ID " + hospital11.email);
        System.out.println("City " + hospital11.city);
        System.out.println("State " + hospital11.state);
        System.out.println("Country " + hospital11.country);
        System.out.println("Established Year " + hospital11.establishedYear);
        System.out.println("Parking Available " + hospital11.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital11.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital11.hospitalCode);
        System.out.println("Website " + hospital11.website);
        System.out.println("Insurance Accepted " + hospital11.insuranceAccepted);

        Hospital hospital12 = new Hospital();

        System.out.println("Before Initialization of Hospital12");
        System.out.println("Hospital ID is " + hospital12.hospitalId);
        System.out.println("Hospital Name is " + hospital12.hospitalName);
        System.out.println("Hospital Location is " + hospital12.location);
        System.out.println("Total Beds are " + hospital12.totalBeds);
        System.out.println("Staff Count is " + hospital12.staffCount);
        System.out.println("Emergency Available " + hospital12.hasEmergency);
        System.out.println("ICU Available " + hospital12.hasICU);
        System.out.println("Ambulance Available " + hospital12.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital12.hasPharmacy);
        System.out.println("Open 24x7 " + hospital12.open24x7);
        System.out.println("Chief Doctor Name " + hospital12.chiefDoctorName);
        System.out.println("Opening Time " + hospital12.openingTime);
        System.out.println("Closing Time " + hospital12.closingTime);
        System.out.println("Hospital Rating " + hospital12.rating);
        System.out.println("Contact Number " + hospital12.contactNumber);
        System.out.println("Email ID " + hospital12.email);
        System.out.println("City " + hospital12.city);
        System.out.println("State " + hospital12.state);
        System.out.println("Country " + hospital12.country);
        System.out.println("Established Year " + hospital12.establishedYear);
        System.out.println("Parking Available " + hospital12.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital12.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital12.hospitalCode);
        System.out.println("Website " + hospital12.website);
        System.out.println("Insurance Accepted " + hospital12.insuranceAccepted);

        hospital12.hospitalId = 12;
        hospital12.hospitalName = "Global Hospital";
        hospital12.location = "Parel";
        hospital12.totalBeds = 300;
        hospital12.staffCount = 130;
        hospital12.hasEmergency = true;
        hospital12.hasICU = true;
        hospital12.hasAmbulance = true;
        hospital12.hasPharmacy = true;
        hospital12.open24x7 = true;
        hospital12.chiefDoctorName = "Dr. Joshi";
        hospital12.openingTime = "12AM";
        hospital12.closingTime = "11PM";
        hospital12.rating = 4.2;
        hospital12.contactNumber = "9876502222";
        hospital12.email = "mumbai@globalhospital.com";
        hospital12.city = "Mumbai";
        hospital12.state = "Maharashtra";
        hospital12.country = "India";
        hospital12.establishedYear = 1996;
        hospital12.parkingAvailable = true;
        hospital12.cafeteriaAvailable = true;
        hospital12.hospitalCode = "HOSP112";
        hospital12.website = "www.globalhospital.com";
        hospital12.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital12");
        System.out.println("Hospital ID is " + hospital12.hospitalId);
        System.out.println("Hospital Name is " + hospital12.hospitalName);
        System.out.println("Hospital Location is " + hospital12.location);
        System.out.println("Total Beds are " + hospital12.totalBeds);
        System.out.println("Staff Count is " + hospital12.staffCount);
        System.out.println("Emergency Available " + hospital12.hasEmergency);
        System.out.println("ICU Available " + hospital12.hasICU);
        System.out.println("Ambulance Available " + hospital12.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital12.hasPharmacy);
        System.out.println("Open 24x7 " + hospital12.open24x7);
        System.out.println("Chief Doctor Name " + hospital12.chiefDoctorName);
        System.out.println("Opening Time " + hospital12.openingTime);
        System.out.println("Closing Time " + hospital12.closingTime);
        System.out.println("Hospital Rating " + hospital12.rating);
        System.out.println("Contact Number " + hospital12.contactNumber);
        System.out.println("Email ID " + hospital12.email);
        System.out.println("City " + hospital12.city);
        System.out.println("State " + hospital12.state);
        System.out.println("Country " + hospital12.country);
        System.out.println("Established Year " + hospital12.establishedYear);
        System.out.println("Parking Available " + hospital12.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital12.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital12.hospitalCode);
        System.out.println("Website " + hospital12.website);
        System.out.println("Insurance Accepted " + hospital12.insuranceAccepted);

        Hospital hospital13 = new Hospital();

        System.out.println("Before Initialization of Hospital13");
        System.out.println("Hospital ID is " + hospital13.hospitalId);
        System.out.println("Hospital Name is " + hospital13.hospitalName);
        System.out.println("Hospital Location is " + hospital13.location);
        System.out.println("Total Beds are " + hospital13.totalBeds);
        System.out.println("Staff Count is " + hospital13.staffCount);
        System.out.println("Emergency Available " + hospital13.hasEmergency);
        System.out.println("ICU Available " + hospital13.hasICU);
        System.out.println("Ambulance Available " + hospital13.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital13.hasPharmacy);
        System.out.println("Open 24x7 " + hospital13.open24x7);
        System.out.println("Chief Doctor Name " + hospital13.chiefDoctorName);
        System.out.println("Opening Time " + hospital13.openingTime);
        System.out.println("Closing Time " + hospital13.closingTime);
        System.out.println("Hospital Rating " + hospital13.rating);
        System.out.println("Contact Number " + hospital13.contactNumber);
        System.out.println("Email ID " + hospital13.email);
        System.out.println("City " + hospital13.city);
        System.out.println("State " + hospital13.state);
        System.out.println("Country " + hospital13.country);
        System.out.println("Established Year " + hospital13.establishedYear);
        System.out.println("Parking Available " + hospital13.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital13.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital13.hospitalCode);
        System.out.println("Website " + hospital13.website);
        System.out.println("Insurance Accepted " + hospital13.insuranceAccepted);

        hospital13.hospitalId = 13;
        hospital13.hospitalName = "KIMS Hospital";
        hospital13.location = "Secunderabad";
        hospital13.totalBeds = 400;
        hospital13.staffCount = 160;
        hospital13.hasEmergency = true;
        hospital13.hasICU = true;
        hospital13.hasAmbulance = true;
        hospital13.hasPharmacy = true;
        hospital13.open24x7 = true;
        hospital13.chiefDoctorName = "Dr. Bhaskar";
        hospital13.openingTime = "12AM";
        hospital13.closingTime = "11PM";
        hospital13.rating = 4.4;
        hospital13.contactNumber = "9876503333";
        hospital13.email = "care@kimshospitals.com";
        hospital13.city = "Secunderabad";
        hospital13.state = "Telangana";
        hospital13.country = "India";
        hospital13.establishedYear = 2004;
        hospital13.parkingAvailable = true;
        hospital13.cafeteriaAvailable = true;
        hospital13.hospitalCode = "HOSP113";
        hospital13.website = "www.kimshospitals.com";
        hospital13.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital13");
        System.out.println("Hospital ID is " + hospital13.hospitalId);
        System.out.println("Hospital Name is " + hospital13.hospitalName);
        System.out.println("Hospital Location is " + hospital13.location);
        System.out.println("Total Beds are " + hospital13.totalBeds);
        System.out.println("Staff Count is " + hospital13.staffCount);
        System.out.println("Emergency Available " + hospital13.hasEmergency);
        System.out.println("ICU Available " + hospital13.hasICU);
        System.out.println("Ambulance Available " + hospital13.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital13.hasPharmacy);
        System.out.println("Open 24x7 " + hospital13.open24x7);
        System.out.println("Chief Doctor Name " + hospital13.chiefDoctorName);
        System.out.println("Opening Time " + hospital13.openingTime);
        System.out.println("Closing Time " + hospital13.closingTime);
        System.out.println("Hospital Rating " + hospital13.rating);
        System.out.println("Contact Number " + hospital13.contactNumber);
        System.out.println("Email ID " + hospital13.email);
        System.out.println("City " + hospital13.city);
        System.out.println("State " + hospital13.state);
        System.out.println("Country " + hospital13.country);
        System.out.println("Established Year " + hospital13.establishedYear);
        System.out.println("Parking Available " + hospital13.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital13.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital13.hospitalCode);
        System.out.println("Website " + hospital13.website);
        System.out.println("Insurance Accepted " + hospital13.insuranceAccepted);

        Hospital hospital14 = new Hospital();

        System.out.println("Before Initialization of Hospital14");
        System.out.println("Hospital ID is " + hospital14.hospitalId);
        System.out.println("Hospital Name is " + hospital14.hospitalName);
        System.out.println("Hospital Location is " + hospital14.location);
        System.out.println("Total Beds are " + hospital14.totalBeds);
        System.out.println("Staff Count is " + hospital14.staffCount);
        System.out.println("Emergency Available " + hospital14.hasEmergency);
        System.out.println("ICU Available " + hospital14.hasICU);
        System.out.println("Ambulance Available " + hospital14.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital14.hasPharmacy);
        System.out.println("Open 24x7 " + hospital14.open24x7);
        System.out.println("Chief Doctor Name " + hospital14.chiefDoctorName);
        System.out.println("Opening Time " + hospital14.openingTime);
        System.out.println("Closing Time " + hospital14.closingTime);
        System.out.println("Hospital Rating " + hospital14.rating);
        System.out.println("Contact Number " + hospital14.contactNumber);
        System.out.println("Email ID " + hospital14.email);
        System.out.println("City " + hospital14.city);
        System.out.println("State " + hospital14.state);
        System.out.println("Country " + hospital14.country);
        System.out.println("Established Year " + hospital14.establishedYear);
        System.out.println("Parking Available " + hospital14.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital14.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital14.hospitalCode);
        System.out.println("Website " + hospital14.website);
        System.out.println("Insurance Accepted " + hospital14.insuranceAccepted);

        hospital14.hospitalId = 14;
        hospital14.hospitalName = "Sterling Hospital";
        hospital14.location = "Gurukul";
        hospital14.totalBeds = 280;
        hospital14.staffCount = 110;
        hospital14.hasEmergency = true;
        hospital14.hasICU = true;
        hospital14.hasAmbulance = true;
        hospital14.hasPharmacy = true;
        hospital14.open24x7 = true;
        hospital14.chiefDoctorName = "Dr. Patel";
        hospital14.openingTime = "12AM";
        hospital14.closingTime = "11PM";
        hospital14.rating = 4.1;
        hospital14.contactNumber = "9876504444";
        hospital14.email = "info@sterlinghospitals.com";
        hospital14.city = "Ahmedabad";
        hospital14.state = "Gujarat";
        hospital14.country = "India";
        hospital14.establishedYear = 2001;
        hospital14.parkingAvailable = true;
        hospital14.cafeteriaAvailable = false;
        hospital14.hospitalCode = "HOSP114";
        hospital14.website = "www.sterlinghospitals.com";
        hospital14.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital14");
        System.out.println("Hospital ID is " + hospital14.hospitalId);
        System.out.println("Hospital Name is " + hospital14.hospitalName);
        System.out.println("Hospital Location is " + hospital14.location);
        System.out.println("Total Beds are " + hospital14.totalBeds);
        System.out.println("Staff Count is " + hospital14.staffCount);
        System.out.println("Emergency Available " + hospital14.hasEmergency);
        System.out.println("ICU Available " + hospital14.hasICU);
        System.out.println("Ambulance Available " + hospital14.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital14.hasPharmacy);
        System.out.println("Open 24x7 " + hospital14.open24x7);
        System.out.println("Chief Doctor Name " + hospital14.chiefDoctorName);
        System.out.println("Opening Time " + hospital14.openingTime);
        System.out.println("Closing Time " + hospital14.closingTime);
        System.out.println("Hospital Rating " + hospital14.rating);
        System.out.println("Contact Number " + hospital14.contactNumber);
        System.out.println("Email ID " + hospital14.email);
        System.out.println("City " + hospital14.city);
        System.out.println("State " + hospital14.state);
        System.out.println("Country " + hospital14.country);
        System.out.println("Established Year " + hospital14.establishedYear);
        System.out.println("Parking Available " + hospital14.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital14.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital14.hospitalCode);
        System.out.println("Website " + hospital14.website);
        System.out.println("Insurance Accepted " + hospital14.insuranceAccepted);

        Hospital hospital15 = new Hospital();

        System.out.println("Before Initialization of Hospital15");
        System.out.println("Hospital ID is " + hospital15.hospitalId);
        System.out.println("Hospital Name is " + hospital15.hospitalName);
        System.out.println("Hospital Location is " + hospital15.location);
        System.out.println("Total Beds are " + hospital15.totalBeds);
        System.out.println("Staff Count is " + hospital15.staffCount);
        System.out.println("Emergency Available " + hospital15.hasEmergency);
        System.out.println("ICU Available " + hospital15.hasICU);
        System.out.println("Ambulance Available " + hospital15.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital15.hasPharmacy);
        System.out.println("Open 24x7 " + hospital15.open24x7);
        System.out.println("Chief Doctor Name " + hospital15.chiefDoctorName);
        System.out.println("Opening Time " + hospital15.openingTime);
        System.out.println("Closing Time " + hospital15.closingTime);
        System.out.println("Hospital Rating " + hospital15.rating);
        System.out.println("Contact Number " + hospital15.contactNumber);
        System.out.println("Email ID " + hospital15.email);
        System.out.println("City " + hospital15.city);
        System.out.println("State " + hospital15.state);
        System.out.println("Country " + hospital15.country);
        System.out.println("Established Year " + hospital15.establishedYear);
        System.out.println("Parking Available " + hospital15.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital15.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital15.hospitalCode);
        System.out.println("Website " + hospital15.website);
        System.out.println("Insurance Accepted " + hospital15.insuranceAccepted);

        hospital15.hospitalId = 15;
        hospital15.hospitalName = "Yashoda Hospital";
        hospital15.location = "Somajiguda";
        hospital15.totalBeds = 550;
        hospital15.staffCount = 220;
        hospital15.hasEmergency = true;
        hospital15.hasICU = true;
        hospital15.hasAmbulance = true;
        hospital15.hasPharmacy = true;
        hospital15.open24x7 = true;
        hospital15.chiefDoctorName = "Dr. Krishna";
        hospital15.openingTime = "12AM";
        hospital15.closingTime = "11PM";
        hospital15.rating = 4.6;
        hospital15.contactNumber = "9876505555";
        hospital15.email = "helpdesk@yashodahospitals.com";
        hospital15.city = "Hyderabad";
        hospital15.state = "Telangana";
        hospital15.country = "India";
        hospital15.establishedYear = 1989;
        hospital15.parkingAvailable = true;
        hospital15.cafeteriaAvailable = true;
        hospital15.hospitalCode = "HOSP115";
        hospital15.website = "www.yashodahospitals.com";
        hospital15.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital15");
        System.out.println("Hospital ID is " + hospital15.hospitalId);
        System.out.println("Hospital Name is " + hospital15.hospitalName);
        System.out.println("Hospital Location is " + hospital15.location);
        System.out.println("Total Beds are " + hospital15.totalBeds);
        System.out.println("Staff Count is " + hospital15.staffCount);
        System.out.println("Emergency Available " + hospital15.hasEmergency);
        System.out.println("ICU Available " + hospital15.hasICU);
        System.out.println("Ambulance Available " + hospital15.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital15.hasPharmacy);
        System.out.println("Open 24x7 " + hospital15.open24x7);
        System.out.println("Chief Doctor Name " + hospital15.chiefDoctorName);
        System.out.println("Opening Time " + hospital15.openingTime);
        System.out.println("Closing Time " + hospital15.closingTime);
        System.out.println("Hospital Rating " + hospital15.rating);
        System.out.println("Contact Number " + hospital15.contactNumber);
        System.out.println("Email ID " + hospital15.email);
        System.out.println("City " + hospital15.city);
        System.out.println("State " + hospital15.state);
        System.out.println("Country " + hospital15.country);
        System.out.println("Established Year " + hospital15.establishedYear);
        System.out.println("Parking Available " + hospital15.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital15.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital15.hospitalCode);
        System.out.println("Website " + hospital15.website);
        System.out.println("Insurance Accepted " + hospital15.insuranceAccepted);

        Hospital hospital16 = new Hospital();

        System.out.println("Before Initialization of Hospital16");
        System.out.println("Hospital ID is " + hospital16.hospitalId);
        System.out.println("Hospital Name is " + hospital16.hospitalName);
        System.out.println("Hospital Location is " + hospital16.location);
        System.out.println("Total Beds are " + hospital16.totalBeds);
        System.out.println("Staff Count is " + hospital16.staffCount);
        System.out.println("Emergency Available " + hospital16.hasEmergency);
        System.out.println("ICU Available " + hospital16.hasICU);
        System.out.println("Ambulance Available " + hospital16.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital16.hasPharmacy);
        System.out.println("Open 24x7 " + hospital16.open24x7);
        System.out.println("Chief Doctor Name " + hospital16.chiefDoctorName);
        System.out.println("Opening Time " + hospital16.openingTime);
        System.out.println("Closing Time " + hospital16.closingTime);
        System.out.println("Hospital Rating " + hospital16.rating);
        System.out.println("Contact Number " + hospital16.contactNumber);
        System.out.println("Email ID " + hospital16.email);
        System.out.println("City " + hospital16.city);
        System.out.println("State " + hospital16.state);
        System.out.println("Country " + hospital16.country);
        System.out.println("Established Year " + hospital16.establishedYear);
        System.out.println("Parking Available " + hospital16.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital16.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital16.hospitalCode);
        System.out.println("Website " + hospital16.website);
        System.out.println("Insurance Accepted " + hospital16.insuranceAccepted);

        hospital16.hospitalId = 16;
        hospital16.hospitalName = "Ruby Hall Clinic";
        hospital16.location = "Sassoon Road";
        hospital16.totalBeds = 600;
        hospital16.staffCount = 240;
        hospital16.hasEmergency = true;
        hospital16.hasICU = true;
        hospital16.hasAmbulance = true;
        hospital16.hasPharmacy = true;
        hospital16.open24x7 = true;
        hospital16.chiefDoctorName = "Dr. Grant";
        hospital16.openingTime = "12AM";
        hospital16.closingTime = "11PM";
        hospital16.rating = 4.5;
        hospital16.contactNumber = "9876506666";
        hospital16.email = "info@rubyhall.com";
        hospital16.city = "Pune";
        hospital16.state = "Maharashtra";
        hospital16.country = "India";
        hospital16.establishedYear = 1959;
        hospital16.parkingAvailable = true;
        hospital16.cafeteriaAvailable = true;
        hospital16.hospitalCode = "HOSP116";
        hospital16.website = "www.rubyhall.com";
        hospital16.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital16");
        System.out.println("Hospital ID is " + hospital16.hospitalId);
        System.out.println("Hospital Name is " + hospital16.hospitalName);
        System.out.println("Hospital Location is " + hospital16.location);
        System.out.println("Total Beds are " + hospital16.totalBeds);
        System.out.println("Staff Count is " + hospital16.staffCount);
        System.out.println("Emergency Available " + hospital16.hasEmergency);
        System.out.println("ICU Available " + hospital16.hasICU);
        System.out.println("Ambulance Available " + hospital16.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital16.hasPharmacy);
        System.out.println("Open 24x7 " + hospital16.open24x7);
        System.out.println("Chief Doctor Name " + hospital16.chiefDoctorName);
        System.out.println("Opening Time " + hospital16.openingTime);
        System.out.println("Closing Time " + hospital16.closingTime);
        System.out.println("Hospital Rating " + hospital16.rating);
        System.out.println("Contact Number " + hospital16.contactNumber);
        System.out.println("Email ID " + hospital16.email);
        System.out.println("City " + hospital16.city);
        System.out.println("State " + hospital16.state);
        System.out.println("Country " + hospital16.country);
        System.out.println("Established Year " + hospital16.establishedYear);
        System.out.println("Parking Available " + hospital16.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital16.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital16.hospitalCode);
        System.out.println("Website " + hospital16.website);
        System.out.println("Insurance Accepted " + hospital16.insuranceAccepted);

        Hospital hospital17 = new Hospital();

        System.out.println("Before Initialization of Hospital17");
        System.out.println("Hospital ID is " + hospital17.hospitalId);
        System.out.println("Hospital Name is " + hospital17.hospitalName);
        System.out.println("Hospital Location is " + hospital17.location);
        System.out.println("Total Beds are " + hospital17.totalBeds);
        System.out.println("Staff Count is " + hospital17.staffCount);
        System.out.println("Emergency Available " + hospital17.hasEmergency);
        System.out.println("ICU Available " + hospital17.hasICU);
        System.out.println("Ambulance Available " + hospital17.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital17.hasPharmacy);
        System.out.println("Open 24x7 " + hospital17.open24x7);
        System.out.println("Chief Doctor Name " + hospital17.chiefDoctorName);
        System.out.println("Opening Time " + hospital17.openingTime);
        System.out.println("Closing Time " + hospital17.closingTime);
        System.out.println("Hospital Rating " + hospital17.rating);
        System.out.println("Contact Number " + hospital17.contactNumber);
        System.out.println("Email ID " + hospital17.email);
        System.out.println("City " + hospital17.city);
        System.out.println("State " + hospital17.state);
        System.out.println("Country " + hospital17.country);
        System.out.println("Established Year " + hospital17.establishedYear);
        System.out.println("Parking Available " + hospital17.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital17.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital17.hospitalCode);
        System.out.println("Website " + hospital17.website);
        System.out.println("Insurance Accepted " + hospital17.insuranceAccepted);

        hospital17.hospitalId = 17;
        hospital17.hospitalName = "Lilavati Hospital";
        hospital17.location = "Bandra West";
        hospital17.totalBeds = 323;
        hospital17.staffCount = 150;
        hospital17.hasEmergency = true;
        hospital17.hasICU = true;
        hospital17.hasAmbulance = true;
        hospital17.hasPharmacy = true;
        hospital17.open24x7 = true;
        hospital17.chiefDoctorName = "Dr. Mehta";
        hospital17.openingTime = "12AM";
        hospital17.closingTime = "11PM";
        hospital17.rating = 4.7;
        hospital17.contactNumber = "9876507777";
        hospital17.email = "care@lilavatihospital.com";
        hospital17.city = "Mumbai";
        hospital17.state = "Maharashtra";
        hospital17.country = "India";
        hospital17.establishedYear = 1997;
        hospital17.parkingAvailable = true;
        hospital17.cafeteriaAvailable = true;
        hospital17.hospitalCode = "HOSP117";
        hospital17.website = "www.lilavatihospital.com";
        hospital17.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital17");
        System.out.println("Hospital ID is " + hospital17.hospitalId);
        System.out.println("Hospital Name is " + hospital17.hospitalName);
        System.out.println("Hospital Location is " + hospital17.location);
        System.out.println("Total Beds are " + hospital17.totalBeds);
        System.out.println("Staff Count is " + hospital17.staffCount);
        System.out.println("Emergency Available " + hospital17.hasEmergency);
        System.out.println("ICU Available " + hospital17.hasICU);
        System.out.println("Ambulance Available " + hospital17.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital17.hasPharmacy);
        System.out.println("Open 24x7 " + hospital17.open24x7);
        System.out.println("Chief Doctor Name " + hospital17.chiefDoctorName);
        System.out.println("Opening Time " + hospital17.openingTime);
        System.out.println("Closing Time " + hospital17.closingTime);
        System.out.println("Hospital Rating " + hospital17.rating);
        System.out.println("Contact Number " + hospital17.contactNumber);
        System.out.println("Email ID " + hospital17.email);
        System.out.println("City " + hospital17.city);
        System.out.println("State " + hospital17.state);
        System.out.println("Country " + hospital17.country);
        System.out.println("Established Year " + hospital17.establishedYear);
        System.out.println("Parking Available " + hospital17.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital17.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital17.hospitalCode);
        System.out.println("Website " + hospital17.website);
        System.out.println("Insurance Accepted " + hospital17.insuranceAccepted);

        Hospital hospital18 = new Hospital();

        System.out.println("Before Initialization of Hospital18");
        System.out.println("Hospital ID is " + hospital18.hospitalId);
        System.out.println("Hospital Name is " + hospital18.hospitalName);
        System.out.println("Hospital Location is " + hospital18.location);
        System.out.println("Total Beds are " + hospital18.totalBeds);
        System.out.println("Staff Count is " + hospital18.staffCount);
        System.out.println("Emergency Available " + hospital18.hasEmergency);
        System.out.println("ICU Available " + hospital18.hasICU);
        System.out.println("Ambulance Available " + hospital18.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital18.hasPharmacy);
        System.out.println("Open 24x7 " + hospital18.open24x7);
        System.out.println("Chief Doctor Name " + hospital18.chiefDoctorName);
        System.out.println("Opening Time " + hospital18.openingTime);
        System.out.println("Closing Time " + hospital18.closingTime);
        System.out.println("Hospital Rating " + hospital18.rating);
        System.out.println("Contact Number " + hospital18.contactNumber);
        System.out.println("Email ID " + hospital18.email);
        System.out.println("City " + hospital18.city);
        System.out.println("State " + hospital18.state);
        System.out.println("Country " + hospital18.country);
        System.out.println("Established Year " + hospital18.establishedYear);
        System.out.println("Parking Available " + hospital18.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital18.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital18.hospitalCode);
        System.out.println("Website " + hospital18.website);
        System.out.println("Insurance Accepted " + hospital18.insuranceAccepted);

        hospital18.hospitalId = 18;
        hospital18.hospitalName = "Breach Candy Hospital";
        hospital18.location = "Mahalakshmi";
        hospital18.totalBeds = 173;
        hospital18.staffCount = 85;
        hospital18.hasEmergency = true;
        hospital18.hasICU = true;
        hospital18.hasAmbulance = true;
        hospital18.hasPharmacy = true;
        hospital18.open24x7 = true;
        hospital18.chiefDoctorName = "Dr. Udwadia";
        hospital18.openingTime = "12AM";
        hospital18.closingTime = "11PM";
        hospital18.rating = 4.9;
        hospital18.contactNumber = "9876508888";
        hospital18.email = "info@breachcandyhospital.org";
        hospital18.city = "Mumbai";
        hospital18.state = "Maharashtra";
        hospital18.country = "India";
        hospital18.establishedYear = 1950;
        hospital18.parkingAvailable = true;
        hospital18.cafeteriaAvailable = true;
        hospital18.hospitalCode = "HOSP118";
        hospital18.website = "www.breachcandyhospital.org";
        hospital18.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital18");
        System.out.println("Hospital ID is " + hospital18.hospitalId);
        System.out.println("Hospital Name is " + hospital18.hospitalName);
        System.out.println("Hospital Location is " + hospital18.location);
        System.out.println("Total Beds are " + hospital18.totalBeds);
        System.out.println("Staff Count is " + hospital18.staffCount);
        System.out.println("Emergency Available " + hospital18.hasEmergency);
        System.out.println("ICU Available " + hospital18.hasICU);
        System.out.println("Ambulance Available " + hospital18.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital18.hasPharmacy);
        System.out.println("Open 24x7 " + hospital18.open24x7);
        System.out.println("Chief Doctor Name " + hospital18.chiefDoctorName);
        System.out.println("Opening Time " + hospital18.openingTime);
        System.out.println("Closing Time " + hospital18.closingTime);
        System.out.println("Hospital Rating " + hospital18.rating);
        System.out.println("Contact Number " + hospital18.contactNumber);
        System.out.println("Email ID " + hospital18.email);
        System.out.println("City " + hospital18.city);
        System.out.println("State " + hospital18.state);
        System.out.println("Country " + hospital18.country);
        System.out.println("Established Year " + hospital18.establishedYear);
        System.out.println("Parking Available " + hospital18.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital18.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital18.hospitalCode);
        System.out.println("Website " + hospital18.website);
        System.out.println("Insurance Accepted " + hospital18.insuranceAccepted);

        Hospital hospital19 = new Hospital();

        System.out.println("Before Initialization of Hospital19");
        System.out.println("Hospital ID is " + hospital19.hospitalId);
        System.out.println("Hospital Name is " + hospital19.hospitalName);
        System.out.println("Hospital Location is " + hospital19.location);
        System.out.println("Total Beds are " + hospital19.totalBeds);
        System.out.println("Staff Count is " + hospital19.staffCount);
        System.out.println("Emergency Available " + hospital19.hasEmergency);
        System.out.println("ICU Available " + hospital19.hasICU);
        System.out.println("Ambulance Available " + hospital19.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital19.hasPharmacy);
        System.out.println("Open 24x7 " + hospital19.open24x7);
        System.out.println("Chief Doctor Name " + hospital19.chiefDoctorName);
        System.out.println("Opening Time " + hospital19.openingTime);
        System.out.println("Closing Time " + hospital19.closingTime);
        System.out.println("Hospital Rating " + hospital19.rating);
        System.out.println("Contact Number " + hospital19.contactNumber);
        System.out.println("Email ID " + hospital19.email);
        System.out.println("City " + hospital19.city);
        System.out.println("State " + hospital19.state);
        System.out.println("Country " + hospital19.country);
        System.out.println("Established Year " + hospital19.establishedYear);
        System.out.println("Parking Available " + hospital19.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital19.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital19.hospitalCode);
        System.out.println("Website " + hospital19.website);
        System.out.println("Insurance Accepted " + hospital19.insuranceAccepted);

        hospital19.hospitalId = 19;
        hospital19.hospitalName = "Hinduja Hospital";
        hospital19.location = "Mahim";
        hospital19.totalBeds = 400;
        hospital19.staffCount = 190;
        hospital19.hasEmergency = true;
        hospital19.hasICU = true;
        hospital19.hasAmbulance = true;
        hospital19.hasPharmacy = true;
        hospital19.open24x7 = true;
        hospital19.chiefDoctorName = "Dr. Desai";
        hospital19.openingTime = "12AM";
        hospital19.closingTime = "11PM";
        hospital19.rating = 4.8;
        hospital19.contactNumber = "9876509999";
        hospital19.email = "info@hindujahospital.com";
        hospital19.city = "Mumbai";
        hospital19.state = "Maharashtra";
        hospital19.country = "India";
        hospital19.establishedYear = 1951;
        hospital19.parkingAvailable = true;
        hospital19.cafeteriaAvailable = true;
        hospital19.hospitalCode = "HOSP119";
        hospital19.website = "www.hindujahospital.com";
        hospital19.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital19");
        System.out.println("Hospital ID is " + hospital19.hospitalId);
        System.out.println("Hospital Name is " + hospital19.hospitalName);
        System.out.println("Hospital Location is " + hospital19.location);
        System.out.println("Total Beds are " + hospital19.totalBeds);
        System.out.println("Staff Count is " + hospital19.staffCount);
        System.out.println("Emergency Available " + hospital19.hasEmergency);
        System.out.println("ICU Available " + hospital19.hasICU);
        System.out.println("Ambulance Available " + hospital19.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital19.hasPharmacy);
        System.out.println("Open 24x7 " + hospital19.open24x7);
        System.out.println("Chief Doctor Name " + hospital19.chiefDoctorName);
        System.out.println("Opening Time " + hospital19.openingTime);
        System.out.println("Closing Time " + hospital19.closingTime);
        System.out.println("Hospital Rating " + hospital19.rating);
        System.out.println("Contact Number " + hospital19.contactNumber);
        System.out.println("Email ID " + hospital19.email);
        System.out.println("City " + hospital19.city);
        System.out.println("State " + hospital19.state);
        System.out.println("Country " + hospital19.country);
        System.out.println("Established Year " + hospital19.establishedYear);
        System.out.println("Parking Available " + hospital19.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital19.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital19.hospitalCode);
        System.out.println("Website " + hospital19.website);
        System.out.println("Insurance Accepted " + hospital19.insuranceAccepted);

        Hospital hospital20 = new Hospital();

        System.out.println("Before Initialization of Hospital20");
        System.out.println("Hospital ID is " + hospital20.hospitalId);
        System.out.println("Hospital Name is " + hospital20.hospitalName);
        System.out.println("Hospital Location is " + hospital20.location);
        System.out.println("Total Beds are " + hospital20.totalBeds);
        System.out.println("Staff Count is " + hospital20.staffCount);
        System.out.println("Emergency Available " + hospital20.hasEmergency);
        System.out.println("ICU Available " + hospital20.hasICU);
        System.out.println("Ambulance Available " + hospital20.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital20.hasPharmacy);
        System.out.println("Open 24x7 " + hospital20.open24x7);
        System.out.println("Chief Doctor Name " + hospital20.chiefDoctorName);
        System.out.println("Opening Time " + hospital20.openingTime);
        System.out.println("Closing Time " + hospital20.closingTime);
        System.out.println("Hospital Rating " + hospital20.rating);
        System.out.println("Contact Number " + hospital20.contactNumber);
        System.out.println("Email ID " + hospital20.email);
        System.out.println("City " + hospital20.city);
        System.out.println("State " + hospital20.state);
        System.out.println("Country " + hospital20.country);
        System.out.println("Established Year " + hospital20.establishedYear);
        System.out.println("Parking Available " + hospital20.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital20.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital20.hospitalCode);
        System.out.println("Website " + hospital20.website);
        System.out.println("Insurance Accepted " + hospital20.insuranceAccepted);

        hospital20.hospitalId = 20;
        hospital20.hospitalName = "Tata Memorial Hospital";
        hospital20.location = "Parel";
        hospital20.totalBeds = 700;
        hospital20.staffCount = 350;
        hospital20.hasEmergency = true;
        hospital20.hasICU = true;
        hospital20.hasAmbulance = true;
        hospital20.hasPharmacy = true;
        hospital20.open24x7 = true;
        hospital20.chiefDoctorName = "Dr. Badwe";
        hospital20.openingTime = "12AM";
        hospital20.closingTime = "11PM";
        hospital20.rating = 4.9;
        hospital20.contactNumber = "9876510000";
        hospital20.email = "msoffice@tmc.gov.in";
        hospital20.city = "Mumbai";
        hospital20.state = "Maharashtra";
        hospital20.country = "India";
        hospital20.establishedYear = 1941;
        hospital20.parkingAvailable = true;
        hospital20.cafeteriaAvailable = true;
        hospital20.hospitalCode = "HOSP120";
        hospital20.website = "www.tmc.gov.in";
        hospital20.insuranceAccepted = true;

        System.out.println("After Initialization of Hospital20");
        System.out.println("Hospital ID is " + hospital20.hospitalId);
        System.out.println("Hospital Name is " + hospital20.hospitalName);
        System.out.println("Hospital Location is " + hospital20.location);
        System.out.println("Total Beds are " + hospital20.totalBeds);
        System.out.println("Staff Count is " + hospital20.staffCount);
        System.out.println("Emergency Available " + hospital20.hasEmergency);
        System.out.println("ICU Available " + hospital20.hasICU);
        System.out.println("Ambulance Available " + hospital20.hasAmbulance);
        System.out.println("Pharmacy Available " + hospital20.hasPharmacy);
        System.out.println("Open 24x7 " + hospital20.open24x7);
        System.out.println("Chief Doctor Name " + hospital20.chiefDoctorName);
        System.out.println("Opening Time " + hospital20.openingTime);
        System.out.println("Closing Time " + hospital20.closingTime);
        System.out.println("Hospital Rating " + hospital20.rating);
        System.out.println("Contact Number " + hospital20.contactNumber);
        System.out.println("Email ID " + hospital20.email);
        System.out.println("City " + hospital20.city);
        System.out.println("State " + hospital20.state);
        System.out.println("Country " + hospital20.country);
        System.out.println("Established Year " + hospital20.establishedYear);
        System.out.println("Parking Available " + hospital20.parkingAvailable);
        System.out.println("Cafeteria Available " + hospital20.cafeteriaAvailable);
        System.out.println("Hospital Code " + hospital20.hospitalCode);
        System.out.println("Website " + hospital20.website);
        System.out.println("Insurance Accepted " + hospital20.insuranceAccepted);
    }
}