class HotelExecutor {
    public static void main(String[] args){

        Hotel hotel1 = new Hotel();

        System.out.println("Before Initialization of Hotel1");
        System.out.println("Hotel ID is " + hotel1.hotelId);
        System.out.println("Hotel Name is " + hotel1.hotelName);
        System.out.println("Location is " + hotel1.location);
        System.out.println("Total Rooms are " + hotel1.totalRooms);
        System.out.println("Staff Count is " + hotel1.staffCount);
        System.out.println("Wifi Available " + hotel1.hasWifi);
        System.out.println("Pool Available " + hotel1.hasPool);
        System.out.println("Gym Available " + hotel1.hasGym);
        System.out.println("AC Available " + hotel1.hasAC);
        System.out.println("Open Today " + hotel1.openToday);
        System.out.println("Manager Name " + hotel1.managerName);
        System.out.println("Check-In Time " + hotel1.checkInTime);
        System.out.println("Check-Out Time " + hotel1.checkOutTime);
        System.out.println("Rating " + hotel1.rating);
        System.out.println("Contact Number " + hotel1.contactNumber);
        System.out.println("Email ID " + hotel1.email);
        System.out.println("City " + hotel1.city);
        System.out.println("State " + hotel1.state);
        System.out.println("Country " + hotel1.country);
        System.out.println("Established Year " + hotel1.establishedYear);
        System.out.println("Parking Available " + hotel1.parkingAvailable);
        System.out.println("Restaurant Available " + hotel1.restaurantAvailable);
        System.out.println("Hotel Code " + hotel1.hotelCode);
        System.out.println("Website " + hotel1.website);
        System.out.println("Membership Available " + hotel1.membershipAvailable);

        hotel1.hotelId = 1;
        hotel1.hotelName = "Grand Plaza";
        hotel1.location = "MG Road";
        hotel1.totalRooms = 200;
        hotel1.staffCount = 80;
        hotel1.hasWifi = true;
        hotel1.hasPool = true;
        hotel1.hasGym = true;
        hotel1.hasAC = true;
        hotel1.openToday = true;
        hotel1.managerName = "Arjun Kumar";
        hotel1.checkInTime = "12PM";
        hotel1.checkOutTime = "11AM";
        hotel1.rating = 4.5;
        hotel1.contactNumber = "9988776655";
        hotel1.email = "booking@grandplaza.com";
        hotel1.city = "Bangalore";
        hotel1.state = "Karnataka";
        hotel1.country = "India";
        hotel1.establishedYear = 2010;
        hotel1.parkingAvailable = true;
        hotel1.restaurantAvailable = true;
        hotel1.hotelCode = "HTL101";
        hotel1.website = "www.grandplaza.com";
        hotel1.membershipAvailable = true;

        System.out.println("After Initialization of Hotel1");
        System.out.println("Hotel ID is " + hotel1.hotelId);
        System.out.println("Hotel Name is " + hotel1.hotelName);
        System.out.println("Location is " + hotel1.location);
        System.out.println("Total Rooms are " + hotel1.totalRooms);
        System.out.println("Staff Count is " + hotel1.staffCount);
        System.out.println("Wifi Available " + hotel1.hasWifi);
        System.out.println("Pool Available " + hotel1.hasPool);
        System.out.println("Gym Available " + hotel1.hasGym);
        System.out.println("AC Available " + hotel1.hasAC);
        System.out.println("Open Today " + hotel1.openToday);
        System.out.println("Manager Name " + hotel1.managerName);
        System.out.println("Check-In Time " + hotel1.checkInTime);
        System.out.println("Check-Out Time " + hotel1.checkOutTime);
        System.out.println("Rating " + hotel1.rating);
        System.out.println("Contact Number " + hotel1.contactNumber);
        System.out.println("Email ID " + hotel1.email);
        System.out.println("City " + hotel1.city);
        System.out.println("State " + hotel1.state);
        System.out.println("Country " + hotel1.country);
        System.out.println("Established Year " + hotel1.establishedYear);
        System.out.println("Parking Available " + hotel1.parkingAvailable);
        System.out.println("Restaurant Available " + hotel1.restaurantAvailable);
        System.out.println("Hotel Code " + hotel1.hotelCode);
        System.out.println("Website " + hotel1.website);
        System.out.println("Membership Available " + hotel1.membershipAvailable);

        Hotel hotel2 = new Hotel();

        System.out.println("Before Initialization of Hotel2");
        System.out.println("Hotel ID is " + hotel2.hotelId);
        System.out.println("Hotel Name is " + hotel2.hotelName);
        System.out.println("Location is " + hotel2.location);
        System.out.println("Total Rooms are " + hotel2.totalRooms);
        System.out.println("Staff Count is " + hotel2.staffCount);
        System.out.println("Wifi Available " + hotel2.hasWifi);
        System.out.println("Pool Available " + hotel2.hasPool);
        System.out.println("Gym Available " + hotel2.hasGym);
        System.out.println("AC Available " + hotel2.hasAC);
        System.out.println("Open Today " + hotel2.openToday);
        System.out.println("Manager Name " + hotel2.managerName);
        System.out.println("Check-In Time " + hotel2.checkInTime);
        System.out.println("Check-Out Time " + hotel2.checkOutTime);
        System.out.println("Rating " + hotel2.rating);
        System.out.println("Contact Number " + hotel2.contactNumber);
        System.out.println("Email ID " + hotel2.email);
        System.out.println("City " + hotel2.city);
        System.out.println("State " + hotel2.state);
        System.out.println("Country " + hotel2.country);
        System.out.println("Established Year " + hotel2.establishedYear);
        System.out.println("Parking Available " + hotel2.parkingAvailable);
        System.out.println("Restaurant Available " + hotel2.restaurantAvailable);
        System.out.println("Hotel Code " + hotel2.hotelCode);
        System.out.println("Website " + hotel2.website);
        System.out.println("Membership Available " + hotel2.membershipAvailable);

        hotel2.hotelId = 2;
        hotel2.hotelName = "Sea View Resort";
        hotel2.location = "Baga Beach";
        hotel2.totalRooms = 150;
        hotel2.staffCount = 100;
        hotel2.hasWifi = true;
        hotel2.hasPool = true;
        hotel2.hasGym = false;
        hotel2.hasAC = true;
        hotel2.openToday = true;
        hotel2.managerName = "Rahul Desai";
        hotel2.checkInTime = "2PM";
        hotel2.checkOutTime = "12PM";
        hotel2.rating = 4.8;
        hotel2.contactNumber = "9123456780";
        hotel2.email = "stay@seaview.com";
        hotel2.city = "Goa";
        hotel2.state = "Goa";
        hotel2.country = "India";
        hotel2.establishedYear = 2005;
        hotel2.parkingAvailable = true;
        hotel2.restaurantAvailable = true;
        hotel2.hotelCode = "HTL102";
        hotel2.website = "www.seaviewresortgoa.com";
        hotel2.membershipAvailable = false;

        System.out.println("After Initialization of Hotel2");
        System.out.println("Hotel ID is " + hotel2.hotelId);
        System.out.println("Hotel Name is " + hotel2.hotelName);
        System.out.println("Location is " + hotel2.location);
        System.out.println("Total Rooms are " + hotel2.totalRooms);
        System.out.println("Staff Count is " + hotel2.staffCount);
        System.out.println("Wifi Available " + hotel2.hasWifi);
        System.out.println("Pool Available " + hotel2.hasPool);
        System.out.println("Gym Available " + hotel2.hasGym);
        System.out.println("AC Available " + hotel2.hasAC);
        System.out.println("Open Today " + hotel2.openToday);
        System.out.println("Manager Name " + hotel2.managerName);
        System.out.println("Check-In Time " + hotel2.checkInTime);
        System.out.println("Check-Out Time " + hotel2.checkOutTime);
        System.out.println("Rating " + hotel2.rating);
        System.out.println("Contact Number " + hotel2.contactNumber);
        System.out.println("Email ID " + hotel2.email);
        System.out.println("City " + hotel2.city);
        System.out.println("State " + hotel2.state);
        System.out.println("Country " + hotel2.country);
        System.out.println("Established Year " + hotel2.establishedYear);
        System.out.println("Parking Available " + hotel2.parkingAvailable);
        System.out.println("Restaurant Available " + hotel2.restaurantAvailable);
        System.out.println("Hotel Code " + hotel2.hotelCode);
        System.out.println("Website " + hotel2.website);
        System.out.println("Membership Available " + hotel2.membershipAvailable);

        Hotel hotel3 = new Hotel();

        System.out.println("Before Initialization of Hotel3");
        System.out.println("Hotel ID is " + hotel3.hotelId);
        System.out.println("Hotel Name is " + hotel3.hotelName);
        System.out.println("Location is " + hotel3.location);
        System.out.println("Total Rooms are " + hotel3.totalRooms);
        System.out.println("Staff Count is " + hotel3.staffCount);
        System.out.println("Wifi Available " + hotel3.hasWifi);
        System.out.println("Pool Available " + hotel3.hasPool);
        System.out.println("Gym Available " + hotel3.hasGym);
        System.out.println("AC Available " + hotel3.hasAC);
        System.out.println("Open Today " + hotel3.openToday);
        System.out.println("Manager Name " + hotel3.managerName);
        System.out.println("Check-In Time " + hotel3.checkInTime);
        System.out.println("Check-Out Time " + hotel3.checkOutTime);
        System.out.println("Rating " + hotel3.rating);
        System.out.println("Contact Number " + hotel3.contactNumber);
        System.out.println("Email ID " + hotel3.email);
        System.out.println("City " + hotel3.city);
        System.out.println("State " + hotel3.state);
        System.out.println("Country " + hotel3.country);
        System.out.println("Established Year " + hotel3.establishedYear);
        System.out.println("Parking Available " + hotel3.parkingAvailable);
        System.out.println("Restaurant Available " + hotel3.restaurantAvailable);
        System.out.println("Hotel Code " + hotel3.hotelCode);
        System.out.println("Website " + hotel3.website);
        System.out.println("Membership Available " + hotel3.membershipAvailable);

        hotel3.hotelId = 3;
        hotel3.hotelName = "Mountain Retreat";
        hotel3.location = "Mall Road";
        hotel3.totalRooms = 50;
        hotel3.staffCount = 25;
        hotel3.hasWifi = true;
        hotel3.hasPool = false;
        hotel3.hasGym = false;
        hotel3.hasAC = false;
        hotel3.openToday = true;
        hotel3.managerName = "Vikram Singh";
        hotel3.checkInTime = "1PM";
        hotel3.checkOutTime = "11AM";
        hotel3.rating = 4.2;
        hotel3.contactNumber = "9876543211";
        hotel3.email = "hello@mountainretreat.com";
        hotel3.city = "Shimla";
        hotel3.state = "Himachal Pradesh";
        hotel3.country = "India";
        hotel3.establishedYear = 1998;
        hotel3.parkingAvailable = true;
        hotel3.restaurantAvailable = true;
        hotel3.hotelCode = "HTL103";
        hotel3.website = "www.mountainretreat.com";
        hotel3.membershipAvailable = false;

        System.out.println("After Initialization of Hotel3");
        System.out.println("Hotel ID is " + hotel3.hotelId);
        System.out.println("Hotel Name is " + hotel3.hotelName);
        System.out.println("Location is " + hotel3.location);
        System.out.println("Total Rooms are " + hotel3.totalRooms);
        System.out.println("Staff Count is " + hotel3.staffCount);
        System.out.println("Wifi Available " + hotel3.hasWifi);
        System.out.println("Pool Available " + hotel3.hasPool);
        System.out.println("Gym Available " + hotel3.hasGym);
        System.out.println("AC Available " + hotel3.hasAC);
        System.out.println("Open Today " + hotel3.openToday);
        System.out.println("Manager Name " + hotel3.managerName);
        System.out.println("Check-In Time " + hotel3.checkInTime);
        System.out.println("Check-Out Time " + hotel3.checkOutTime);
        System.out.println("Rating " + hotel3.rating);
        System.out.println("Contact Number " + hotel3.contactNumber);
        System.out.println("Email ID " + hotel3.email);
        System.out.println("City " + hotel3.city);
        System.out.println("State " + hotel3.state);
        System.out.println("Country " + hotel3.country);
        System.out.println("Established Year " + hotel3.establishedYear);
        System.out.println("Parking Available " + hotel3.parkingAvailable);
        System.out.println("Restaurant Available " + hotel3.restaurantAvailable);
        System.out.println("Hotel Code " + hotel3.hotelCode);
        System.out.println("Website " + hotel3.website);
        System.out.println("Membership Available " + hotel3.membershipAvailable);

        Hotel hotel4 = new Hotel();

        System.out.println("Before Initialization of Hotel4");
        System.out.println("Hotel ID is " + hotel4.hotelId);
        System.out.println("Hotel Name is " + hotel4.hotelName);
        System.out.println("Location is " + hotel4.location);
        System.out.println("Total Rooms are " + hotel4.totalRooms);
        System.out.println("Staff Count is " + hotel4.staffCount);
        System.out.println("Wifi Available " + hotel4.hasWifi);
        System.out.println("Pool Available " + hotel4.hasPool);
        System.out.println("Gym Available " + hotel4.hasGym);
        System.out.println("AC Available " + hotel4.hasAC);
        System.out.println("Open Today " + hotel4.openToday);
        System.out.println("Manager Name " + hotel4.managerName);
        System.out.println("Check-In Time " + hotel4.checkInTime);
        System.out.println("Check-Out Time " + hotel4.checkOutTime);
        System.out.println("Rating " + hotel4.rating);
        System.out.println("Contact Number " + hotel4.contactNumber);
        System.out.println("Email ID " + hotel4.email);
        System.out.println("City " + hotel4.city);
        System.out.println("State " + hotel4.state);
        System.out.println("Country " + hotel4.country);
        System.out.println("Established Year " + hotel4.establishedYear);
        System.out.println("Parking Available " + hotel4.parkingAvailable);
        System.out.println("Restaurant Available " + hotel4.restaurantAvailable);
        System.out.println("Hotel Code " + hotel4.hotelCode);
        System.out.println("Website " + hotel4.website);
        System.out.println("Membership Available " + hotel4.membershipAvailable);

        hotel4.hotelId = 4;
        hotel4.hotelName = "City Center Inn";
        hotel4.location = "Andheri West";
        hotel4.totalRooms = 120;
        hotel4.staffCount = 60;
        hotel4.hasWifi = true;
        hotel4.hasPool = false;
        hotel4.hasGym = true;
        hotel4.hasAC = true;
        hotel4.openToday = true;
        hotel4.managerName = "Suresh Patil";
        hotel4.checkInTime = "12PM";
        hotel4.checkOutTime = "11AM";
        hotel4.rating = 4.0;
        hotel4.contactNumber = "9001122334";
        hotel4.email = "contact@citycenterinn.com";
        hotel4.city = "Mumbai";
        hotel4.state = "Maharashtra";
        hotel4.country = "India";
        hotel4.establishedYear = 2015;
        hotel4.parkingAvailable = true;
        hotel4.restaurantAvailable = true;
        hotel4.hotelCode = "HTL104";
        hotel4.website = "www.citycenterinn.com";
        hotel4.membershipAvailable = true;

        System.out.println("After Initialization of Hotel4");
        System.out.println("Hotel ID is " + hotel4.hotelId);
        System.out.println("Hotel Name is " + hotel4.hotelName);
        System.out.println("Location is " + hotel4.location);
        System.out.println("Total Rooms are " + hotel4.totalRooms);
        System.out.println("Staff Count is " + hotel4.staffCount);
        System.out.println("Wifi Available " + hotel4.hasWifi);
        System.out.println("Pool Available " + hotel4.hasPool);
        System.out.println("Gym Available " + hotel4.hasGym);
        System.out.println("AC Available " + hotel4.hasAC);
        System.out.println("Open Today " + hotel4.openToday);
        System.out.println("Manager Name " + hotel4.managerName);
        System.out.println("Check-In Time " + hotel4.checkInTime);
        System.out.println("Check-Out Time " + hotel4.checkOutTime);
        System.out.println("Rating " + hotel4.rating);
        System.out.println("Contact Number " + hotel4.contactNumber);
        System.out.println("Email ID " + hotel4.email);
        System.out.println("City " + hotel4.city);
        System.out.println("State " + hotel4.state);
        System.out.println("Country " + hotel4.country);
        System.out.println("Established Year " + hotel4.establishedYear);
        System.out.println("Parking Available " + hotel4.parkingAvailable);
        System.out.println("Restaurant Available " + hotel4.restaurantAvailable);
        System.out.println("Hotel Code " + hotel4.hotelCode);
        System.out.println("Website " + hotel4.website);
        System.out.println("Membership Available " + hotel4.membershipAvailable);

        Hotel hotel5 = new Hotel();

        System.out.println("Before Initialization of Hotel5");
        System.out.println("Hotel ID is " + hotel5.hotelId);
        System.out.println("Hotel Name is " + hotel5.hotelName);
        System.out.println("Location is " + hotel5.location);
        System.out.println("Total Rooms are " + hotel5.totalRooms);
        System.out.println("Staff Count is " + hotel5.staffCount);
        System.out.println("Wifi Available " + hotel5.hasWifi);
        System.out.println("Pool Available " + hotel5.hasPool);
        System.out.println("Gym Available " + hotel5.hasGym);
        System.out.println("AC Available " + hotel5.hasAC);
        System.out.println("Open Today " + hotel5.openToday);
        System.out.println("Manager Name " + hotel5.managerName);
        System.out.println("Check-In Time " + hotel5.checkInTime);
        System.out.println("Check-Out Time " + hotel5.checkOutTime);
        System.out.println("Rating " + hotel5.rating);
        System.out.println("Contact Number " + hotel5.contactNumber);
        System.out.println("Email ID " + hotel5.email);
        System.out.println("City " + hotel5.city);
        System.out.println("State " + hotel5.state);
        System.out.println("Country " + hotel5.country);
        System.out.println("Established Year " + hotel5.establishedYear);
        System.out.println("Parking Available " + hotel5.parkingAvailable);
        System.out.println("Restaurant Available " + hotel5.restaurantAvailable);
        System.out.println("Hotel Code " + hotel5.hotelCode);
        System.out.println("Website " + hotel5.website);
        System.out.println("Membership Available " + hotel5.membershipAvailable);

        hotel5.hotelId = 5;
        hotel5.hotelName = "Royal Palace";
        hotel5.location = "Amer Road";
        hotel5.totalRooms = 300;
        hotel5.staffCount = 150;
        hotel5.hasWifi = true;
        hotel5.hasPool = true;
        hotel5.hasGym = true;
        hotel5.hasAC = true;
        hotel5.openToday = true;
        hotel5.managerName = "Rajesh Sharma";
        hotel5.checkInTime = "2PM";
        hotel5.checkOutTime = "12PM";
        hotel5.rating = 4.9;
        hotel5.contactNumber = "9012345678";
        hotel5.email = "reservations@royalpalace.com";
        hotel5.city = "Jaipur";
        hotel5.state = "Rajasthan";
        hotel5.country = "India";
        hotel5.establishedYear = 1990;
        hotel5.parkingAvailable = true;
        hotel5.restaurantAvailable = true;
        hotel5.hotelCode = "HTL105";
        hotel5.website = "www.royalpalace.com";
        hotel5.membershipAvailable = true;

        System.out.println("After Initialization of Hotel5");
        System.out.println("Hotel ID is " + hotel5.hotelId);
        System.out.println("Hotel Name is " + hotel5.hotelName);
        System.out.println("Location is " + hotel5.location);
        System.out.println("Total Rooms are " + hotel5.totalRooms);
        System.out.println("Staff Count is " + hotel5.staffCount);
        System.out.println("Wifi Available " + hotel5.hasWifi);
        System.out.println("Pool Available " + hotel5.hasPool);
        System.out.println("Gym Available " + hotel5.hasGym);
        System.out.println("AC Available " + hotel5.hasAC);
        System.out.println("Open Today " + hotel5.openToday);
        System.out.println("Manager Name " + hotel5.managerName);
        System.out.println("Check-In Time " + hotel5.checkInTime);
        System.out.println("Check-Out Time " + hotel5.checkOutTime);
        System.out.println("Rating " + hotel5.rating);
        System.out.println("Contact Number " + hotel5.contactNumber);
        System.out.println("Email ID " + hotel5.email);
        System.out.println("City " + hotel5.city);
        System.out.println("State " + hotel5.state);
        System.out.println("Country " + hotel5.country);
        System.out.println("Established Year " + hotel5.establishedYear);
        System.out.println("Parking Available " + hotel5.parkingAvailable);
        System.out.println("Restaurant Available " + hotel5.restaurantAvailable);
        System.out.println("Hotel Code " + hotel5.hotelCode);
        System.out.println("Website " + hotel5.website);
        System.out.println("Membership Available " + hotel5.membershipAvailable);

        Hotel hotel6 = new Hotel();

        System.out.println("Before Initialization of Hotel6");
        System.out.println("Hotel ID is " + hotel6.hotelId);
        System.out.println("Hotel Name is " + hotel6.hotelName);
        System.out.println("Location is " + hotel6.location);
        System.out.println("Total Rooms are " + hotel6.totalRooms);
        System.out.println("Staff Count is " + hotel6.staffCount);
        System.out.println("Wifi Available " + hotel6.hasWifi);
        System.out.println("Pool Available " + hotel6.hasPool);
        System.out.println("Gym Available " + hotel6.hasGym);
        System.out.println("AC Available " + hotel6.hasAC);
        System.out.println("Open Today " + hotel6.openToday);
        System.out.println("Manager Name " + hotel6.managerName);
        System.out.println("Check-In Time " + hotel6.checkInTime);
        System.out.println("Check-Out Time " + hotel6.checkOutTime);
        System.out.println("Rating " + hotel6.rating);
        System.out.println("Contact Number " + hotel6.contactNumber);
        System.out.println("Email ID " + hotel6.email);
        System.out.println("City " + hotel6.city);
        System.out.println("State " + hotel6.state);
        System.out.println("Country " + hotel6.country);
        System.out.println("Established Year " + hotel6.establishedYear);
        System.out.println("Parking Available " + hotel6.parkingAvailable);
        System.out.println("Restaurant Available " + hotel6.restaurantAvailable);
        System.out.println("Hotel Code " + hotel6.hotelCode);
        System.out.println("Website " + hotel6.website);
        System.out.println("Membership Available " + hotel6.membershipAvailable);

        hotel6.hotelId = 6;
        hotel6.hotelName = "Lake Side Hotel";
        hotel6.location = "Pichola";
        hotel6.totalRooms = 80;
        hotel6.staffCount = 45;
        hotel6.hasWifi = true;
        hotel6.hasPool = true;
        hotel6.hasGym = false;
        hotel6.hasAC = true;
        hotel6.openToday = true;
        hotel6.managerName = "Amit Mewar";
        hotel6.checkInTime = "1PM";
        hotel6.checkOutTime = "11AM";
        hotel6.rating = 4.7;
        hotel6.contactNumber = "9988001122";
        hotel6.email = "info@lakeside.com";
        hotel6.city = "Udaipur";
        hotel6.state = "Rajasthan";
        hotel6.country = "India";
        hotel6.establishedYear = 2002;
        hotel6.parkingAvailable = true;
        hotel6.restaurantAvailable = true;
        hotel6.hotelCode = "HTL106";
        hotel6.website = "www.lakesideudaipur.com";
        hotel6.membershipAvailable = false;

        System.out.println("After Initialization of Hotel6");
        System.out.println("Hotel ID is " + hotel6.hotelId);
        System.out.println("Hotel Name is " + hotel6.hotelName);
        System.out.println("Location is " + hotel6.location);
        System.out.println("Total Rooms are " + hotel6.totalRooms);
        System.out.println("Staff Count is " + hotel6.staffCount);
        System.out.println("Wifi Available " + hotel6.hasWifi);
        System.out.println("Pool Available " + hotel6.hasPool);
        System.out.println("Gym Available " + hotel6.hasGym);
        System.out.println("AC Available " + hotel6.hasAC);
        System.out.println("Open Today " + hotel6.openToday);
        System.out.println("Manager Name " + hotel6.managerName);
        System.out.println("Check-In Time " + hotel6.checkInTime);
        System.out.println("Check-Out Time " + hotel6.checkOutTime);
        System.out.println("Rating " + hotel6.rating);
        System.out.println("Contact Number " + hotel6.contactNumber);
        System.out.println("Email ID " + hotel6.email);
        System.out.println("City " + hotel6.city);
        System.out.println("State " + hotel6.state);
        System.out.println("Country " + hotel6.country);
        System.out.println("Established Year " + hotel6.establishedYear);
        System.out.println("Parking Available " + hotel6.parkingAvailable);
        System.out.println("Restaurant Available " + hotel6.restaurantAvailable);
        System.out.println("Hotel Code " + hotel6.hotelCode);
        System.out.println("Website " + hotel6.website);
        System.out.println("Membership Available " + hotel6.membershipAvailable);

        Hotel hotel7 = new Hotel();

        System.out.println("Before Initialization of Hotel7");
        System.out.println("Hotel ID is " + hotel7.hotelId);
        System.out.println("Hotel Name is " + hotel7.hotelName);
        System.out.println("Location is " + hotel7.location);
        System.out.println("Total Rooms are " + hotel7.totalRooms);
        System.out.println("Staff Count is " + hotel7.staffCount);
        System.out.println("Wifi Available " + hotel7.hasWifi);
        System.out.println("Pool Available " + hotel7.hasPool);
        System.out.println("Gym Available " + hotel7.hasGym);
        System.out.println("AC Available " + hotel7.hasAC);
        System.out.println("Open Today " + hotel7.openToday);
        System.out.println("Manager Name " + hotel7.managerName);
        System.out.println("Check-In Time " + hotel7.checkInTime);
        System.out.println("Check-Out Time " + hotel7.checkOutTime);
        System.out.println("Rating " + hotel7.rating);
        System.out.println("Contact Number " + hotel7.contactNumber);
        System.out.println("Email ID " + hotel7.email);
        System.out.println("City " + hotel7.city);
        System.out.println("State " + hotel7.state);
        System.out.println("Country " + hotel7.country);
        System.out.println("Established Year " + hotel7.establishedYear);
        System.out.println("Parking Available " + hotel7.parkingAvailable);
        System.out.println("Restaurant Available " + hotel7.restaurantAvailable);
        System.out.println("Hotel Code " + hotel7.hotelCode);
        System.out.println("Website " + hotel7.website);
        System.out.println("Membership Available " + hotel7.membershipAvailable);

        hotel7.hotelId = 7;
        hotel7.hotelName = "Desert Safari Camp";
        hotel7.location = "Sam Sand Dunes";
        hotel7.totalRooms = 40;
        hotel7.staffCount = 20;
        hotel7.hasWifi = false;
        hotel7.hasPool = false;
        hotel7.hasGym = false;
        hotel7.hasAC = false;
        hotel7.openToday = true;
        hotel7.managerName = "Kishan Bhati";
        hotel7.checkInTime = "4PM";
        hotel7.checkOutTime = "10AM";
        hotel7.rating = 4.6;
        hotel7.contactNumber = "9871234567";
        hotel7.email = "camp@desertsafari.com";
        hotel7.city = "Jaisalmer";
        hotel7.state = "Rajasthan";
        hotel7.country = "India";
        hotel7.establishedYear = 2012;
        hotel7.parkingAvailable = true;
        hotel7.restaurantAvailable = true;
        hotel7.hotelCode = "HTL107";
        hotel7.website = "www.desertsafari.com";
        hotel7.membershipAvailable = false;

        System.out.println("After Initialization of Hotel7");
        System.out.println("Hotel ID is " + hotel7.hotelId);
        System.out.println("Hotel Name is " + hotel7.hotelName);
        System.out.println("Location is " + hotel7.location);
        System.out.println("Total Rooms are " + hotel7.totalRooms);
        System.out.println("Staff Count is " + hotel7.staffCount);
        System.out.println("Wifi Available " + hotel7.hasWifi);
        System.out.println("Pool Available " + hotel7.hasPool);
        System.out.println("Gym Available " + hotel7.hasGym);
        System.out.println("AC Available " + hotel7.hasAC);
        System.out.println("Open Today " + hotel7.openToday);
        System.out.println("Manager Name " + hotel7.managerName);
        System.out.println("Check-In Time " + hotel7.checkInTime);
        System.out.println("Check-Out Time " + hotel7.checkOutTime);
        System.out.println("Rating " + hotel7.rating);
        System.out.println("Contact Number " + hotel7.contactNumber);
        System.out.println("Email ID " + hotel7.email);
        System.out.println("City " + hotel7.city);
        System.out.println("State " + hotel7.state);
        System.out.println("Country " + hotel7.country);
        System.out.println("Established Year " + hotel7.establishedYear);
        System.out.println("Parking Available " + hotel7.parkingAvailable);
        System.out.println("Restaurant Available " + hotel7.restaurantAvailable);
        System.out.println("Hotel Code " + hotel7.hotelCode);
        System.out.println("Website " + hotel7.website);
        System.out.println("Membership Available " + hotel7.membershipAvailable);

        Hotel hotel8 = new Hotel();

        System.out.println("Before Initialization of Hotel8");
        System.out.println("Hotel ID is " + hotel8.hotelId);
        System.out.println("Hotel Name is " + hotel8.hotelName);
        System.out.println("Location is " + hotel8.location);
        System.out.println("Total Rooms are " + hotel8.totalRooms);
        System.out.println("Staff Count is " + hotel8.staffCount);
        System.out.println("Wifi Available " + hotel8.hasWifi);
        System.out.println("Pool Available " + hotel8.hasPool);
        System.out.println("Gym Available " + hotel8.hasGym);
        System.out.println("AC Available " + hotel8.hasAC);
        System.out.println("Open Today " + hotel8.openToday);
        System.out.println("Manager Name " + hotel8.managerName);
        System.out.println("Check-In Time " + hotel8.checkInTime);
        System.out.println("Check-Out Time " + hotel8.checkOutTime);
        System.out.println("Rating " + hotel8.rating);
        System.out.println("Contact Number " + hotel8.contactNumber);
        System.out.println("Email ID " + hotel8.email);
        System.out.println("City " + hotel8.city);
        System.out.println("State " + hotel8.state);
        System.out.println("Country " + hotel8.country);
        System.out.println("Established Year " + hotel8.establishedYear);
        System.out.println("Parking Available " + hotel8.parkingAvailable);
        System.out.println("Restaurant Available " + hotel8.restaurantAvailable);
        System.out.println("Hotel Code " + hotel8.hotelCode);
        System.out.println("Website " + hotel8.website);
        System.out.println("Membership Available " + hotel8.membershipAvailable);

        hotel8.hotelId = 8;
        hotel8.hotelName = "Green Valley";
        hotel8.location = "Tea Estate Road";
        hotel8.totalRooms = 60;
        hotel8.staffCount = 30;
        hotel8.hasWifi = true;
        hotel8.hasPool = false;
        hotel8.hasGym = true;
        hotel8.hasAC = false;
        hotel8.openToday = true;
        hotel8.managerName = "Anil Varghese";
        hotel8.checkInTime = "12PM";
        hotel8.checkOutTime = "11AM";
        hotel8.rating = 4.4;
        hotel8.contactNumber = "9988112233";
        hotel8.email = "stay@greenvalley.com";
        hotel8.city = "Munnar";
        hotel8.state = "Kerala";
        hotel8.country = "India";
        hotel8.establishedYear = 2008;
        hotel8.parkingAvailable = true;
        hotel8.restaurantAvailable = true;
        hotel8.hotelCode = "HTL108";
        hotel8.website = "www.greenvalleymunnar.com";
        hotel8.membershipAvailable = false;

        System.out.println("After Initialization of Hotel8");
        System.out.println("Hotel ID is " + hotel8.hotelId);
        System.out.println("Hotel Name is " + hotel8.hotelName);
        System.out.println("Location is " + hotel8.location);
        System.out.println("Total Rooms are " + hotel8.totalRooms);
        System.out.println("Staff Count is " + hotel8.staffCount);
        System.out.println("Wifi Available " + hotel8.hasWifi);
        System.out.println("Pool Available " + hotel8.hasPool);
        System.out.println("Gym Available " + hotel8.hasGym);
        System.out.println("AC Available " + hotel8.hasAC);
        System.out.println("Open Today " + hotel8.openToday);
        System.out.println("Manager Name " + hotel8.managerName);
        System.out.println("Check-In Time " + hotel8.checkInTime);
        System.out.println("Check-Out Time " + hotel8.checkOutTime);
        System.out.println("Rating " + hotel8.rating);
        System.out.println("Contact Number " + hotel8.contactNumber);
        System.out.println("Email ID " + hotel8.email);
        System.out.println("City " + hotel8.city);
        System.out.println("State " + hotel8.state);
        System.out.println("Country " + hotel8.country);
        System.out.println("Established Year " + hotel8.establishedYear);
        System.out.println("Parking Available " + hotel8.parkingAvailable);
        System.out.println("Restaurant Available " + hotel8.restaurantAvailable);
        System.out.println("Hotel Code " + hotel8.hotelCode);
        System.out.println("Website " + hotel8.website);
        System.out.println("Membership Available " + hotel8.membershipAvailable);

        Hotel hotel9 = new Hotel();

        System.out.println("Before Initialization of Hotel9");
        System.out.println("Hotel ID is " + hotel9.hotelId);
        System.out.println("Hotel Name is " + hotel9.hotelName);
        System.out.println("Location is " + hotel9.location);
        System.out.println("Total Rooms are " + hotel9.totalRooms);
        System.out.println("Staff Count is " + hotel9.staffCount);
        System.out.println("Wifi Available " + hotel9.hasWifi);
        System.out.println("Pool Available " + hotel9.hasPool);
        System.out.println("Gym Available " + hotel9.hasGym);
        System.out.println("AC Available " + hotel9.hasAC);
        System.out.println("Open Today " + hotel9.openToday);
        System.out.println("Manager Name " + hotel9.managerName);
        System.out.println("Check-In Time " + hotel9.checkInTime);
        System.out.println("Check-Out Time " + hotel9.checkOutTime);
        System.out.println("Rating " + hotel9.rating);
        System.out.println("Contact Number " + hotel9.contactNumber);
        System.out.println("Email ID " + hotel9.email);
        System.out.println("City " + hotel9.city);
        System.out.println("State " + hotel9.state);
        System.out.println("Country " + hotel9.country);
        System.out.println("Established Year " + hotel9.establishedYear);
        System.out.println("Parking Available " + hotel9.parkingAvailable);
        System.out.println("Restaurant Available " + hotel9.restaurantAvailable);
        System.out.println("Hotel Code " + hotel9.hotelCode);
        System.out.println("Website " + hotel9.website);
        System.out.println("Membership Available " + hotel9.membershipAvailable);

        hotel9.hotelId = 9;
        hotel9.hotelName = "Snow Peak";
        hotel9.location = "Old Manali";
        hotel9.totalRooms = 45;
        hotel9.staffCount = 22;
        hotel9.hasWifi = true;
        hotel9.hasPool = false;
        hotel9.hasGym = false;
        hotel9.hasAC = false;
        hotel9.openToday = true;
        hotel9.managerName = "Sonam Dorjee";
        hotel9.checkInTime = "12PM";
        hotel9.checkOutTime = "11AM";
        hotel9.rating = 4.3;
        hotel9.contactNumber = "9876500111";
        hotel9.email = "hello@snowpeak.com";
        hotel9.city = "Manali";
        hotel9.state = "Himachal Pradesh";
        hotel9.country = "India";
        hotel9.establishedYear = 2011;
        hotel9.parkingAvailable = true;
        hotel9.restaurantAvailable = true;
        hotel9.hotelCode = "HTL109";
        hotel9.website = "www.snowpeakmanali.com";
        hotel9.membershipAvailable = false;

        System.out.println("After Initialization of Hotel9");
        System.out.println("Hotel ID is " + hotel9.hotelId);
        System.out.println("Hotel Name is " + hotel9.hotelName);
        System.out.println("Location is " + hotel9.location);
        System.out.println("Total Rooms are " + hotel9.totalRooms);
        System.out.println("Staff Count is " + hotel9.staffCount);
        System.out.println("Wifi Available " + hotel9.hasWifi);
        System.out.println("Pool Available " + hotel9.hasPool);
        System.out.println("Gym Available " + hotel9.hasGym);
        System.out.println("AC Available " + hotel9.hasAC);
        System.out.println("Open Today " + hotel9.openToday);
        System.out.println("Manager Name " + hotel9.managerName);
        System.out.println("Check-In Time " + hotel9.checkInTime);
        System.out.println("Check-Out Time " + hotel9.checkOutTime);
        System.out.println("Rating " + hotel9.rating);
        System.out.println("Contact Number " + hotel9.contactNumber);
        System.out.println("Email ID " + hotel9.email);
        System.out.println("City " + hotel9.city);
        System.out.println("State " + hotel9.state);
        System.out.println("Country " + hotel9.country);
        System.out.println("Established Year " + hotel9.establishedYear);
        System.out.println("Parking Available " + hotel9.parkingAvailable);
        System.out.println("Restaurant Available " + hotel9.restaurantAvailable);
        System.out.println("Hotel Code " + hotel9.hotelCode);
        System.out.println("Website " + hotel9.website);
        System.out.println("Membership Available " + hotel9.membershipAvailable);

        Hotel hotel10 = new Hotel();

        System.out.println("Before Initialization of Hotel10");
        System.out.println("Hotel ID is " + hotel10.hotelId);
        System.out.println("Hotel Name is " + hotel10.hotelName);
        System.out.println("Location is " + hotel10.location);
        System.out.println("Total Rooms are " + hotel10.totalRooms);
        System.out.println("Staff Count is " + hotel10.staffCount);
        System.out.println("Wifi Available " + hotel10.hasWifi);
        System.out.println("Pool Available " + hotel10.hasPool);
        System.out.println("Gym Available " + hotel10.hasGym);
        System.out.println("AC Available " + hotel10.hasAC);
        System.out.println("Open Today " + hotel10.openToday);
        System.out.println("Manager Name " + hotel10.managerName);
        System.out.println("Check-In Time " + hotel10.checkInTime);
        System.out.println("Check-Out Time " + hotel10.checkOutTime);
        System.out.println("Rating " + hotel10.rating);
        System.out.println("Contact Number " + hotel10.contactNumber);
        System.out.println("Email ID " + hotel10.email);
        System.out.println("City " + hotel10.city);
        System.out.println("State " + hotel10.state);
        System.out.println("Country " + hotel10.country);
        System.out.println("Established Year " + hotel10.establishedYear);
        System.out.println("Parking Available " + hotel10.parkingAvailable);
        System.out.println("Restaurant Available " + hotel10.restaurantAvailable);
        System.out.println("Hotel Code " + hotel10.hotelCode);
        System.out.println("Website " + hotel10.website);
        System.out.println("Membership Available " + hotel10.membershipAvailable);

        hotel10.hotelId = 10;
        hotel10.hotelName = "River View";
        hotel10.location = "Tapovan";
        hotel10.totalRooms = 75;
        hotel10.staffCount = 35;
        hotel10.hasWifi = true;
        hotel10.hasPool = true;
        hotel10.hasGym = true;
        hotel10.hasAC = true;
        hotel10.openToday = true;
        hotel10.managerName = "Ravi Tyagi";
        hotel10.checkInTime = "1PM";
        hotel10.checkOutTime = "11AM";
        hotel10.rating = 4.5;
        hotel10.contactNumber = "9876500222";
        hotel10.email = "info@riverview.com";
        hotel10.city = "Rishikesh";
        hotel10.state = "Uttarakhand";
        hotel10.country = "India";
        hotel10.establishedYear = 2014;
        hotel10.parkingAvailable = true;
        hotel10.restaurantAvailable = true;
        hotel10.hotelCode = "HTL110";
        hotel10.website = "www.riverviewrishikesh.com";
        hotel10.membershipAvailable = false;

        System.out.println("After Initialization of Hotel10");
        System.out.println("Hotel ID is " + hotel10.hotelId);
        System.out.println("Hotel Name is " + hotel10.hotelName);
        System.out.println("Location is " + hotel10.location);
        System.out.println("Total Rooms are " + hotel10.totalRooms);
        System.out.println("Staff Count is " + hotel10.staffCount);
        System.out.println("Wifi Available " + hotel10.hasWifi);
        System.out.println("Pool Available " + hotel10.hasPool);
        System.out.println("Gym Available " + hotel10.hasGym);
        System.out.println("AC Available " + hotel10.hasAC);
        System.out.println("Open Today " + hotel10.openToday);
        System.out.println("Manager Name " + hotel10.managerName);
        System.out.println("Check-In Time " + hotel10.checkInTime);
        System.out.println("Check-Out Time " + hotel10.checkOutTime);
        System.out.println("Rating " + hotel10.rating);
        System.out.println("Contact Number " + hotel10.contactNumber);
        System.out.println("Email ID " + hotel10.email);
        System.out.println("City " + hotel10.city);
        System.out.println("State " + hotel10.state);
        System.out.println("Country " + hotel10.country);
        System.out.println("Established Year " + hotel10.establishedYear);
        System.out.println("Parking Available " + hotel10.parkingAvailable);
        System.out.println("Restaurant Available " + hotel10.restaurantAvailable);
        System.out.println("Hotel Code " + hotel10.hotelCode);
        System.out.println("Website " + hotel10.website);
        System.out.println("Membership Available " + hotel10.membershipAvailable);

        Hotel hotel11 = new Hotel();

        System.out.println("Before Initialization of Hotel11");
        System.out.println("Hotel ID is " + hotel11.hotelId);
        System.out.println("Hotel Name is " + hotel11.hotelName);
        System.out.println("Location is " + hotel11.location);
        System.out.println("Total Rooms are " + hotel11.totalRooms);
        System.out.println("Staff Count is " + hotel11.staffCount);
        System.out.println("Wifi Available " + hotel11.hasWifi);
        System.out.println("Pool Available " + hotel11.hasPool);
        System.out.println("Gym Available " + hotel11.hasGym);
        System.out.println("AC Available " + hotel11.hasAC);
        System.out.println("Open Today " + hotel11.openToday);
        System.out.println("Manager Name " + hotel11.managerName);
        System.out.println("Check-In Time " + hotel11.checkInTime);
        System.out.println("Check-Out Time " + hotel11.checkOutTime);
        System.out.println("Rating " + hotel11.rating);
        System.out.println("Contact Number " + hotel11.contactNumber);
        System.out.println("Email ID " + hotel11.email);
        System.out.println("City " + hotel11.city);
        System.out.println("State " + hotel11.state);
        System.out.println("Country " + hotel11.country);
        System.out.println("Established Year " + hotel11.establishedYear);
        System.out.println("Parking Available " + hotel11.parkingAvailable);
        System.out.println("Restaurant Available " + hotel11.restaurantAvailable);
        System.out.println("Hotel Code " + hotel11.hotelCode);
        System.out.println("Website " + hotel11.website);
        System.out.println("Membership Available " + hotel11.membershipAvailable);

        hotel11.hotelId = 11;
        hotel11.hotelName = "Ocean Pearl";
        hotel11.location = "Marine Drive";
        hotel11.totalRooms = 110;
        hotel11.staffCount = 55;
        hotel11.hasWifi = true;
        hotel11.hasPool = true;
        hotel11.hasGym = true;
        hotel11.hasAC = true;
        hotel11.openToday = true;
        hotel11.managerName = "George Mathew";
        hotel11.checkInTime = "2PM";
        hotel11.checkOutTime = "12PM";
        hotel11.rating = 4.6;
        hotel11.contactNumber = "9876500333";
        hotel11.email = "stay@oceanpearl.com";
        hotel11.city = "Kochi";
        hotel11.state = "Kerala";
        hotel11.country = "India";
        hotel11.establishedYear = 2017;
        hotel11.parkingAvailable = true;
        hotel11.restaurantAvailable = true;
        hotel11.hotelCode = "HTL111";
        hotel11.website = "www.oceanpearlkochi.com";
        hotel11.membershipAvailable = true;

        System.out.println("After Initialization of Hotel11");
        System.out.println("Hotel ID is " + hotel11.hotelId);
        System.out.println("Hotel Name is " + hotel11.hotelName);
        System.out.println("Location is " + hotel11.location);
        System.out.println("Total Rooms are " + hotel11.totalRooms);
        System.out.println("Staff Count is " + hotel11.staffCount);
        System.out.println("Wifi Available " + hotel11.hasWifi);
        System.out.println("Pool Available " + hotel11.hasPool);
        System.out.println("Gym Available " + hotel11.hasGym);
        System.out.println("AC Available " + hotel11.hasAC);
        System.out.println("Open Today " + hotel11.openToday);
        System.out.println("Manager Name " + hotel11.managerName);
        System.out.println("Check-In Time " + hotel11.checkInTime);
        System.out.println("Check-Out Time " + hotel11.checkOutTime);
        System.out.println("Rating " + hotel11.rating);
        System.out.println("Contact Number " + hotel11.contactNumber);
        System.out.println("Email ID " + hotel11.email);
        System.out.println("City " + hotel11.city);
        System.out.println("State " + hotel11.state);
        System.out.println("Country " + hotel11.country);
        System.out.println("Established Year " + hotel11.establishedYear);
        System.out.println("Parking Available " + hotel11.parkingAvailable);
        System.out.println("Restaurant Available " + hotel11.restaurantAvailable);
        System.out.println("Hotel Code " + hotel11.hotelCode);
        System.out.println("Website " + hotel11.website);
        System.out.println("Membership Available " + hotel11.membershipAvailable);

        Hotel hotel12 = new Hotel();

        System.out.println("Before Initialization of Hotel12");
        System.out.println("Hotel ID is " + hotel12.hotelId);
        System.out.println("Hotel Name is " + hotel12.hotelName);
        System.out.println("Location is " + hotel12.location);
        System.out.println("Total Rooms are " + hotel12.totalRooms);
        System.out.println("Staff Count is " + hotel12.staffCount);
        System.out.println("Wifi Available " + hotel12.hasWifi);
        System.out.println("Pool Available " + hotel12.hasPool);
        System.out.println("Gym Available " + hotel12.hasGym);
        System.out.println("AC Available " + hotel12.hasAC);
        System.out.println("Open Today " + hotel12.openToday);
        System.out.println("Manager Name " + hotel12.managerName);
        System.out.println("Check-In Time " + hotel12.checkInTime);
        System.out.println("Check-Out Time " + hotel12.checkOutTime);
        System.out.println("Rating " + hotel12.rating);
        System.out.println("Contact Number " + hotel12.contactNumber);
        System.out.println("Email ID " + hotel12.email);
        System.out.println("City " + hotel12.city);
        System.out.println("State " + hotel12.state);
        System.out.println("Country " + hotel12.country);
        System.out.println("Established Year " + hotel12.establishedYear);
        System.out.println("Parking Available " + hotel12.parkingAvailable);
        System.out.println("Restaurant Available " + hotel12.restaurantAvailable);
        System.out.println("Hotel Code " + hotel12.hotelCode);
        System.out.println("Website " + hotel12.website);
        System.out.println("Membership Available " + hotel12.membershipAvailable);

        hotel12.hotelId = 12;
        hotel12.hotelName = "Heritage Haveli";
        hotel12.location = "Old City";
        hotel12.totalRooms = 35;
        hotel12.staffCount = 20;
        hotel12.hasWifi = true;
        hotel12.hasPool = true;
        hotel12.hasGym = false;
        hotel12.hasAC = true;
        hotel12.openToday = true;
        hotel12.managerName = "Gajendra Singh";
        hotel12.checkInTime = "12PM";
        hotel12.checkOutTime = "11AM";
        hotel12.rating = 4.8;
        hotel12.contactNumber = "9876500444";
        hotel12.email = "info@heritagehaveli.com";
        hotel12.city = "Jodhpur";
        hotel12.state = "Rajasthan";
        hotel12.country = "India";
        hotel12.establishedYear = 1985;
        hotel12.parkingAvailable = true;
        hotel12.restaurantAvailable = true;
        hotel12.hotelCode = "HTL112";
        hotel12.website = "www.heritagehavelijodhpur.com";
        hotel12.membershipAvailable = false;

        System.out.println("After Initialization of Hotel12");
        System.out.println("Hotel ID is " + hotel12.hotelId);
        System.out.println("Hotel Name is " + hotel12.hotelName);
        System.out.println("Location is " + hotel12.location);
        System.out.println("Total Rooms are " + hotel12.totalRooms);
        System.out.println("Staff Count is " + hotel12.staffCount);
        System.out.println("Wifi Available " + hotel12.hasWifi);
        System.out.println("Pool Available " + hotel12.hasPool);
        System.out.println("Gym Available " + hotel12.hasGym);
        System.out.println("AC Available " + hotel12.hasAC);
        System.out.println("Open Today " + hotel12.openToday);
        System.out.println("Manager Name " + hotel12.managerName);
        System.out.println("Check-In Time " + hotel12.checkInTime);
        System.out.println("Check-Out Time " + hotel12.checkOutTime);
        System.out.println("Rating " + hotel12.rating);
        System.out.println("Contact Number " + hotel12.contactNumber);
        System.out.println("Email ID " + hotel12.email);
        System.out.println("City " + hotel12.city);
        System.out.println("State " + hotel12.state);
        System.out.println("Country " + hotel12.country);
        System.out.println("Established Year " + hotel12.establishedYear);
        System.out.println("Parking Available " + hotel12.parkingAvailable);
        System.out.println("Restaurant Available " + hotel12.restaurantAvailable);
        System.out.println("Hotel Code " + hotel12.hotelCode);
        System.out.println("Website " + hotel12.website);
        System.out.println("Membership Available " + hotel12.membershipAvailable);

        Hotel hotel13 = new Hotel();

        System.out.println("Before Initialization of Hotel13");
        System.out.println("Hotel ID is " + hotel13.hotelId);
        System.out.println("Hotel Name is " + hotel13.hotelName);
        System.out.println("Location is " + hotel13.location);
        System.out.println("Total Rooms are " + hotel13.totalRooms);
        System.out.println("Staff Count is " + hotel13.staffCount);
        System.out.println("Wifi Available " + hotel13.hasWifi);
        System.out.println("Pool Available " + hotel13.hasPool);
        System.out.println("Gym Available " + hotel13.hasGym);
        System.out.println("AC Available " + hotel13.hasAC);
        System.out.println("Open Today " + hotel13.openToday);
        System.out.println("Manager Name " + hotel13.managerName);
        System.out.println("Check-In Time " + hotel13.checkInTime);
        System.out.println("Check-Out Time " + hotel13.checkOutTime);
        System.out.println("Rating " + hotel13.rating);
        System.out.println("Contact Number " + hotel13.contactNumber);
        System.out.println("Email ID " + hotel13.email);
        System.out.println("City " + hotel13.city);
        System.out.println("State " + hotel13.state);
        System.out.println("Country " + hotel13.country);
        System.out.println("Established Year " + hotel13.establishedYear);
        System.out.println("Parking Available " + hotel13.parkingAvailable);
        System.out.println("Restaurant Available " + hotel13.restaurantAvailable);
        System.out.println("Hotel Code " + hotel13.hotelCode);
        System.out.println("Website " + hotel13.website);
        System.out.println("Membership Available " + hotel13.membershipAvailable);

        hotel13.hotelId = 13;
        hotel13.hotelName = "Tea Garden Resort";
        hotel13.location = "Happy Valley";
        hotel13.totalRooms = 60;
        hotel13.staffCount = 35;
        hotel13.hasWifi = true;
        hotel13.hasPool = false;
        hotel13.hasGym = false;
        hotel13.hasAC = false;
        hotel13.openToday = true;
        hotel13.managerName = "Prakash Gurung";
        hotel13.checkInTime = "1PM";
        hotel13.checkOutTime = "11AM";
        hotel13.rating = 4.5;
        hotel13.contactNumber = "9876500555";
        hotel13.email = "booking@teagarden.com";
        hotel13.city = "Darjeeling";
        hotel13.state = "West Bengal";
        hotel13.country = "India";
        hotel13.establishedYear = 1995;
        hotel13.parkingAvailable = true;
        hotel13.restaurantAvailable = true;
        hotel13.hotelCode = "HTL113";
        hotel13.website = "www.teagardenresort.com";
        hotel13.membershipAvailable = false;

        System.out.println("After Initialization of Hotel13");
        System.out.println("Hotel ID is " + hotel13.hotelId);
        System.out.println("Hotel Name is " + hotel13.hotelName);
        System.out.println("Location is " + hotel13.location);
        System.out.println("Total Rooms are " + hotel13.totalRooms);
        System.out.println("Staff Count is " + hotel13.staffCount);
        System.out.println("Wifi Available " + hotel13.hasWifi);
        System.out.println("Pool Available " + hotel13.hasPool);
        System.out.println("Gym Available " + hotel13.hasGym);
        System.out.println("AC Available " + hotel13.hasAC);
        System.out.println("Open Today " + hotel13.openToday);
        System.out.println("Manager Name " + hotel13.managerName);
        System.out.println("Check-In Time " + hotel13.checkInTime);
        System.out.println("Check-Out Time " + hotel13.checkOutTime);
        System.out.println("Rating " + hotel13.rating);
        System.out.println("Contact Number " + hotel13.contactNumber);
        System.out.println("Email ID " + hotel13.email);
        System.out.println("City " + hotel13.city);
        System.out.println("State " + hotel13.state);
        System.out.println("Country " + hotel13.country);
        System.out.println("Established Year " + hotel13.establishedYear);
        System.out.println("Parking Available " + hotel13.parkingAvailable);
        System.out.println("Restaurant Available " + hotel13.restaurantAvailable);
        System.out.println("Hotel Code " + hotel13.hotelCode);
        System.out.println("Website " + hotel13.website);
        System.out.println("Membership Available " + hotel13.membershipAvailable);

        Hotel hotel14 = new Hotel();

        System.out.println("Before Initialization of Hotel14");
        System.out.println("Hotel ID is " + hotel14.hotelId);
        System.out.println("Hotel Name is " + hotel14.hotelName);
        System.out.println("Location is " + hotel14.location);
        System.out.println("Total Rooms are " + hotel14.totalRooms);
        System.out.println("Staff Count is " + hotel14.staffCount);
        System.out.println("Wifi Available " + hotel14.hasWifi);
        System.out.println("Pool Available " + hotel14.hasPool);
        System.out.println("Gym Available " + hotel14.hasGym);
        System.out.println("AC Available " + hotel14.hasAC);
        System.out.println("Open Today " + hotel14.openToday);
        System.out.println("Manager Name " + hotel14.managerName);
        System.out.println("Check-In Time " + hotel14.checkInTime);
        System.out.println("Check-Out Time " + hotel14.checkOutTime);
        System.out.println("Rating " + hotel14.rating);
        System.out.println("Contact Number " + hotel14.contactNumber);
        System.out.println("Email ID " + hotel14.email);
        System.out.println("City " + hotel14.city);
        System.out.println("State " + hotel14.state);
        System.out.println("Country " + hotel14.country);
        System.out.println("Established Year " + hotel14.establishedYear);
        System.out.println("Parking Available " + hotel14.parkingAvailable);
        System.out.println("Restaurant Available " + hotel14.restaurantAvailable);
        System.out.println("Hotel Code " + hotel14.hotelCode);
        System.out.println("Website " + hotel14.website);
        System.out.println("Membership Available " + hotel14.membershipAvailable);

        hotel14.hotelId = 14;
        hotel14.hotelName = "Sunset Point";
        hotel14.location = "Cape Road";
        hotel14.totalRooms = 80;
        hotel14.staffCount = 40;
        hotel14.hasWifi = true;
        hotel14.hasPool = true;
        hotel14.hasGym = false;
        hotel14.hasAC = true;
        hotel14.openToday = true;
        hotel14.managerName = "Sundar Rajan";
        hotel14.checkInTime = "12PM";
        hotel14.checkOutTime = "11AM";
        hotel14.rating = 4.3;
        hotel14.contactNumber = "9876500666";
        hotel14.email = "stay@sunsetpoint.com";
        hotel14.city = "Kanyakumari";
        hotel14.state = "Tamil Nadu";
        hotel14.country = "India";
        hotel14.establishedYear = 2010;
        hotel14.parkingAvailable = true;
        hotel14.restaurantAvailable = true;
        hotel14.hotelCode = "HTL114";
        hotel14.website = "www.sunsetpointkk.com";
        hotel14.membershipAvailable = false;

        System.out.println("After Initialization of Hotel14");
        System.out.println("Hotel ID is " + hotel14.hotelId);
        System.out.println("Hotel Name is " + hotel14.hotelName);
        System.out.println("Location is " + hotel14.location);
        System.out.println("Total Rooms are " + hotel14.totalRooms);
        System.out.println("Staff Count is " + hotel14.staffCount);
        System.out.println("Wifi Available " + hotel14.hasWifi);
        System.out.println("Pool Available " + hotel14.hasPool);
        System.out.println("Gym Available " + hotel14.hasGym);
        System.out.println("AC Available " + hotel14.hasAC);
        System.out.println("Open Today " + hotel14.openToday);
        System.out.println("Manager Name " + hotel14.managerName);
        System.out.println("Check-In Time " + hotel14.checkInTime);
        System.out.println("Check-Out Time " + hotel14.checkOutTime);
        System.out.println("Rating " + hotel14.rating);
        System.out.println("Contact Number " + hotel14.contactNumber);
        System.out.println("Email ID " + hotel14.email);
        System.out.println("City " + hotel14.city);
        System.out.println("State " + hotel14.state);
        System.out.println("Country " + hotel14.country);
        System.out.println("Established Year " + hotel14.establishedYear);
        System.out.println("Parking Available " + hotel14.parkingAvailable);
        System.out.println("Restaurant Available " + hotel14.restaurantAvailable);
        System.out.println("Hotel Code " + hotel14.hotelCode);
        System.out.println("Website " + hotel14.website);
        System.out.println("Membership Available " + hotel14.membershipAvailable);

        Hotel hotel15 = new Hotel();

        System.out.println("Before Initialization of Hotel15");
        System.out.println("Hotel ID is " + hotel15.hotelId);
        System.out.println("Hotel Name is " + hotel15.hotelName);
        System.out.println("Location is " + hotel15.location);
        System.out.println("Total Rooms are " + hotel15.totalRooms);
        System.out.println("Staff Count is " + hotel15.staffCount);
        System.out.println("Wifi Available " + hotel15.hasWifi);
        System.out.println("Pool Available " + hotel15.hasPool);
        System.out.println("Gym Available " + hotel15.hasGym);
        System.out.println("AC Available " + hotel15.hasAC);
        System.out.println("Open Today " + hotel15.openToday);
        System.out.println("Manager Name " + hotel15.managerName);
        System.out.println("Check-In Time " + hotel15.checkInTime);
        System.out.println("Check-Out Time " + hotel15.checkOutTime);
        System.out.println("Rating " + hotel15.rating);
        System.out.println("Contact Number " + hotel15.contactNumber);
        System.out.println("Email ID " + hotel15.email);
        System.out.println("City " + hotel15.city);
        System.out.println("State " + hotel15.state);
        System.out.println("Country " + hotel15.country);
        System.out.println("Established Year " + hotel15.establishedYear);
        System.out.println("Parking Available " + hotel15.parkingAvailable);
        System.out.println("Restaurant Available " + hotel15.restaurantAvailable);
        System.out.println("Hotel Code " + hotel15.hotelCode);
        System.out.println("Website " + hotel15.website);
        System.out.println("Membership Available " + hotel15.membershipAvailable);

        hotel15.hotelId = 15;
        hotel15.hotelName = "Pine Tree Hotel";
        hotel15.location = "Police Bazaar";
        hotel15.totalRooms = 55;
        hotel15.staffCount = 28;
        hotel15.hasWifi = true;
        hotel15.hasPool = false;
        hotel15.hasGym = true;
        hotel15.hasAC = false;
        hotel15.openToday = true;
        hotel15.managerName = "David Syiem";
        hotel15.checkInTime = "2PM";
        hotel15.checkOutTime = "12PM";
        hotel15.rating = 4.1;
        hotel15.contactNumber = "9876500777";
        hotel15.email = "hello@pinetree.com";
        hotel15.city = "Shillong";
        hotel15.state = "Meghalaya";
        hotel15.country = "India";
        hotel15.establishedYear = 2004;
        hotel15.parkingAvailable = true;
        hotel15.restaurantAvailable = true;
        hotel15.hotelCode = "HTL115";
        hotel15.website = "www.pinetreeshillong.com";
        hotel15.membershipAvailable = false;

        System.out.println("After Initialization of Hotel15");
        System.out.println("Hotel ID is " + hotel15.hotelId);
        System.out.println("Hotel Name is " + hotel15.hotelName);
        System.out.println("Location is " + hotel15.location);
        System.out.println("Total Rooms are " + hotel15.totalRooms);
        System.out.println("Staff Count is " + hotel15.staffCount);
        System.out.println("Wifi Available " + hotel15.hasWifi);
        System.out.println("Pool Available " + hotel15.hasPool);
        System.out.println("Gym Available " + hotel15.hasGym);
        System.out.println("AC Available " + hotel15.hasAC);
        System.out.println("Open Today " + hotel15.openToday);
        System.out.println("Manager Name " + hotel15.managerName);
        System.out.println("Check-In Time " + hotel15.checkInTime);
        System.out.println("Check-Out Time " + hotel15.checkOutTime);
        System.out.println("Rating " + hotel15.rating);
        System.out.println("Contact Number " + hotel15.contactNumber);
        System.out.println("Email ID " + hotel15.email);
        System.out.println("City " + hotel15.city);
        System.out.println("State " + hotel15.state);
        System.out.println("Country " + hotel15.country);
        System.out.println("Established Year " + hotel15.establishedYear);
        System.out.println("Parking Available " + hotel15.parkingAvailable);
        System.out.println("Restaurant Available " + hotel15.restaurantAvailable);
        System.out.println("Hotel Code " + hotel15.hotelCode);
        System.out.println("Website " + hotel15.website);
        System.out.println("Membership Available " + hotel15.membershipAvailable);

        Hotel hotel16 = new Hotel();

        System.out.println("Before Initialization of Hotel16");
        System.out.println("Hotel ID is " + hotel16.hotelId);
        System.out.println("Hotel Name is " + hotel16.hotelName);
        System.out.println("Location is " + hotel16.location);
        System.out.println("Total Rooms are " + hotel16.totalRooms);
        System.out.println("Staff Count is " + hotel16.staffCount);
        System.out.println("Wifi Available " + hotel16.hasWifi);
        System.out.println("Pool Available " + hotel16.hasPool);
        System.out.println("Gym Available " + hotel16.hasGym);
        System.out.println("AC Available " + hotel16.hasAC);
        System.out.println("Open Today " + hotel16.openToday);
        System.out.println("Manager Name " + hotel16.managerName);
        System.out.println("Check-In Time " + hotel16.checkInTime);
        System.out.println("Check-Out Time " + hotel16.checkOutTime);
        System.out.println("Rating " + hotel16.rating);
        System.out.println("Contact Number " + hotel16.contactNumber);
        System.out.println("Email ID " + hotel16.email);
        System.out.println("City " + hotel16.city);
        System.out.println("State " + hotel16.state);
        System.out.println("Country " + hotel16.country);
        System.out.println("Established Year " + hotel16.establishedYear);
        System.out.println("Parking Available " + hotel16.parkingAvailable);
        System.out.println("Restaurant Available " + hotel16.restaurantAvailable);
        System.out.println("Hotel Code " + hotel16.hotelCode);
        System.out.println("Website " + hotel16.website);
        System.out.println("Membership Available " + hotel16.membershipAvailable);

        hotel16.hotelId = 16;
        hotel16.hotelName = "Backwater Retreat";
        hotel16.location = "Punnamada";
        hotel16.totalRooms = 30;
        hotel16.staffCount = 15;
        hotel16.hasWifi = true;
        hotel16.hasPool = false;
        hotel16.hasGym = false;
        hotel16.hasAC = true;
        hotel16.openToday = true;
        hotel16.managerName = "Arun Pillai";
        hotel16.checkInTime = "1PM";
        hotel16.checkOutTime = "11AM";
        hotel16.rating = 4.7;
        hotel16.contactNumber = "9876500888";
        hotel16.email = "info@backwaterretreat.com";
        hotel16.city = "Alleppey";
        hotel16.state = "Kerala";
        hotel16.country = "India";
        hotel16.establishedYear = 2009;
        hotel16.parkingAvailable = true;
        hotel16.restaurantAvailable = true;
        hotel16.hotelCode = "HTL116";
        hotel16.website = "www.backwaterretreat.com";
        hotel16.membershipAvailable = false;

        System.out.println("After Initialization of Hotel16");
        System.out.println("Hotel ID is " + hotel16.hotelId);
        System.out.println("Hotel Name is " + hotel16.hotelName);
        System.out.println("Location is " + hotel16.location);
        System.out.println("Total Rooms are " + hotel16.totalRooms);
        System.out.println("Staff Count is " + hotel16.staffCount);
        System.out.println("Wifi Available " + hotel16.hasWifi);
        System.out.println("Pool Available " + hotel16.hasPool);
        System.out.println("Gym Available " + hotel16.hasGym);
        System.out.println("AC Available " + hotel16.hasAC);
        System.out.println("Open Today " + hotel16.openToday);
        System.out.println("Manager Name " + hotel16.managerName);
        System.out.println("Check-In Time " + hotel16.checkInTime);
        System.out.println("Check-Out Time " + hotel16.checkOutTime);
        System.out.println("Rating " + hotel16.rating);
        System.out.println("Contact Number " + hotel16.contactNumber);
        System.out.println("Email ID " + hotel16.email);
        System.out.println("City " + hotel16.city);
        System.out.println("State " + hotel16.state);
        System.out.println("Country " + hotel16.country);
        System.out.println("Established Year " + hotel16.establishedYear);
        System.out.println("Parking Available " + hotel16.parkingAvailable);
        System.out.println("Restaurant Available " + hotel16.restaurantAvailable);
        System.out.println("Hotel Code " + hotel16.hotelCode);
        System.out.println("Website " + hotel16.website);
        System.out.println("Membership Available " + hotel16.membershipAvailable);

        Hotel hotel17 = new Hotel();

        System.out.println("Before Initialization of Hotel17");
        System.out.println("Hotel ID is " + hotel17.hotelId);
        System.out.println("Hotel Name is " + hotel17.hotelName);
        System.out.println("Location is " + hotel17.location);
        System.out.println("Total Rooms are " + hotel17.totalRooms);
        System.out.println("Staff Count is " + hotel17.staffCount);
        System.out.println("Wifi Available " + hotel17.hasWifi);
        System.out.println("Pool Available " + hotel17.hasPool);
        System.out.println("Gym Available " + hotel17.hasGym);
        System.out.println("AC Available " + hotel17.hasAC);
        System.out.println("Open Today " + hotel17.openToday);
        System.out.println("Manager Name " + hotel17.managerName);
        System.out.println("Check-In Time " + hotel17.checkInTime);
        System.out.println("Check-Out Time " + hotel17.checkOutTime);
        System.out.println("Rating " + hotel17.rating);
        System.out.println("Contact Number " + hotel17.contactNumber);
        System.out.println("Email ID " + hotel17.email);
        System.out.println("City " + hotel17.city);
        System.out.println("State " + hotel17.state);
        System.out.println("Country " + hotel17.country);
        System.out.println("Established Year " + hotel17.establishedYear);
        System.out.println("Parking Available " + hotel17.parkingAvailable);
        System.out.println("Restaurant Available " + hotel17.restaurantAvailable);
        System.out.println("Hotel Code " + hotel17.hotelCode);
        System.out.println("Website " + hotel17.website);
        System.out.println("Membership Available " + hotel17.membershipAvailable);

        hotel17.hotelId = 17;
        hotel17.hotelName = "Palm Grove";
        hotel17.location = "White Town";
        hotel17.totalRooms = 40;
        hotel17.staffCount = 20;
        hotel17.hasWifi = true;
        hotel17.hasPool = true;
        hotel17.hasGym = false;
        hotel17.hasAC = true;
        hotel17.openToday = true;
        hotel17.managerName = "Kumar Swamy";
        hotel17.checkInTime = "12PM";
        hotel17.checkOutTime = "11AM";
        hotel17.rating = 4.4;
        hotel17.contactNumber = "9876500999";
        hotel17.email = "hello@palmgrove.com";
        hotel17.city = "Pondicherry";
        hotel17.state = "Puducherry";
        hotel17.country = "India";
        hotel17.establishedYear = 2013;
        hotel17.parkingAvailable = true;
        hotel17.restaurantAvailable = true;
        hotel17.hotelCode = "HTL117";
        hotel17.website = "www.palmgrovepondicherry.com";
        hotel17.membershipAvailable = false;

        System.out.println("After Initialization of Hotel17");
        System.out.println("Hotel ID is " + hotel17.hotelId);
        System.out.println("Hotel Name is " + hotel17.hotelName);
        System.out.println("Location is " + hotel17.location);
        System.out.println("Total Rooms are " + hotel17.totalRooms);
        System.out.println("Staff Count is " + hotel17.staffCount);
        System.out.println("Wifi Available " + hotel17.hasWifi);
        System.out.println("Pool Available " + hotel17.hasPool);
        System.out.println("Gym Available " + hotel17.hasGym);
        System.out.println("AC Available " + hotel17.hasAC);
        System.out.println("Open Today " + hotel17.openToday);
        System.out.println("Manager Name " + hotel17.managerName);
        System.out.println("Check-In Time " + hotel17.checkInTime);
        System.out.println("Check-Out Time " + hotel17.checkOutTime);
        System.out.println("Rating " + hotel17.rating);
        System.out.println("Contact Number " + hotel17.contactNumber);
        System.out.println("Email ID " + hotel17.email);
        System.out.println("City " + hotel17.city);
        System.out.println("State " + hotel17.state);
        System.out.println("Country " + hotel17.country);
        System.out.println("Established Year " + hotel17.establishedYear);
        System.out.println("Parking Available " + hotel17.parkingAvailable);
        System.out.println("Restaurant Available " + hotel17.restaurantAvailable);
        System.out.println("Hotel Code " + hotel17.hotelCode);
        System.out.println("Website " + hotel17.website);
        System.out.println("Membership Available " + hotel17.membershipAvailable);

        Hotel hotel18 = new Hotel();

        System.out.println("Before Initialization of Hotel18");
        System.out.println("Hotel ID is " + hotel18.hotelId);
        System.out.println("Hotel Name is " + hotel18.hotelName);
        System.out.println("Location is " + hotel18.location);
        System.out.println("Total Rooms are " + hotel18.totalRooms);
        System.out.println("Staff Count is " + hotel18.staffCount);
        System.out.println("Wifi Available " + hotel18.hasWifi);
        System.out.println("Pool Available " + hotel18.hasPool);
        System.out.println("Gym Available " + hotel18.hasGym);
        System.out.println("AC Available " + hotel18.hasAC);
        System.out.println("Open Today " + hotel18.openToday);
        System.out.println("Manager Name " + hotel18.managerName);
        System.out.println("Check-In Time " + hotel18.checkInTime);
        System.out.println("Check-Out Time " + hotel18.checkOutTime);
        System.out.println("Rating " + hotel18.rating);
        System.out.println("Contact Number " + hotel18.contactNumber);
        System.out.println("Email ID " + hotel18.email);
        System.out.println("City " + hotel18.city);
        System.out.println("State " + hotel18.state);
        System.out.println("Country " + hotel18.country);
        System.out.println("Established Year " + hotel18.establishedYear);
        System.out.println("Parking Available " + hotel18.parkingAvailable);
        System.out.println("Restaurant Available " + hotel18.restaurantAvailable);
        System.out.println("Hotel Code " + hotel18.hotelCode);
        System.out.println("Website " + hotel18.website);
        System.out.println("Membership Available " + hotel18.membershipAvailable);

        hotel18.hotelId = 18;
        hotel18.hotelName = "Golden Sands";
        hotel18.location = "Marine Parade";
        hotel18.totalRooms = 150;
        hotel18.staffCount = 75;
        hotel18.hasWifi = true;
        hotel18.hasPool = true;
        hotel18.hasGym = true;
        hotel18.hasAC = true;
        hotel18.openToday = true;
        hotel18.managerName = "Subhash Das";
        hotel18.checkInTime = "12PM";
        hotel18.checkOutTime = "11AM";
        hotel18.rating = 4.2;
        hotel18.contactNumber = "9876500100";
        hotel18.email = "info@goldensands.com";
        hotel18.city = "Puri";
        hotel18.state = "Odisha";
        hotel18.country = "India";
        hotel18.establishedYear = 2000;
        hotel18.parkingAvailable = true;
        hotel18.restaurantAvailable = true;
        hotel18.hotelCode = "HTL118";
        hotel18.website = "www.goldensandspuri.com";
        hotel18.membershipAvailable = false;

        System.out.println("After Initialization of Hotel18");
        System.out.println("Hotel ID is " + hotel18.hotelId);
        System.out.println("Hotel Name is " + hotel18.hotelName);
        System.out.println("Location is " + hotel18.location);
        System.out.println("Total Rooms are " + hotel18.totalRooms);
        System.out.println("Staff Count is " + hotel18.staffCount);
        System.out.println("Wifi Available " + hotel18.hasWifi);
        System.out.println("Pool Available " + hotel18.hasPool);
        System.out.println("Gym Available " + hotel18.hasGym);
        System.out.println("AC Available " + hotel18.hasAC);
        System.out.println("Open Today " + hotel18.openToday);
        System.out.println("Manager Name " + hotel18.managerName);
        System.out.println("Check-In Time " + hotel18.checkInTime);
        System.out.println("Check-Out Time " + hotel18.checkOutTime);
        System.out.println("Rating " + hotel18.rating);
        System.out.println("Contact Number " + hotel18.contactNumber);
        System.out.println("Email ID " + hotel18.email);
        System.out.println("City " + hotel18.city);
        System.out.println("State " + hotel18.state);
        System.out.println("Country " + hotel18.country);
        System.out.println("Established Year " + hotel18.establishedYear);
        System.out.println("Parking Available " + hotel18.parkingAvailable);
        System.out.println("Restaurant Available " + hotel18.restaurantAvailable);
        System.out.println("Hotel Code " + hotel18.hotelCode);
        System.out.println("Website " + hotel18.website);
        System.out.println("Membership Available " + hotel18.membershipAvailable);

        Hotel hotel19 = new Hotel();

        System.out.println("Before Initialization of Hotel19");
        System.out.println("Hotel ID is " + hotel19.hotelId);
        System.out.println("Hotel Name is " + hotel19.hotelName);
        System.out.println("Location is " + hotel19.location);
        System.out.println("Total Rooms are " + hotel19.totalRooms);
        System.out.println("Staff Count is " + hotel19.staffCount);
        System.out.println("Wifi Available " + hotel19.hasWifi);
        System.out.println("Pool Available " + hotel19.hasPool);
        System.out.println("Gym Available " + hotel19.hasGym);
        System.out.println("AC Available " + hotel19.hasAC);
        System.out.println("Open Today " + hotel19.openToday);
        System.out.println("Manager Name " + hotel19.managerName);
        System.out.println("Check-In Time " + hotel19.checkInTime);
        System.out.println("Check-Out Time " + hotel19.checkOutTime);
        System.out.println("Rating " + hotel19.rating);
        System.out.println("Contact Number " + hotel19.contactNumber);
        System.out.println("Email ID " + hotel19.email);
        System.out.println("City " + hotel19.city);
        System.out.println("State " + hotel19.state);
        System.out.println("Country " + hotel19.country);
        System.out.println("Established Year " + hotel19.establishedYear);
        System.out.println("Parking Available " + hotel19.parkingAvailable);
        System.out.println("Restaurant Available " + hotel19.restaurantAvailable);
        System.out.println("Hotel Code " + hotel19.hotelCode);
        System.out.println("Website " + hotel19.website);
        System.out.println("Membership Available " + hotel19.membershipAvailable);

        hotel19.hotelId = 19;
        hotel19.hotelName = "Valley View";
        hotel19.location = "Boulevard Road";
        hotel19.totalRooms = 90;
        hotel19.staffCount = 45;
        hotel19.hasWifi = true;
        hotel19.hasPool = false;
        hotel19.hasGym = true;
        hotel19.hasAC = false;
        hotel19.openToday = true;
        hotel19.managerName = "Tariq Ahmed";
        hotel19.checkInTime = "2PM";
        hotel19.checkOutTime = "12PM";
        hotel19.rating = 4.6;
        hotel19.contactNumber = "9876500200";
        hotel19.email = "stay@valleyview.com";
        hotel19.city = "Srinagar";
        hotel19.state = "Jammu and Kashmir";
        hotel19.country = "India";
        hotel19.establishedYear = 2007;
        hotel19.parkingAvailable = true;
        hotel19.restaurantAvailable = true;
        hotel19.hotelCode = "HTL119";
        hotel19.website = "www.valleyviewsrinagar.com";
        hotel19.membershipAvailable = true;

        System.out.println("After Initialization of Hotel19");
        System.out.println("Hotel ID is " + hotel19.hotelId);
        System.out.println("Hotel Name is " + hotel19.hotelName);
        System.out.println("Location is " + hotel19.location);
        System.out.println("Total Rooms are " + hotel19.totalRooms);
        System.out.println("Staff Count is " + hotel19.staffCount);
        System.out.println("Wifi Available " + hotel19.hasWifi);
        System.out.println("Pool Available " + hotel19.hasPool);
        System.out.println("Gym Available " + hotel19.hasGym);
        System.out.println("AC Available " + hotel19.hasAC);
        System.out.println("Open Today " + hotel19.openToday);
        System.out.println("Manager Name " + hotel19.managerName);
        System.out.println("Check-In Time " + hotel19.checkInTime);
        System.out.println("Check-Out Time " + hotel19.checkOutTime);
        System.out.println("Rating " + hotel19.rating);
        System.out.println("Contact Number " + hotel19.contactNumber);
        System.out.println("Email ID " + hotel19.email);
        System.out.println("City " + hotel19.city);
        System.out.println("State " + hotel19.state);
        System.out.println("Country " + hotel19.country);
        System.out.println("Established Year " + hotel19.establishedYear);
        System.out.println("Parking Available " + hotel19.parkingAvailable);
        System.out.println("Restaurant Available " + hotel19.restaurantAvailable);
        System.out.println("Hotel Code " + hotel19.hotelCode);
        System.out.println("Website " + hotel19.website);
        System.out.println("Membership Available " + hotel19.membershipAvailable);

        Hotel hotel20 = new Hotel();

        System.out.println("Before Initialization of Hotel20");
        System.out.println("Hotel ID is " + hotel20.hotelId);
        System.out.println("Hotel Name is " + hotel20.hotelName);
        System.out.println("Location is " + hotel20.location);
        System.out.println("Total Rooms are " + hotel20.totalRooms);
        System.out.println("Staff Count is " + hotel20.staffCount);
        System.out.println("Wifi Available " + hotel20.hasWifi);
        System.out.println("Pool Available " + hotel20.hasPool);
        System.out.println("Gym Available " + hotel20.hasGym);
        System.out.println("AC Available " + hotel20.hasAC);
        System.out.println("Open Today " + hotel20.openToday);
        System.out.println("Manager Name " + hotel20.managerName);
        System.out.println("Check-In Time " + hotel20.checkInTime);
        System.out.println("Check-Out Time " + hotel20.checkOutTime);
        System.out.println("Rating " + hotel20.rating);
        System.out.println("Contact Number " + hotel20.contactNumber);
        System.out.println("Email ID " + hotel20.email);
        System.out.println("City " + hotel20.city);
        System.out.println("State " + hotel20.state);
        System.out.println("Country " + hotel20.country);
        System.out.println("Established Year " + hotel20.establishedYear);
        System.out.println("Parking Available " + hotel20.parkingAvailable);
        System.out.println("Restaurant Available " + hotel20.restaurantAvailable);
        System.out.println("Hotel Code " + hotel20.hotelCode);
        System.out.println("Website " + hotel20.website);
        System.out.println("Membership Available " + hotel20.membershipAvailable);

        hotel20.hotelId = 20;
        hotel20.hotelName = "Cloud Nine";
        hotel20.location = "Camel's Back Road";
        hotel20.totalRooms = 65;
        hotel20.staffCount = 30;
        hotel20.hasWifi = true;
        hotel20.hasPool = false;
        hotel20.hasGym = false;
        hotel20.hasAC = false;
        hotel20.openToday = true;
        hotel20.managerName = "Rakesh Negi";
        hotel20.checkInTime = "1PM";
        hotel20.checkOutTime = "11AM";
        hotel20.rating = 4.3;
        hotel20.contactNumber = "9876500300";
        hotel20.email = "hello@cloudnine.com";
        hotel20.city = "Mussoorie";
        hotel20.state = "Uttarakhand";
        hotel20.country = "India";
        hotel20.establishedYear = 2018;
        hotel20.parkingAvailable = true;
        hotel20.restaurantAvailable = true;
        hotel20.hotelCode = "HTL120";
        hotel20.website = "www.cloudninemussoorie.com";
        hotel20.membershipAvailable = false;

        System.out.println("After Initialization of Hotel20");
        System.out.println("Hotel ID is " + hotel20.hotelId);
        System.out.println("Hotel Name is " + hotel20.hotelName);
        System.out.println("Location is " + hotel20.location);
        System.out.println("Total Rooms are " + hotel20.totalRooms);
        System.out.println("Staff Count is " + hotel20.staffCount);
        System.out.println("Wifi Available " + hotel20.hasWifi);
        System.out.println("Pool Available " + hotel20.hasPool);
        System.out.println("Gym Available " + hotel20.hasGym);
        System.out.println("AC Available " + hotel20.hasAC);
        System.out.println("Open Today " + hotel20.openToday);
        System.out.println("Manager Name " + hotel20.managerName);
        System.out.println("Check-In Time " + hotel20.checkInTime);
        System.out.println("Check-Out Time " + hotel20.checkOutTime);
        System.out.println("Rating " + hotel20.rating);
        System.out.println("Contact Number " + hotel20.contactNumber);
        System.out.println("Email ID " + hotel20.email);
        System.out.println("City " + hotel20.city);
        System.out.println("State " + hotel20.state);
        System.out.println("Country " + hotel20.country);
        System.out.println("Established Year " + hotel20.establishedYear);
        System.out.println("Parking Available " + hotel20.parkingAvailable);
        System.out.println("Restaurant Available " + hotel20.restaurantAvailable);
        System.out.println("Hotel Code " + hotel20.hotelCode);
        System.out.println("Website " + hotel20.website);
        System.out.println("Membership Available " + hotel20.membershipAvailable);

    }
}