class LibraryExecutor {
public static void main(String[] args){
Library library1 = new Library();

System.out.println("Before Initialization of Library1");

System.out.println("Library ID is " + library1.libraryId);
System.out.println("Library Name is " + library1.libraryName);
System.out.println("Library Location is " + library1.location);
System.out.println("Total Books are " + library1.totalBooks);
System.out.println("Staff Count is " + library1.staffCount);
System.out.println("Wifi Available " + library1.hasWifi);
System.out.println("Digital Section Available " + library1.hasDigitalSection);
System.out.println("Reading Room Available " + library1.hasReadingRoom);
System.out.println("AC Available " + library1.hasAC);
System.out.println("Is Library Open Today " + library1.openToday);
System.out.println("Librarian Name " + library1.librarianName);
System.out.println("Opening Time " + library1.openingTime);
System.out.println("Closing Time " + library1.closingTime);
System.out.println("Library Rating " + library1.rating);
System.out.println("Contact Number " + library1.contactNumber);
System.out.println("Email ID " + library1.email);
System.out.println("City " + library1.city);
System.out.println("State " + library1.state);
System.out.println("Country " + library1.country);
System.out.println("Established Year " + library1.establishedYear);
System.out.println("Parking Available " + library1.parkingAvailable);
System.out.println("Cafeteria Available " + library1.cafeteriaAvailable);
System.out.println("Library Code " + library1.libraryCode);
System.out.println("Website " + library1.website);
System.out.println("Membership Available " + library1.membershipAvailable);

library1.libraryId = 1;
library1.libraryName = "Central Library";
library1.location = "Mangalore";
library1.totalBooks = 50000;
library1.staffCount = 20;
library1.hasWifi = true;
library1.hasDigitalSection = true;
library1.hasReadingRoom = true;
library1.hasAC = true;
library1.openToday = true;
library1.librarianName = "Ravi";
library1.openingTime = "8AM";
library1.closingTime = "9PM";
library1.rating = 4.5;
library1.contactNumber = "9876543210";
library1.email = "central@library.com";
library1.city = "Mangalore";
library1.state = "Karnataka";
library1.country = "India";
library1.establishedYear = 1990;
library1.parkingAvailable = true;
library1.cafeteriaAvailable = true;
library1.libraryCode = "LIB101";
library1.website = "www.centrallibrary.com";
library1.membershipAvailable = true;

System.out.println("After Initialization of Library1");

System.out.println("Library ID is " + library1.libraryId);
System.out.println("Library Name is " + library1.libraryName);
System.out.println("Library Location is " + library1.location);
System.out.println("Total Books are " + library1.totalBooks);
System.out.println("Staff Count is " + library1.staffCount);
System.out.println("Wifi Available " + library1.hasWifi);
System.out.println("Digital Section Available " + library1.hasDigitalSection);
System.out.println("Reading Room Available " + library1.hasReadingRoom);
System.out.println("AC Available " + library1.hasAC);
System.out.println("Is Library Open Today " + library1.openToday);
System.out.println("Librarian Name " + library1.librarianName);
System.out.println("Opening Time " + library1.openingTime);
System.out.println("Closing Time " + library1.closingTime);
System.out.println("Library Rating " + library1.rating);
System.out.println("Contact Number " + library1.contactNumber);
System.out.println("Email ID " + library1.email);
System.out.println("City " + library1.city);
System.out.println("State " + library1.state);
System.out.println("Country " + library1.country);
System.out.println("Established Year " + library1.establishedYear);
System.out.println("Parking Available " + library1.parkingAvailable);
System.out.println("Cafeteria Available " + library1.cafeteriaAvailable);
System.out.println("Library Code " + library1.libraryCode);
System.out.println("Website " + library1.website);
System.out.println("Membership Available " + library1.membershipAvailable);

Library library2 = new Library();

System.out.println("Before Initialization of Library2");

System.out.println("Library ID is " + library2.libraryId);
System.out.println("Library Name is " + library2.libraryName);
System.out.println("Library Location is " + library2.location);
System.out.println("Total Books are " + library2.totalBooks);
System.out.println("Staff Count is " + library2.staffCount);
System.out.println("Wifi Available " + library2.hasWifi);
System.out.println("Digital Section Available " + library2.hasDigitalSection);
System.out.println("Reading Room Available " + library2.hasReadingRoom);
System.out.println("AC Available " + library2.hasAC);
System.out.println("Is Library Open Today " + library2.openToday);
System.out.println("Librarian Name " + library2.librarianName);
System.out.println("Opening Time " + library2.openingTime);
System.out.println("Closing Time " + library2.closingTime);
System.out.println("Library Rating " + library2.rating);
System.out.println("Contact Number " + library2.contactNumber);
System.out.println("Email ID " + library2.email);
System.out.println("City " + library2.city);
System.out.println("State " + library2.state);
System.out.println("Country " + library2.country);
System.out.println("Established Year " + library2.establishedYear);
System.out.println("Parking Available " + library2.parkingAvailable);
System.out.println("Cafeteria Available " + library2.cafeteriaAvailable);
System.out.println("Library Code " + library2.libraryCode);
System.out.println("Website " + library2.website);
System.out.println("Membership Available " + library2.membershipAvailable);


library2.libraryId = 2;
library2.libraryName = "City Library";
library2.location = "Bangalore";
library2.totalBooks = 35000;
library2.staffCount = 15;
library2.hasWifi = true;
library2.hasDigitalSection = true;
library2.hasReadingRoom = true;
library2.hasAC = false;
library2.openToday = true;
library2.librarianName = "Suresh";
library2.openingTime = "9AM";
library2.closingTime = "8PM";
library2.rating = 4.2;
library2.contactNumber = "9123456789";
library2.email = "city@library.com";
library2.city = "Bangalore";
library2.state = "Karnataka";
library2.country = "India";
library2.establishedYear = 2000;
library2.parkingAvailable = true;
library2.cafeteriaAvailable = false;
library2.libraryCode = "LIB102";
library2.website = "www.citylibrary.com";
library2.membershipAvailable = true;

System.out.println("After Initialization of Library2");

System.out.println("Library ID is " + library2.libraryId);
System.out.println("Library Name is " + library2.libraryName);
System.out.println("Library Location is " + library2.location);
System.out.println("Total Books are " + library2.totalBooks);
System.out.println("Staff Count is " + library2.staffCount);
System.out.println("Wifi Available " + library2.hasWifi);
System.out.println("Digital Section Available " + library2.hasDigitalSection);
System.out.println("Reading Room Available " + library2.hasReadingRoom);
System.out.println("AC Available " + library2.hasAC);
System.out.println("Is Library Open Today " + library2.openToday);
System.out.println("Librarian Name " + library2.librarianName);
System.out.println("Opening Time " + library2.openingTime);
System.out.println("Closing Time " + library2.closingTime);
System.out.println("Library Rating " + library2.rating);
System.out.println("Contact Number " + library2.contactNumber);
System.out.println("Email ID " + library2.email);
System.out.println("City " + library2.city);
System.out.println("State " + library2.state);
System.out.println("Country " + library2.country);
System.out.println("Established Year " + library2.establishedYear);
System.out.println("Parking Available " + library2.parkingAvailable);
System.out.println("Cafeteria Available " + library2.cafeteriaAvailable);
System.out.println("Library Code " + library2.libraryCode);
System.out.println("Website " + library2.website);
System.out.println("Membership Available " + library2.membershipAvailable);

Library library3 = new Library();

System.out.println("Before Initialization of Library3");

System.out.println("Library ID is " + library3.libraryId);
System.out.println("Library Name is " + library3.libraryName);
System.out.println("Library Location is " + library3.location);
System.out.println("Total Books are " + library3.totalBooks);
System.out.println("Staff Count is " + library3.staffCount);
System.out.println("Wifi Available " + library3.hasWifi);
System.out.println("Digital Section Available " + library3.hasDigitalSection);
System.out.println("Reading Room Available " + library3.hasReadingRoom);
System.out.println("AC Available " + library3.hasAC);
System.out.println("Is Library Open Today " + library3.openToday);
System.out.println("Librarian Name " + library3.librarianName);
System.out.println("Opening Time " + library3.openingTime);
System.out.println("Closing Time " + library3.closingTime);
System.out.println("Library Rating " + library3.rating);
System.out.println("Contact Number " + library3.contactNumber);
System.out.println("Email ID " + library3.email);
System.out.println("City " + library3.city);
System.out.println("State " + library3.state);
System.out.println("Country " + library3.country);
System.out.println("Established Year " + library3.establishedYear);
System.out.println("Parking Available " + library3.parkingAvailable);
System.out.println("Cafeteria Available " + library3.cafeteriaAvailable);
System.out.println("Library Code " + library3.libraryCode);
System.out.println("Website " + library3.website);
System.out.println("Membership Available " + library3.membershipAvailable);

library3.libraryId = 3;
library3.libraryName = "District Library";
library3.location = "Udupi";
library3.totalBooks = 20000;
library3.staffCount = 10;
library3.hasWifi = true;
library3.hasDigitalSection = false;
library3.hasReadingRoom = true;
library3.hasAC = false;
library3.openToday = true;
library3.librarianName = "Anil";
library3.openingTime = "9AM";
library3.closingTime = "7PM";
library3.rating = 4.0;
library3.contactNumber = "9988776655";
library3.email = "district@library.com";
library3.city = "Udupi";
library3.state = "Karnataka";
library3.country = "India";
library3.establishedYear = 1995;
library3.parkingAvailable = true;
library3.cafeteriaAvailable = false;
library3.libraryCode = "LIB103";
library3.website = "www.districtlibrary.com";
library3.membershipAvailable = true;

System.out.println("After Initialization of Library3");

System.out.println("Library ID is " + library3.libraryId);
System.out.println("Library Name is " + library3.libraryName);
System.out.println("Library Location is " + library3.location);
System.out.println("Total Books are " + library3.totalBooks);
System.out.println("Staff Count is " + library3.staffCount);
System.out.println("Wifi Available " + library3.hasWifi);
System.out.println("Digital Section Available " + library3.hasDigitalSection);
System.out.println("Reading Room Available " + library3.hasReadingRoom);
System.out.println("AC Available " + library3.hasAC);
System.out.println("Is Library Open Today " + library3.openToday);
System.out.println("Librarian Name " + library3.librarianName);
System.out.println("Opening Time " + library3.openingTime);
System.out.println("Closing Time " + library3.closingTime);
System.out.println("Library Rating " + library3.rating);
System.out.println("Contact Number " + library3.contactNumber);
System.out.println("Email ID " + library3.email);
System.out.println("City " + library3.city);
System.out.println("State " + library3.state);
System.out.println("Country " + library3.country);
System.out.println("Established Year " + library3.establishedYear);
System.out.println("Parking Available " + library3.parkingAvailable);
System.out.println("Cafeteria Available " + library3.cafeteriaAvailable);
System.out.println("Library Code " + library3.libraryCode);
System.out.println("Website " + library3.website);
System.out.println("Membership Available " + library3.membershipAvailable);

Library library4 = new Library();

System.out.println("Before Initialization of Library4");

System.out.println("Library ID is " + library4.libraryId);
System.out.println("Library Name is " + library4.libraryName);
System.out.println("Library Location is " + library4.location);
System.out.println("Total Books are " + library4.totalBooks);
System.out.println("Staff Count is " + library4.staffCount);

library4.libraryId = 4;
library4.libraryName = "Public Library";
library4.location = "Mysore";
library4.totalBooks = 25000;
library4.staffCount = 12;
library4.hasWifi = true;
library4.hasDigitalSection = true;
library4.hasReadingRoom = true;
library4.hasAC = false;
library4.openToday = true;
library4.librarianName = "Kiran";
library4.openingTime = "8AM";
library4.closingTime = "8PM";
library4.rating = 4.1;
library4.contactNumber = "9001122334";
library4.email = "public@library.com";
library4.city = "Mysore";
library4.state = "Karnataka";
library4.country = "India";
library4.establishedYear = 1998;
library4.parkingAvailable = true;
library4.cafeteriaAvailable = true;
library4.libraryCode = "LIB104";
library4.website = "www.publiclibrary.com";
library4.membershipAvailable = true;

System.out.println("After Initialization of Library4");

System.out.println("Library ID is " + library4.libraryId);
System.out.println("Library Name is " + library4.libraryName);
System.out.println("Library Location is " + library4.location);
System.out.println("Total Books are " + library4.totalBooks);
System.out.println("Staff Count is " + library4.staffCount);
System.out.println("City is " + library4.city);

Library library5 = new Library();

System.out.println("Before Initialization of Library5");

System.out.println("Library ID is " + library5.libraryId);
System.out.println("Library Name is " + library5.libraryName);
System.out.println("Library Location is " + library5.location);
System.out.println("Total Books are " + library5.totalBooks);
System.out.println("Staff Count is " + library5.staffCount);
System.out.println("Wifi Available " + library5.hasWifi);
System.out.println("Digital Section Available " + library5.hasDigitalSection);
System.out.println("Reading Room Available " + library5.hasReadingRoom);
System.out.println("AC Available " + library5.hasAC);
System.out.println("Is Library Open Today " + library5.openToday);
System.out.println("Librarian Name " + library5.librarianName);
System.out.println("Opening Time " + library5.openingTime);
System.out.println("Closing Time " + library5.closingTime);
System.out.println("Library Rating " + library5.rating);
System.out.println("Contact Number " + library5.contactNumber);
System.out.println("Email ID " + library5.email);
System.out.println("City " + library5.city);
System.out.println("State " + library5.state);
System.out.println("Country " + library5.country);
System.out.println("Established Year " + library5.establishedYear);
System.out.println("Parking Available " + library5.parkingAvailable);
System.out.println("Cafeteria Available " + library5.cafeteriaAvailable);
System.out.println("Library Code " + library5.libraryCode);
System.out.println("Website " + library5.website);
System.out.println("Membership Available " + library5.membershipAvailable);

library5.libraryId = 5;
library5.libraryName = "University Library";
library5.location = "Manipal";
library5.totalBooks = 60000;
library5.staffCount = 30;
library5.hasWifi = true;
library5.hasDigitalSection = true;
library5.hasReadingRoom = true;
library5.hasAC = true;
library5.openToday = true;
library5.librarianName = "Shankar";
library5.openingTime = "8AM";
library5.closingTime = "10PM";
library5.rating = 4.8;
library5.contactNumber = "9012345678";
library5.email = "university@library.com";
library5.city = "Manipal";
library5.state = "Karnataka";
library5.country = "India";
library5.establishedYear = 1985;
library5.parkingAvailable = true;
library5.cafeteriaAvailable = true;
library5.libraryCode = "LIB105";
library5.website = "www.universitylibrary.com";
library5.membershipAvailable = true;

System.out.println("After Initialization of Library5");

System.out.println("Library ID is " + library5.libraryId);
System.out.println("Library Name is " + library5.libraryName);
System.out.println("Library Location is " + library5.location);
System.out.println("Total Books are " + library5.totalBooks);
System.out.println("Staff Count is " + library5.staffCount);
System.out.println("Wifi Available " + library5.hasWifi);
System.out.println("Digital Section Available " + library5.hasDigitalSection);
System.out.println("Reading Room Available " + library5.hasReadingRoom);
System.out.println("AC Available " + library5.hasAC);
System.out.println("Is Library Open Today " + library5.openToday);
System.out.println("Librarian Name " + library5.librarianName);
System.out.println("Opening Time " + library5.openingTime);
System.out.println("Closing Time " + library5.closingTime);
System.out.println("Library Rating " + library5.rating);
System.out.println("Contact Number " + library5.contactNumber);
System.out.println("Email ID " + library5.email);
System.out.println("City " + library5.city);
System.out.println("State " + library5.state);
System.out.println("Country " + library5.country);
System.out.println("Established Year " + library5.establishedYear);
System.out.println("Parking Available " + library5.parkingAvailable);
System.out.println("Cafeteria Available " + library5.cafeteriaAvailable);
System.out.println("Library Code " + library5.libraryCode);
System.out.println("Website " + library5.website);
System.out.println("Membership Available " + library5.membershipAvailable);

Library library6 = new Library();

System.out.println("Before Initialization of Library6");

System.out.println("Library ID is " + library6.libraryId);
System.out.println("Library Name is " + library6.libraryName);
System.out.println("Library Location is " + library6.location);
System.out.println("Total Books are " + library6.totalBooks);
System.out.println("Staff Count is " + library6.staffCount);
System.out.println("Wifi Available " + library6.hasWifi);
System.out.println("Digital Section Available " + library6.hasDigitalSection);
System.out.println("Reading Room Available " + library6.hasReadingRoom);
System.out.println("AC Available " + library6.hasAC);
System.out.println("Is Library Open Today " + library6.openToday);
System.out.println("Librarian Name " + library6.librarianName);
System.out.println("Opening Time " + library6.openingTime);
System.out.println("Closing Time " + library6.closingTime);
System.out.println("Library Rating " + library6.rating);
System.out.println("Contact Number " + library6.contactNumber);
System.out.println("Email ID " + library6.email);
System.out.println("City " + library6.city);
System.out.println("State " + library6.state);
System.out.println("Country " + library6.country);
System.out.println("Established Year " + library6.establishedYear);
System.out.println("Parking Available " + library6.parkingAvailable);
System.out.println("Cafeteria Available " + library6.cafeteriaAvailable);
System.out.println("Library Code " + library6.libraryCode);
System.out.println("Website " + library6.website);
System.out.println("Membership Available " + library6.membershipAvailable);

library6.libraryId = 6;
library6.libraryName = "Research Library";
library6.location = "Bangalore";
library6.totalBooks = 45000;
library6.staffCount = 18;
library6.hasWifi = true;
library6.hasDigitalSection = true;
library6.hasReadingRoom = true;
library6.hasAC = true;
library6.openToday = true;
library6.librarianName = "Mahesh";
library6.openingTime = "9AM";
library6.closingTime = "9PM";
library6.rating = 4.4;
library6.contactNumber = "9988001122";
library6.email = "research@library.com";
library6.city = "Bangalore";
library6.state = "Karnataka";
library6.country = "India";
library6.establishedYear = 1992;
library6.parkingAvailable = true;
library6.cafeteriaAvailable = false;
library6.libraryCode = "LIB106";
library6.website = "www.researchlibrary.com";
library6.membershipAvailable = true;

System.out.println("After Initialization of Library6");

System.out.println("Library ID is " + library6.libraryId);
System.out.println("Library Name is " + library6.libraryName);
System.out.println("Library Location is " + library6.location);
System.out.println("Total Books are " + library6.totalBooks);
System.out.println("Staff Count is " + library6.staffCount);
System.out.println("Wifi Available " + library6.hasWifi);
System.out.println("Digital Section Available " + library6.hasDigitalSection);
System.out.println("Reading Room Available " + library6.hasReadingRoom);
System.out.println("AC Available " + library6.hasAC);
System.out.println("Is Library Open Today " + library6.openToday);
System.out.println("Librarian Name " + library6.librarianName);
System.out.println("Opening Time " + library6.openingTime);
System.out.println("Closing Time " + library6.closingTime);
System.out.println("Library Rating " + library6.rating);
System.out.println("Contact Number " + library6.contactNumber);
System.out.println("Email ID " + library6.email);
System.out.println("City " + library6.city);
System.out.println("State " + library6.state);
System.out.println("Country " + library6.country);
System.out.println("Established Year " + library6.establishedYear);
System.out.println("Parking Available " + library6.parkingAvailable);
System.out.println("Cafeteria Available " + library6.cafeteriaAvailable);
System.out.println("Library Code " + library6.libraryCode);
System.out.println("Website " + library6.website);
System.out.println("Membership Available " + library6.membershipAvailable);


Library library7 = new Library();

System.out.println("Before Initialization of Library7");

System.out.println("Library ID is " + library7.libraryId);
System.out.println("Library Name is " + library7.libraryName);
System.out.println("Library Location is " + library7.location);
System.out.println("Total Books are " + library7.totalBooks);
System.out.println("Staff Count is " + library7.staffCount);
System.out.println("Wifi Available " + library7.hasWifi);
System.out.println("Digital Section Available " + library7.hasDigitalSection);
System.out.println("Reading Room Available " + library7.hasReadingRoom);
System.out.println("AC Available " + library7.hasAC);
System.out.println("Is Library Open Today " + library7.openToday);
System.out.println("Librarian Name " + library7.librarianName);
System.out.println("Opening Time " + library7.openingTime);
System.out.println("Closing Time " + library7.closingTime);
System.out.println("Library Rating " + library7.rating);
System.out.println("Contact Number " + library7.contactNumber);
System.out.println("Email ID " + library7.email);
System.out.println("City " + library7.city);
System.out.println("State " + library7.state);
System.out.println("Country " + library7.country);
System.out.println("Established Year " + library7.establishedYear);
System.out.println("Parking Available " + library7.parkingAvailable);
System.out.println("Cafeteria Available " + library7.cafeteriaAvailable);
System.out.println("Library Code " + library7.libraryCode);
System.out.println("Website " + library7.website);
System.out.println("Membership Available " + library7.membershipAvailable);

library7.libraryId = 7;
library7.libraryName = "Science Library";
library7.location = "Hyderabad";
library7.totalBooks = 38000;
library7.staffCount = 16;
library7.hasWifi = true;
library7.hasDigitalSection = true;
library7.hasReadingRoom = true;
library7.hasAC = true;
library7.openToday = true;
library7.librarianName = "Raghav";
library7.openingTime = "9AM";
library7.closingTime = "9PM";
library7.rating = 4.3;
library7.contactNumber = "9871234567";
library7.email = "science@library.com";
library7.city = "Hyderabad";
library7.state = "Telangana";
library7.country = "India";
library7.establishedYear = 1998;
library7.parkingAvailable = true;
library7.cafeteriaAvailable = false;
library7.libraryCode = "LIB107";
library7.website = "www.sciencelibrary.com";
library7.membershipAvailable = true;

System.out.println("After Initialization of Library7");

System.out.println("Library ID is " + library7.libraryId);
System.out.println("Library Name is " + library7.libraryName);
System.out.println("Library Location is " + library7.location);
System.out.println("Total Books are " + library7.totalBooks);
System.out.println("Staff Count is " + library7.staffCount);
System.out.println("Wifi Available " + library7.hasWifi);
System.out.println("Digital Section Available " + library7.hasDigitalSection);
System.out.println("Reading Room Available " + library7.hasReadingRoom);
System.out.println("AC Available " + library7.hasAC);
System.out.println("Is Library Open Today " + library7.openToday);
System.out.println("Librarian Name " + library7.librarianName);
System.out.println("Opening Time " + library7.openingTime);
System.out.println("Closing Time " + library7.closingTime);
System.out.println("Library Rating " + library7.rating);
System.out.println("Contact Number " + library7.contactNumber);
System.out.println("Email ID " + library7.email);
System.out.println("City " + library7.city);
System.out.println("State " + library7.state);
System.out.println("Country " + library7.country);
System.out.println("Established Year " + library7.establishedYear);
System.out.println("Parking Available " + library7.parkingAvailable);
System.out.println("Cafeteria Available " + library7.cafeteriaAvailable);
System.out.println("Library Code " + library7.libraryCode);
System.out.println("Website " + library7.website);
System.out.println("Membership Available " + library7.membershipAvailable);


Library library8 = new Library();

System.out.println("Before Initialization of Library8");

System.out.println("Library ID is " + library8.libraryId);
System.out.println("Library Name is " + library8.libraryName);
System.out.println("Library Location is " + library8.location);
System.out.println("Total Books are " + library8.totalBooks);
System.out.println("Staff Count is " + library8.staffCount);
System.out.println("Wifi Available " + library8.hasWifi);
System.out.println("Digital Section Available " + library8.hasDigitalSection);
System.out.println("Reading Room Available " + library8.hasReadingRoom);
System.out.println("AC Available " + library8.hasAC);
System.out.println("Is Library Open Today " + library8.openToday);
System.out.println("Librarian Name " + library8.librarianName);
System.out.println("Opening Time " + library8.openingTime);
System.out.println("Closing Time " + library8.closingTime);
System.out.println("Library Rating " + library8.rating);
System.out.println("Contact Number " + library8.contactNumber);
System.out.println("Email ID " + library8.email);
System.out.println("City " + library8.city);
System.out.println("State " + library8.state);
System.out.println("Country " + library8.country);
System.out.println("Established Year " + library8.establishedYear);
System.out.println("Parking Available " + library8.parkingAvailable);
System.out.println("Cafeteria Available " + library8.cafeteriaAvailable);
System.out.println("Library Code " + library8.libraryCode);
System.out.println("Website " + library8.website);
System.out.println("Membership Available " + library8.membershipAvailable);

library8.libraryId = 8;
library8.libraryName = "Technology Library";
library8.location = "Pune";
library8.totalBooks = 42000;
library8.staffCount = 22;
library8.hasWifi = true;
library8.hasDigitalSection = true;
library8.hasReadingRoom = true;
library8.hasAC = true;
library8.openToday = true;
library8.librarianName = "Ajay";
library8.openingTime = "8AM";
library8.closingTime = "9PM";
library8.rating = 4.6;
library8.contactNumber = "9887766554";
library8.email = "tech@library.com";
library8.city = "Pune";
library8.state = "Maharashtra";
library8.country = "India";
library8.establishedYear = 2003;
library8.parkingAvailable = true;
library8.cafeteriaAvailable = true;
library8.libraryCode = "LIB108";
library8.website = "www.techlibrary.com";
library8.membershipAvailable = true;

System.out.println("After Initialization of Library8");

System.out.println("Library ID is " + library8.libraryId);
System.out.println("Library Name is " + library8.libraryName);
System.out.println("Library Location is " + library8.location);
System.out.println("Total Books are " + library8.totalBooks);
System.out.println("Staff Count is " + library8.staffCount);
System.out.println("Wifi Available " + library8.hasWifi);
System.out.println("Digital Section Available " + library8.hasDigitalSection);
System.out.println("Reading Room Available " + library8.hasReadingRoom);
System.out.println("AC Available " + library8.hasAC);
System.out.println("Is Library Open Today " + library8.openToday);
System.out.println("Librarian Name " + library8.librarianName);
System.out.println("Opening Time " + library8.openingTime);
System.out.println("Closing Time " + library8.closingTime);
System.out.println("Library Rating " + library8.rating);
System.out.println("Contact Number " + library8.contactNumber);
System.out.println("Email ID " + library8.email);
System.out.println("City " + library8.city);
System.out.println("State " + library8.state);
System.out.println("Country " + library8.country);
System.out.println("Established Year " + library8.establishedYear);
System.out.println("Parking Available " + library8.parkingAvailable);
System.out.println("Cafeteria Available " + library8.cafeteriaAvailable);
System.out.println("Library Code " + library8.libraryCode);
System.out.println("Website " + library8.website);
System.out.println("Membership Available " + library8.membershipAvailable);


Library library9 = new Library();

System.out.println("Before Initialization of Library9");

System.out.println("Library ID is " + library9.libraryId);
System.out.println("Library Name is " + library9.libraryName);
System.out.println("Library Location is " + library9.location);
System.out.println("Total Books are " + library9.totalBooks);
System.out.println("Staff Count is " + library9.staffCount);
System.out.println("Wifi Available " + library9.hasWifi);
System.out.println("Digital Section Available " + library9.hasDigitalSection);
System.out.println("Reading Room Available " + library9.hasReadingRoom);
System.out.println("AC Available " + library9.hasAC);
System.out.println("Is Library Open Today " + library9.openToday);
System.out.println("Librarian Name " + library9.librarianName);
System.out.println("Opening Time " + library9.openingTime);
System.out.println("Closing Time " + library9.closingTime);
System.out.println("Library Rating " + library9.rating);
System.out.println("Contact Number " + library9.contactNumber);
System.out.println("Email ID " + library9.email);
System.out.println("City " + library9.city);
System.out.println("State " + library9.state);
System.out.println("Country " + library9.country);
System.out.println("Established Year " + library9.establishedYear);
System.out.println("Parking Available " + library9.parkingAvailable);
System.out.println("Cafeteria Available " + library9.cafeteriaAvailable);
System.out.println("Library Code " + library9.libraryCode);
System.out.println("Website " + library9.website);
System.out.println("Membership Available " + library9.membershipAvailable);


library9.libraryId = 9;
library9.libraryName = "Medical Library";
library9.location = "Chennai";
library9.totalBooks = 32000;
library9.staffCount = 14;
library9.hasWifi = true;
library9.hasDigitalSection = true;
library9.hasReadingRoom = true;
library9.hasAC = true;
library9.openToday = true;
library9.librarianName = "Dr. Kumar";
library9.openingTime = "8AM";
library9.closingTime = "8PM";
library9.rating = 4.4;
library9.contactNumber = "9876501234";
library9.email = "medical@library.com";
library9.city = "Chennai";
library9.state = "Tamil Nadu";
library9.country = "India";
library9.establishedYear = 1996;
library9.parkingAvailable = true;
library9.cafeteriaAvailable = false;
library9.libraryCode = "LIB109";
library9.website = "www.medicallibrary.com";
library9.membershipAvailable = true;

System.out.println("After Initialization of Library9");

System.out.println("Library ID is " + library9.libraryId);
System.out.println("Library Name is " + library9.libraryName);
System.out.println("Library Location is " + library9.location);
System.out.println("Total Books are " + library9.totalBooks);
System.out.println("Staff Count is " + library9.staffCount);
System.out.println("Wifi Available " + library9.hasWifi);
System.out.println("Digital Section Available " + library9.hasDigitalSection);
System.out.println("Reading Room Available " + library9.hasReadingRoom);
System.out.println("AC Available " + library9.hasAC);
System.out.println("Is Library Open Today " + library9.openToday);
System.out.println("Librarian Name " + library9.librarianName);
System.out.println("Opening Time " + library9.openingTime);
System.out.println("Closing Time " + library9.closingTime);
System.out.println("Library Rating " + library9.rating);
System.out.println("Contact Number " + library9.contactNumber);
System.out.println("Email ID " + library9.email);
System.out.println("City " + library9.city);
System.out.println("State " + library9.state);
System.out.println("Country " + library9.country);
System.out.println("Established Year " + library9.establishedYear);
System.out.println("Parking Available " + library9.parkingAvailable);
System.out.println("Cafeteria Available " + library9.cafeteriaAvailable);
System.out.println("Library Code " + library9.libraryCode);
System.out.println("Website " + library9.website);
System.out.println("Membership Available " + library9.membershipAvailable);

Library library10 = new Library();

System.out.println("Before Initialization of Library10");

System.out.println("Library ID is " + library10.libraryId);
System.out.println("Library Name is " + library10.libraryName);
System.out.println("Library Location is " + library10.location);
System.out.println("Total Books are " + library10.totalBooks);
System.out.println("Staff Count is " + library10.staffCount);
System.out.println("Wifi Available " + library10.hasWifi);
System.out.println("Digital Section Available " + library10.hasDigitalSection);
System.out.println("Reading Room Available " + library10.hasReadingRoom);
System.out.println("AC Available " + library10.hasAC);
System.out.println("Is Library Open Today " + library10.openToday);
System.out.println("Librarian Name " + library10.librarianName);
System.out.println("Opening Time " + library10.openingTime);
System.out.println("Closing Time " + library10.closingTime);
System.out.println("Library Rating " + library10.rating);
System.out.println("Contact Number " + library10.contactNumber);
System.out.println("Email ID " + library10.email);
System.out.println("City " + library10.city);
System.out.println("State " + library10.state);
System.out.println("Country " + library10.country);
System.out.println("Established Year " + library10.establishedYear);
System.out.println("Parking Available " + library10.parkingAvailable);
System.out.println("Cafeteria Available " + library10.cafeteriaAvailable);
System.out.println("Library Code " + library10.libraryCode);
System.out.println("Website " + library10.website);
System.out.println("Membership Available " + library10.membershipAvailable);


library10.libraryId = 10;
library10.libraryName = "Engineering Library";
library10.location = "Mumbai";
library10.totalBooks = 47000;
library10.staffCount = 21;
library10.hasWifi = true;
library10.hasDigitalSection = true;
library10.hasReadingRoom = true;
library10.hasAC = true;
library10.openToday = true;
library10.librarianName = "Rajesh";
library10.openingTime = "8AM";
library10.closingTime = "10PM";
library10.rating = 4.7;
library10.contactNumber = "9898989898";
library10.email = "engineering@library.com";
library10.city = "Mumbai";
library10.state = "Maharashtra";
library10.country = "India";
library10.establishedYear = 2001;
library10.parkingAvailable = true;
library10.cafeteriaAvailable = true;
library10.libraryCode = "LIB110";
library10.website = "www.engineeringlibrary.com";
library10.membershipAvailable = true;

System.out.println("After Initialization of Library10");

System.out.println("Library ID is " + library10.libraryId);
System.out.println("Library Name is " + library10.libraryName);
System.out.println("Library Location is " + library10.location);
System.out.println("Total Books are " + library10.totalBooks);
System.out.println("Staff Count is " + library10.staffCount);
System.out.println("Wifi Available " + library10.hasWifi);
System.out.println("Digital Section Available " + library10.hasDigitalSection);
System.out.println("Reading Room Available " + library10.hasReadingRoom);
System.out.println("AC Available " + library10.hasAC);
System.out.println("Is Library Open Today " + library10.openToday);
System.out.println("Librarian Name " + library10.librarianName);
System.out.println("Opening Time " + library10.openingTime);
System.out.println("Closing Time " + library10.closingTime);
System.out.println("Library Rating " + library10.rating);
System.out.println("Contact Number " + library10.contactNumber);
System.out.println("Email ID " + library10.email);
System.out.println("City " + library10.city);
System.out.println("State " + library10.state);
System.out.println("Country " + library10.country);
System.out.println("Established Year " + library10.establishedYear);
System.out.println("Parking Available " + library10.parkingAvailable);
System.out.println("Cafeteria Available " + library10.cafeteriaAvailable);
System.out.println("Library Code " + library10.libraryCode);
System.out.println("Website " + library10.website);
System.out.println("Membership Available " + library10.membershipAvailable);

Library library11 = new Library();

System.out.println("Before Initialization of Library11");

System.out.println("Library ID is " + library11.libraryId);
System.out.println("Library Name is " + library11.libraryName);
System.out.println("Library Location is " + library11.location);
System.out.println("Total Books are " + library11.totalBooks);
System.out.println("Staff Count is " + library11.staffCount);
System.out.println("Wifi Available " + library11.hasWifi);
System.out.println("Digital Section Available " + library11.hasDigitalSection);
System.out.println("Reading Room Available " + library11.hasReadingRoom);
System.out.println("AC Available " + library11.hasAC);
System.out.println("Is Library Open Today " + library11.openToday);
System.out.println("Librarian Name " + library11.librarianName);
System.out.println("Opening Time " + library11.openingTime);
System.out.println("Closing Time " + library11.closingTime);
System.out.println("Library Rating " + library11.rating);
System.out.println("Contact Number " + library11.contactNumber);
System.out.println("Email ID " + library11.email);
System.out.println("City " + library11.city);
System.out.println("State " + library11.state);
System.out.println("Country " + library11.country);
System.out.println("Established Year " + library11.establishedYear);
System.out.println("Parking Available " + library11.parkingAvailable);
System.out.println("Cafeteria Available " + library11.cafeteriaAvailable);
System.out.println("Library Code " + library11.libraryCode);
System.out.println("Website " + library11.website);
System.out.println("Membership Available " + library11.membershipAvailable);


library11.libraryId = 11;
library11.libraryName = "Law Library";
library11.location = "Delhi";
library11.totalBooks = 28000;
library11.staffCount = 13;
library11.hasWifi = true;
library11.hasDigitalSection = true;
library11.hasReadingRoom = true;
library11.hasAC = true;
library11.openToday = true;
library11.librarianName = "Vikram";
library11.openingTime = "9AM";
library11.closingTime = "8PM";
library11.rating = 4.3;
library11.contactNumber = "9876541111";
library11.email = "law@library.com";
library11.city = "Delhi";
library11.state = "Delhi";
library11.country = "India";
library11.establishedYear = 1993;
library11.parkingAvailable = true;
library11.cafeteriaAvailable = false;
library11.libraryCode = "LIB111";
library11.website = "www.lawlibrary.com";
library11.membershipAvailable = true;

System.out.println("After Initialization of Library11");

System.out.println("Library ID is " + library11.libraryId);
System.out.println("Library Name is " + library11.libraryName);
System.out.println("Library Location is " + library11.location);
System.out.println("Total Books are " + library11.totalBooks);
System.out.println("Staff Count is " + library11.staffCount);
System.out.println("Wifi Available " + library11.hasWifi);
System.out.println("Digital Section Available " + library11.hasDigitalSection);
System.out.println("Reading Room Available " + library11.hasReadingRoom);
System.out.println("AC Available " + library11.hasAC);
System.out.println("Is Library Open Today " + library11.openToday);
System.out.println("Librarian Name " + library11.librarianName);
System.out.println("Opening Time " + library11.openingTime);
System.out.println("Closing Time " + library11.closingTime);
System.out.println("Library Rating " + library11.rating);
System.out.println("Contact Number " + library11.contactNumber);
System.out.println("Email ID " + library11.email);
System.out.println("City " + library11.city);
System.out.println("State " + library11.state);
System.out.println("Country " + library11.country);
System.out.println("Established Year " + library11.establishedYear);
System.out.println("Parking Available " + library11.parkingAvailable);
System.out.println("Cafeteria Available " + library11.cafeteriaAvailable);
System.out.println("Library Code " + library11.libraryCode);
System.out.println("Website " + library11.website);
System.out.println("Membership Available " + library11.membershipAvailable);

Library library12 = new Library();

System.out.println("Before Initialization of Library12");

System.out.println("Library ID is " + library12.libraryId);
System.out.println("Library Name is " + library12.libraryName);
System.out.println("Library Location is " + library12.location);
System.out.println("Total Books are " + library12.totalBooks);
System.out.println("Staff Count is " + library12.staffCount);
System.out.println("Wifi Available " + library12.hasWifi);
System.out.println("Digital Section Available " + library12.hasDigitalSection);
System.out.println("Reading Room Available " + library12.hasReadingRoom);
System.out.println("AC Available " + library12.hasAC);
System.out.println("Is Library Open Today " + library12.openToday);
System.out.println("Librarian Name " + library12.librarianName);
System.out.println("Opening Time " + library12.openingTime);
System.out.println("Closing Time " + library12.closingTime);
System.out.println("Library Rating " + library12.rating);
System.out.println("Contact Number " + library12.contactNumber);
System.out.println("Email ID " + library12.email);
System.out.println("City " + library12.city);
System.out.println("State " + library12.state);
System.out.println("Country " + library12.country);
System.out.println("Established Year " + library12.establishedYear);
System.out.println("Parking Available " + library12.parkingAvailable);
System.out.println("Cafeteria Available " + library12.cafeteriaAvailable);
System.out.println("Library Code " + library12.libraryCode);
System.out.println("Website " + library12.website);
System.out.println("Membership Available " + library12.membershipAvailable);


library12.libraryId = 12;
library12.libraryName = "Digital Library";
library12.location = "Kolkata";
library12.totalBooks = 36000;
library12.staffCount = 17;
library12.hasWifi = true;
library12.hasDigitalSection = true;
library12.hasReadingRoom = true;
library12.hasAC = true;
library12.openToday = true;
library12.librarianName = "Arjun";
library12.openingTime = "8AM";
library12.closingTime = "9PM";
library12.rating = 4.5;
library12.contactNumber = "9876502222";
library12.email = "digital@library.com";
library12.city = "Kolkata";
library12.state = "West Bengal";
library12.country = "India";
library12.establishedYear = 2005;
library12.parkingAvailable = true;
library12.cafeteriaAvailable = true;
library12.libraryCode = "LIB112";
library12.website = "www.digitallibrary.com";
library12.membershipAvailable = true;

System.out.println("After Initialization of Library12");

System.out.println("Library ID is " + library12.libraryId);
System.out.println("Library Name is " + library12.libraryName);
System.out.println("Library Location is " + library12.location);
System.out.println("Total Books are " + library12.totalBooks);
System.out.println("Staff Count is " + library12.staffCount);
System.out.println("Wifi Available " + library12.hasWifi);
System.out.println("Digital Section Available " + library12.hasDigitalSection);
System.out.println("Reading Room Available " + library12.hasReadingRoom);
System.out.println("AC Available " + library12.hasAC);
System.out.println("Is Library Open Today " + library12.openToday);
System.out.println("Librarian Name " + library12.librarianName);
System.out.println("Opening Time " + library12.openingTime);
System.out.println("Closing Time " + library12.closingTime);
System.out.println("Library Rating " + library12.rating);
System.out.println("Contact Number " + library12.contactNumber);
System.out.println("Email ID " + library12.email);
System.out.println("City " + library12.city);
System.out.println("State " + library12.state);
System.out.println("Country " + library12.country);
System.out.println("Established Year " + library12.establishedYear);
System.out.println("Parking Available " + library12.parkingAvailable);
System.out.println("Cafeteria Available " + library12.cafeteriaAvailable);
System.out.println("Library Code " + library12.libraryCode);
System.out.println("Website " + library12.website);
System.out.println("Membership Available " + library12.membershipAvailable);

Library library13 = new Library();

System.out.println("Before Initialization of Library13");

System.out.println("Library ID is " + library13.libraryId);
System.out.println("Library Name is " + library13.libraryName);
System.out.println("Library Location is " + library13.location);
System.out.println("Total Books are " + library13.totalBooks);
System.out.println("Staff Count is " + library13.staffCount);
System.out.println("Wifi Available " + library13.hasWifi);
System.out.println("Digital Section Available " + library13.hasDigitalSection);
System.out.println("Reading Room Available " + library13.hasReadingRoom);
System.out.println("AC Available " + library13.hasAC);
System.out.println("Is Library Open Today " + library13.openToday);
System.out.println("Librarian Name " + library13.librarianName);
System.out.println("Opening Time " + library13.openingTime);
System.out.println("Closing Time " + library13.closingTime);
System.out.println("Library Rating " + library13.rating);
System.out.println("Contact Number " + library13.contactNumber);
System.out.println("Email ID " + library13.email);
System.out.println("City " + library13.city);
System.out.println("State " + library13.state);
System.out.println("Country " + library13.country);
System.out.println("Established Year " + library13.establishedYear);
System.out.println("Parking Available " + library13.parkingAvailable);
System.out.println("Cafeteria Available " + library13.cafeteriaAvailable);
System.out.println("Library Code " + library13.libraryCode);
System.out.println("Website " + library13.website);
System.out.println("Membership Available " + library13.membershipAvailable);


library13.libraryId = 13;
library13.libraryName = "City Knowledge Library";
library13.location = "Ahmedabad";
library13.totalBooks = 30000;
library13.staffCount = 14;
library13.hasWifi = true;
library13.hasDigitalSection = true;
library13.hasReadingRoom = true;
library13.hasAC = false;
library13.openToday = true;
library13.librarianName = "Rohit";
library13.openingTime = "9AM";
library13.closingTime = "8PM";
library13.rating = 4.2;
library13.contactNumber = "9876503333";
library13.email = "cityknowledge@library.com";
library13.city = "Ahmedabad";
library13.state = "Gujarat";
library13.country = "India";
library13.establishedYear = 1999;
library13.parkingAvailable = true;
library13.cafeteriaAvailable = false;
library13.libraryCode = "LIB113";
library13.website = "www.cityknowledge.com";
library13.membershipAvailable = true;

System.out.println("After Initialization of Library13");

System.out.println("Library ID is " + library13.libraryId);
System.out.println("Library Name is " + library13.libraryName);
System.out.println("Library Location is " + library13.location);
System.out.println("Total Books are " + library13.totalBooks);
System.out.println("Staff Count is " + library13.staffCount);
System.out.println("Wifi Available " + library13.hasWifi);
System.out.println("Digital Section Available " + library13.hasDigitalSection);
System.out.println("Reading Room Available " + library13.hasReadingRoom);
System.out.println("AC Available " + library13.hasAC);
System.out.println("Is Library Open Today " + library13.openToday);
System.out.println("Librarian Name " + library13.librarianName);
System.out.println("Opening Time " + library13.openingTime);
System.out.println("Closing Time " + library13.closingTime);
System.out.println("Library Rating " + library13.rating);
System.out.println("Contact Number " + library13.contactNumber);
System.out.println("Email ID " + library13.email);
System.out.println("City " + library13.city);
System.out.println("State " + library13.state);
System.out.println("Country " + library13.country);
System.out.println("Established Year " + library13.establishedYear);
System.out.println("Parking Available " + library13.parkingAvailable);
System.out.println("Cafeteria Available " + library13.cafeteriaAvailable);
System.out.println("Library Code " + library13.libraryCode);
System.out.println("Website " + library13.website);
System.out.println("Membership Available " + library13.membershipAvailable);

Library library14 = new Library();

System.out.println("Before Initialization of Library14");

System.out.println("Library ID is " + library14.libraryId);
System.out.println("Library Name is " + library14.libraryName);
System.out.println("Library Location is " + library14.location);
System.out.println("Total Books are " + library14.totalBooks);
System.out.println("Staff Count is " + library14.staffCount);
System.out.println("Wifi Available " + library14.hasWifi);
System.out.println("Digital Section Available " + library14.hasDigitalSection);
System.out.println("Reading Room Available " + library14.hasReadingRoom);
System.out.println("AC Available " + library14.hasAC);
System.out.println("Is Library Open Today " + library14.openToday);
System.out.println("Librarian Name " + library14.librarianName);
System.out.println("Opening Time " + library14.openingTime);
System.out.println("Closing Time " + library14.closingTime);
System.out.println("Library Rating " + library14.rating);
System.out.println("Contact Number " + library14.contactNumber);
System.out.println("Email ID " + library14.email);
System.out.println("City " + library14.city);
System.out.println("State " + library14.state);
System.out.println("Country " + library14.country);
System.out.println("Established Year " + library14.establishedYear);
System.out.println("Parking Available " + library14.parkingAvailable);
System.out.println("Cafeteria Available " + library14.cafeteriaAvailable);
System.out.println("Library Code " + library14.libraryCode);
System.out.println("Website " + library14.website);
System.out.println("Membership Available " + library14.membershipAvailable);


library14.libraryId = 14;
library14.libraryName = "Community Library";
library14.location = "Jaipur";
library14.totalBooks = 26000;
library14.staffCount = 11;
library14.hasWifi = true;
library14.hasDigitalSection = false;
library14.hasReadingRoom = true;
library14.hasAC = false;
library14.openToday = true;
library14.librarianName = "Manoj";
library14.openingTime = "8AM";
library14.closingTime = "7PM";
library14.rating = 4.0;
library14.contactNumber = "9876504444";
library14.email = "community@library.com";
library14.city = "Jaipur";
library14.state = "Rajasthan";
library14.country = "India";
library14.establishedYear = 2002;
library14.parkingAvailable = true;
library14.cafeteriaAvailable = false;
library14.libraryCode = "LIB114";
library14.website = "www.communitylibrary.com";
library14.membershipAvailable = true;

System.out.println("After Initialization of Library14");

System.out.println("Library ID is " + library14.libraryId);
System.out.println("Library Name is " + library14.libraryName);
System.out.println("Library Location is " + library14.location);
System.out.println("Total Books are " + library14.totalBooks);
System.out.println("Staff Count is " + library14.staffCount);
System.out.println("Wifi Available " + library14.hasWifi);
System.out.println("Digital Section Available " + library14.hasDigitalSection);
System.out.println("Reading Room Available " + library14.hasReadingRoom);
System.out.println("AC Available " + library14.hasAC);
System.out.println("Is Library Open Today " + library14.openToday);
System.out.println("Librarian Name " + library14.librarianName);
System.out.println("Opening Time " + library14.openingTime);
System.out.println("Closing Time " + library14.closingTime);
System.out.println("Library Rating " + library14.rating);
System.out.println("Contact Number " + library14.contactNumber);
System.out.println("Email ID " + library14.email);
System.out.println("City " + library14.city);
System.out.println("State " + library14.state);
System.out.println("Country " + library14.country);
System.out.println("Established Year " + library14.establishedYear);
System.out.println("Parking Available " + library14.parkingAvailable);
System.out.println("Cafeteria Available " + library14.cafeteriaAvailable);
System.out.println("Library Code " + library14.libraryCode);
System.out.println("Website " + library14.website);
System.out.println("Membership Available " + library14.membershipAvailable);

Library library15 = new Library();

System.out.println("Before Initialization of Library15");

System.out.println("Library ID is " + library15.libraryId);
System.out.println("Library Name is " + library15.libraryName);
System.out.println("Library Location is " + library15.location);
System.out.println("Total Books are " + library15.totalBooks);
System.out.println("Staff Count is " + library15.staffCount);
System.out.println("Wifi Available " + library15.hasWifi);
System.out.println("Digital Section Available " + library15.hasDigitalSection);
System.out.println("Reading Room Available " + library15.hasReadingRoom);
System.out.println("AC Available " + library15.hasAC);
System.out.println("Is Library Open Today " + library15.openToday);
System.out.println("Librarian Name " + library15.librarianName);
System.out.println("Opening Time " + library15.openingTime);
System.out.println("Closing Time " + library15.closingTime);
System.out.println("Library Rating " + library15.rating);
System.out.println("Contact Number " + library15.contactNumber);
System.out.println("Email ID " + library15.email);
System.out.println("City " + library15.city);
System.out.println("State " + library15.state);
System.out.println("Country " + library15.country);
System.out.println("Established Year " + library15.establishedYear);
System.out.println("Parking Available " + library15.parkingAvailable);
System.out.println("Cafeteria Available " + library15.cafeteriaAvailable);
System.out.println("Library Code " + library15.libraryCode);
System.out.println("Website " + library15.website);
System.out.println("Membership Available " + library15.membershipAvailable);

library15.libraryId = 15;
library15.libraryName = "National Knowledge Library";
library15.location = "Lucknow";
library15.totalBooks = 52000;
library15.staffCount = 24;
library15.hasWifi = true;
library15.hasDigitalSection = true;
library15.hasReadingRoom = true;
library15.hasAC = true;
library15.openToday = true;
library15.librarianName = "Sanjay";
library15.openingTime = "8AM";
library15.closingTime = "9PM";
library15.rating = 4.6;
library15.contactNumber = "9876505555";
library15.email = "national@library.com";
library15.city = "Lucknow";
library15.state = "Uttar Pradesh";
library15.country = "India";
library15.establishedYear = 2008;
library15.parkingAvailable = true;
library15.cafeteriaAvailable = true;
library15.libraryCode = "LIB115";
library15.website = "www.nationallibrary.com";
library15.membershipAvailable = true;

System.out.println("After Initialization of Library15");

System.out.println("Library ID is " + library15.libraryId);
System.out.println("Library Name is " + library15.libraryName);
System.out.println("Library Location is " + library15.location);
System.out.println("Total Books are " + library15.totalBooks);
System.out.println("Staff Count is " + library15.staffCount);
System.out.println("Wifi Available " + library15.hasWifi);
System.out.println("Digital Section Available " + library15.hasDigitalSection);
System.out.println("Reading Room Available " + library15.hasReadingRoom);
System.out.println("AC Available " + library15.hasAC);
System.out.println("Is Library Open Today " + library15.openToday);
System.out.println("Librarian Name " + library15.librarianName);
System.out.println("Opening Time " + library15.openingTime);
System.out.println("Closing Time " + library15.closingTime);
System.out.println("Library Rating " + library15.rating);
System.out.println("Contact Number " + library15.contactNumber);
System.out.println("Email ID " + library15.email);
System.out.println("City " + library15.city);
System.out.println("State " + library15.state);
System.out.println("Country " + library15.country);
System.out.println("Established Year " + library15.establishedYear);
System.out.println("Parking Available " + library15.parkingAvailable);
System.out.println("Cafeteria Available " + library15.cafeteriaAvailable);
System.out.println("Library Code " + library15.libraryCode);
System.out.println("Website " + library15.website);
System.out.println("Membership Available " + library15.membershipAvailable);

Library library16 = new Library();

System.out.println("Before Initialization of Library16");

System.out.println("Library ID is " + library16.libraryId);
System.out.println("Library Name is " + library16.libraryName);
System.out.println("Library Location is " + library16.location);
System.out.println("Total Books are " + library16.totalBooks);
System.out.println("Staff Count is " + library16.staffCount);
System.out.println("Wifi Available " + library16.hasWifi);
System.out.println("Digital Section Available " + library16.hasDigitalSection);
System.out.println("Reading Room Available " + library16.hasReadingRoom);
System.out.println("AC Available " + library16.hasAC);
System.out.println("Is Library Open Today " + library16.openToday);
System.out.println("Librarian Name " + library16.librarianName);
System.out.println("Opening Time " + library16.openingTime);
System.out.println("Closing Time " + library16.closingTime);
System.out.println("Library Rating " + library16.rating);
System.out.println("Contact Number " + library16.contactNumber);
System.out.println("Email ID " + library16.email);
System.out.println("City " + library16.city);
System.out.println("State " + library16.state);
System.out.println("Country " + library16.country);
System.out.println("Established Year " + library16.establishedYear);
System.out.println("Parking Available " + library16.parkingAvailable);
System.out.println("Cafeteria Available " + library16.cafeteriaAvailable);
System.out.println("Library Code " + library16.libraryCode);
System.out.println("Website " + library16.website);
System.out.println("Membership Available " + library16.membershipAvailable);

library16.libraryId = 16;
library16.libraryName = "Smart Study Library";
library16.location = "Bhopal";
library16.totalBooks = 34000;
library16.staffCount = 15;
library16.hasWifi = true;
library16.hasDigitalSection = true;
library16.hasReadingRoom = true;
library16.hasAC = true;
library16.openToday = true;
library16.librarianName = "Amit";
library16.openingTime = "9AM";
library16.closingTime = "9PM";
library16.rating = 4.3;
library16.contactNumber = "9876506666";
library16.email = "smartstudy@library.com";
library16.city = "Bhopal";
library16.state = "Madhya Pradesh";
library16.country = "India";
library16.establishedYear = 2012;
library16.parkingAvailable = true;
library16.cafeteriaAvailable = false;
library16.libraryCode = "LIB116";
library16.website = "www.smartstudylibrary.com";
library16.membershipAvailable = true;

System.out.println("After Initialization of Library16");

System.out.println("Library ID is " + library16.libraryId);
System.out.println("Library Name is " + library16.libraryName);
System.out.println("Library Location is " + library16.location);
System.out.println("Total Books are " + library16.totalBooks);
System.out.println("Staff Count is " + library16.staffCount);
System.out.println("Wifi Available " + library16.hasWifi);
System.out.println("Digital Section Available " + library16.hasDigitalSection);
System.out.println("Reading Room Available " + library16.hasReadingRoom);
System.out.println("AC Available " + library16.hasAC);
System.out.println("Is Library Open Today " + library16.openToday);
System.out.println("Librarian Name " + library16.librarianName);
System.out.println("Opening Time " + library16.openingTime);
System.out.println("Closing Time " + library16.closingTime);
System.out.println("Library Rating " + library16.rating);
System.out.println("Contact Number " + library16.contactNumber);
System.out.println("Email ID " + library16.email);
System.out.println("City " + library16.city);
System.out.println("State " + library16.state);
System.out.println("Country " + library16.country);
System.out.println("Established Year " + library16.establishedYear);
System.out.println("Parking Available " + library16.parkingAvailable);
System.out.println("Cafeteria Available " + library16.cafeteriaAvailable);
System.out.println("Library Code " + library16.libraryCode);
System.out.println("Website " + library16.website);
System.out.println("Membership Available " + library16.membershipAvailable);

Library library17 = new Library();

System.out.println("Before Initialization of Library17");

System.out.println("Library ID is " + library17.libraryId);
System.out.println("Library Name is " + library17.libraryName);
System.out.println("Library Location is " + library17.location);
System.out.println("Total Books are " + library17.totalBooks);
System.out.println("Staff Count is " + library17.staffCount);
System.out.println("Wifi Available " + library17.hasWifi);
System.out.println("Digital Section Available " + library17.hasDigitalSection);
System.out.println("Reading Room Available " + library17.hasReadingRoom);
System.out.println("AC Available " + library17.hasAC);
System.out.println("Is Library Open Today " + library17.openToday);
System.out.println("Librarian Name " + library17.librarianName);
System.out.println("Opening Time " + library17.openingTime);
System.out.println("Closing Time " + library17.closingTime);
System.out.println("Library Rating " + library17.rating);
System.out.println("Contact Number " + library17.contactNumber);
System.out.println("Email ID " + library17.email);
System.out.println("City " + library17.city);
System.out.println("State " + library17.state);
System.out.println("Country " + library17.country);
System.out.println("Established Year " + library17.establishedYear);
System.out.println("Parking Available " + library17.parkingAvailable);
System.out.println("Cafeteria Available " + library17.cafeteriaAvailable);
System.out.println("Library Code " + library17.libraryCode);
System.out.println("Website " + library17.website);
System.out.println("Membership Available " + library17.membershipAvailable);

library17.libraryId = 17;
library17.libraryName = "Innovation Library";
library17.location = "Surat";
library17.totalBooks = 31000;
library17.staffCount = 12;
library17.hasWifi = true;
library17.hasDigitalSection = true;
library17.hasReadingRoom = true;
library17.hasAC = true;
library17.openToday = true;
library17.librarianName = "Harish";
library17.openingTime = "9AM";
library17.closingTime = "8PM";
library17.rating = 4.2;
library17.contactNumber = "9876507777";
library17.email = "innovation@library.com";
library17.city = "Surat";
library17.state = "Gujarat";
library17.country = "India";
library17.establishedYear = 2015;
library17.parkingAvailable = true;
library17.cafeteriaAvailable = false;
library17.libraryCode = "LIB117";
library17.website = "www.innovationlibrary.com";
library17.membershipAvailable = true;

System.out.println("After Initialization of Library17");

System.out.println("Library ID is " + library17.libraryId);
System.out.println("Library Name is " + library17.libraryName);
System.out.println("Library Location is " + library17.location);
System.out.println("Total Books are " + library17.totalBooks);
System.out.println("Staff Count is " + library17.staffCount);
System.out.println("Wifi Available " + library17.hasWifi);
System.out.println("Digital Section Available " + library17.hasDigitalSection);
System.out.println("Reading Room Available " + library17.hasReadingRoom);
System.out.println("AC Available " + library17.hasAC);
System.out.println("Is Library Open Today " + library17.openToday);
System.out.println("Librarian Name " + library17.librarianName);
System.out.println("Opening Time " + library17.openingTime);
System.out.println("Closing Time " + library17.closingTime);
System.out.println("Library Rating " + library17.rating);
System.out.println("Contact Number " + library17.contactNumber);
System.out.println("Email ID " + library17.email);
System.out.println("City " + library17.city);
System.out.println("State " + library17.state);
System.out.println("Country " + library17.country);
System.out.println("Established Year " + library17.establishedYear);
System.out.println("Parking Available " + library17.parkingAvailable);
System.out.println("Cafeteria Available " + library17.cafeteriaAvailable);
System.out.println("Library Code " + library17.libraryCode);
System.out.println("Website " + library17.website);
System.out.println("Membership Available " + library17.membershipAvailable);

Library library18 = new Library();

System.out.println("Before Initialization of Library18");

System.out.println("Library ID is " + library18.libraryId);
System.out.println("Library Name is " + library18.libraryName);
System.out.println("Library Location is " + library18.location);
System.out.println("Total Books are " + library18.totalBooks);
System.out.println("Staff Count is " + library18.staffCount);
System.out.println("Wifi Available " + library18.hasWifi);
System.out.println("Digital Section Available " + library18.hasDigitalSection);
System.out.println("Reading Room Available " + library18.hasReadingRoom);
System.out.println("AC Available " + library18.hasAC);
System.out.println("Is Library Open Today " + library18.openToday);
System.out.println("Librarian Name " + library18.librarianName);
System.out.println("Opening Time " + library18.openingTime);
System.out.println("Closing Time " + library18.closingTime);
System.out.println("Library Rating " + library18.rating);
System.out.println("Contact Number " + library18.contactNumber);
System.out.println("Email ID " + library18.email);
System.out.println("City " + library18.city);
System.out.println("State " + library18.state);
System.out.println("Country " + library18.country);
System.out.println("Established Year " + library18.establishedYear);
System.out.println("Parking Available " + library18.parkingAvailable);
System.out.println("Cafeteria Available " + library18.cafeteriaAvailable);
System.out.println("Library Code " + library18.libraryCode);
System.out.println("Website " + library18.website);
System.out.println("Membership Available " + library18.membershipAvailable);

library18.libraryId = 18;
library18.libraryName = "City Study Library";
library18.location = "Indore";
library18.totalBooks = 27000;
library18.staffCount = 11;
library18.hasWifi = true;
library18.hasDigitalSection = true;
library18.hasReadingRoom = true;
library18.hasAC = false;
library18.openToday = true;
library18.librarianName = "Deepak";
library18.openingTime = "9AM";
library18.closingTime = "8PM";
library18.rating = 4.1;
library18.contactNumber = "9876508888";
library18.email = "study@library.com";
library18.city = "Indore";
library18.state = "Madhya Pradesh";
library18.country = "India";
library18.establishedYear = 2006;
library18.parkingAvailable = true;
library18.cafeteriaAvailable = false;
library18.libraryCode = "LIB118";
library18.website = "www.studylibrary.com";
library18.membershipAvailable = true;

System.out.println("After Initialization of Library18");

System.out.println("Library ID is " + library18.libraryId);
System.out.println("Library Name is " + library18.libraryName);
System.out.println("Library Location is " + library18.location);
System.out.println("Total Books are " + library18.totalBooks);
System.out.println("Staff Count is " + library18.staffCount);
System.out.println("City is " + library18.city);

Library library19 = new Library();

System.out.println("Before Initialization of Library19");

System.out.println("Library ID is " + library19.libraryId);
System.out.println("Library Name is " + library19.libraryName);
System.out.println("Library Location is " + library19.location);
System.out.println("Total Books are " + library19.totalBooks);
System.out.println("Staff Count is " + library19.staffCount);
System.out.println("Wifi Available " + library19.hasWifi);
System.out.println("Digital Section Available " + library19.hasDigitalSection);
System.out.println("Reading Room Available " + library19.hasReadingRoom);
System.out.println("AC Available " + library19.hasAC);
System.out.println("Is Library Open Today " + library19.openToday);
System.out.println("Librarian Name " + library19.librarianName);
System.out.println("Opening Time " + library19.openingTime);
System.out.println("Closing Time " + library19.closingTime);
System.out.println("Library Rating " + library19.rating);
System.out.println("Contact Number " + library19.contactNumber);
System.out.println("Email ID " + library19.email);
System.out.println("City " + library19.city);
System.out.println("State " + library19.state);
System.out.println("Country " + library19.country);
System.out.println("Established Year " + library19.establishedYear);
System.out.println("Parking Available " + library19.parkingAvailable);
System.out.println("Cafeteria Available " + library19.cafeteriaAvailable);
System.out.println("Library Code " + library19.libraryCode);
System.out.println("Website " + library19.website);
System.out.println("Membership Available " + library19.membershipAvailable);

library19.libraryId = 19;
library19.libraryName = "Open Knowledge Library";
library19.location = "Nagpur";
library19.totalBooks = 24000;
library19.staffCount = 10;
library19.hasWifi = true;
library19.hasDigitalSection = false;
library19.hasReadingRoom = true;
library19.hasAC = false;
library19.openToday = true;
library19.librarianName = "Prakash";
library19.openingTime = "8AM";
library19.closingTime = "7PM";
library19.rating = 4.0;
library19.contactNumber = "9876509999";
library19.email = "open@library.com";
library19.city = "Nagpur";
library19.state = "Maharashtra";
library19.country = "India";
library19.establishedYear = 2004;
library19.parkingAvailable = true;
library19.cafeteriaAvailable = false;
library19.libraryCode = "LIB119";
library19.website = "www.openlibrary.com";
library19.membershipAvailable = true;

System.out.println("After Initialization of Library19");

System.out.println("Library ID is " + library19.libraryId);
System.out.println("Library Name is " + library19.libraryName);
System.out.println("Library Location is " + library19.location);
System.out.println("Total Books are " + library19.totalBooks);
System.out.println("Staff Count is " + library19.staffCount);
System.out.println("Wifi Available " + library19.hasWifi);
System.out.println("Digital Section Available " + library19.hasDigitalSection);
System.out.println("Reading Room Available " + library19.hasReadingRoom);
System.out.println("AC Available " + library19.hasAC);
System.out.println("Is Library Open Today " + library19.openToday);
System.out.println("Librarian Name " + library19.librarianName);
System.out.println("Opening Time " + library19.openingTime);
System.out.println("Closing Time " + library19.closingTime);
System.out.println("Library Rating " + library19.rating);
System.out.println("Contact Number " + library19.contactNumber);
System.out.println("Email ID " + library19.email);
System.out.println("City " + library19.city);
System.out.println("State " + library19.state);
System.out.println("Country " + library19.country);
System.out.println("Established Year " + library19.establishedYear);
System.out.println("Parking Available " + library19.parkingAvailable);
System.out.println("Cafeteria Available " + library19.cafeteriaAvailable);
System.out.println("Library Code " + library19.libraryCode);
System.out.println("Website " + library19.website);
System.out.println("Membership Available " + library19.membershipAvailable);

Library library20 = new Library();

System.out.println("Before Initialization of Library20");

System.out.println("Library ID is " + library20.libraryId);
System.out.println("Library Name is " + library20.libraryName);
System.out.println("Library Location is " + library20.location);
System.out.println("Total Books are " + library20.totalBooks);
System.out.println("Staff Count is " + library20.staffCount);
System.out.println("Wifi Available " + library20.hasWifi);
System.out.println("Digital Section Available " + library20.hasDigitalSection);
System.out.println("Reading Room Available " + library20.hasReadingRoom);
System.out.println("AC Available " + library20.hasAC);
System.out.println("Is Library Open Today " + library20.openToday);
System.out.println("Librarian Name " + library20.librarianName);
System.out.println("Opening Time " + library20.openingTime);
System.out.println("Closing Time " + library20.closingTime);
System.out.println("Library Rating " + library20.rating);
System.out.println("Contact Number " + library20.contactNumber);
System.out.println("Email ID " + library20.email);
System.out.println("City " + library20.city);
System.out.println("State " + library20.state);
System.out.println("Country " + library20.country);
System.out.println("Established Year " + library20.establishedYear);
System.out.println("Parking Available " + library20.parkingAvailable);
System.out.println("Cafeteria Available " + library20.cafeteriaAvailable);
System.out.println("Library Code " + library20.libraryCode);
System.out.println("Website " + library20.website);
System.out.println("Membership Available " + library20.membershipAvailable);

library20.libraryId = 20;
library20.libraryName = "Grand National Library";
library20.location = "Kochi";
library20.totalBooks = 55000;
library20.staffCount = 26;
library20.hasWifi = true;
library20.hasDigitalSection = true;
library20.hasReadingRoom = true;
library20.hasAC = true;
library20.openToday = true;
library20.librarianName = "Joseph";
library20.openingTime = "8AM";
library20.closingTime = "10PM";
library20.rating = 4.9;
library20.contactNumber = "9876510000";
library20.email = "grand@library.com";
library20.city = "Kochi";
library20.state = "Kerala";
library20.country = "India";
library20.establishedYear = 2010;
library20.parkingAvailable = true;
library20.cafeteriaAvailable = true;
library20.libraryCode = "LIB120";
library20.website = "www.grandlibrary.com";
library20.membershipAvailable = true;

System.out.println("After Initialization of Library20");

System.out.println("Library ID is " + library20.libraryId);
System.out.println("Library Name is " + library20.libraryName);
System.out.println("Library Location is " + library20.location);
System.out.println("Total Books are " + library20.totalBooks);
System.out.println("Staff Count is " + library20.staffCount);
System.out.println("Wifi Available " + library20.hasWifi);
System.out.println("Digital Section Available " + library20.hasDigitalSection);
System.out.println("Reading Room Available " + library20.hasReadingRoom);
System.out.println("AC Available " + library20.hasAC);
System.out.println("Is Library Open Today " + library20.openToday);
System.out.println("Librarian Name " + library20.librarianName);
System.out.println("Opening Time " + library20.openingTime);
System.out.println("Closing Time " + library20.closingTime);
System.out.println("Library Rating " + library20.rating);
System.out.println("Contact Number " + library20.contactNumber);
System.out.println("Email ID " + library20.email);
System.out.println("City " + library20.city);
System.out.println("State " + library20.state);
System.out.println("Country " + library20.country);
System.out.println("Established Year " + library20.establishedYear);
System.out.println("Parking Available " + library20.parkingAvailable);
System.out.println("Cafeteria Available " + library20.cafeteriaAvailable);
System.out.println("Library Code " + library20.libraryCode);
System.out.println("Website " + library20.website);
System.out.println("Membership Available " + library20.membershipAvailable);

}
}